path.n: NAMESPACE
path.d: DESCRIPTION
dir.r: R
dir.v: vignettes
dir.t: tests
extra.suggests:
  - bookdown
  - renv
  - remotes
  - covr
  - gitdown
  - testdown
  - thinkrtemplate
  - devtools
  - git2r
  - DT
  - htmltools
  - markdown
  - fusen
pkg_ignore:
  - bookdown
  - renv
  - remotes
  - covr
  - gitdown
  - testdown
  - thinkrtemplate
  - devtools
  - git2r
  - DT
  - htmltools
  - markdown
  - fusen
document: yes
normalize: yes
inside_rmd: no
must.exist: yes
check_if_suggests_is_installed: yes
