---
title: "flat_book_utils.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# paged_template

```{r function-paged_template}
#' Render pagedown html_paged
#'
#' @return A pagedown template
#' @inheritParams pagedown::html_paged
#' @export
#'
paged_template <- pagedown::html_paged
```

```{r examples-paged_template, eval=FALSE}
#' \dontrun{
bookdown::render_book("index.Rmd", output_format = "lozen::paged_template")
#' }
```

```{r tests-paged_template}
test_that("paged_template works", {
  skip_on_ci()
  
  withr::with_tempdir({
    
    lozen::create_r_project(
      project_path = getwd(),
      type = "book",
      type_licence = usethis::use_mit_license,
      name_licence = "Bibi"
    )

    bookdown::render_book("index.Rmd", output_format = "lozen::paged_template")

    expect_true(
      file.exists(file.path(getwd(), "_main.html"))
    )
  })
})
```

# bs4_book_template
    
```{r function-bs4_book_template}
#' Render bookdown bs4book
#'
#' @return A pagedown template
#' @inheritParams bookdown::bs4_book
#' @importFrom bookdown bs4_book
#' @export
#'
bs4_book_template <- bookdown::bs4_book
```
  
```{r example-bs4_book_template, eval=FALSE}
#' \dontrun{
bookdown::render_book("index.Rmd", output_format = "lozen::bs4_book_template")
#' }
```
  
```{r tests-bs4_book_template}
test_that("bs4_book_template works", {
  expect_true(inherits(bs4_book_template, "function"))
  skip_on_ci()
  withr::with_tempdir({
    lozen::create_r_project(
      project_path = getwd(),
      type = "book",
      type_licence = usethis::use_mit_license,
      name_licence = "Bibi"
    )

    bookdown::render_book("index.Rmd", output_format = "lozen::bs4_book_template")

    expect_true(
      dir.exists(file.path(getwd(), "_book"))
    )

    expect_true(
      file.exists(file.path(getwd(), "_book", "index.html"))
    )
  })
})
```

# render_book
    
```{r function-render_book}
#' Render a book with lozen formats
#' 
#' @param rmd_to_render rmd file to render
#' @param output_format format to be user to render the book
#' @param output_dir output directory
#' @param ... extra params to be used in bookdown::render_book
#' @importFrom bookdown render_book
#' @importFrom cli cli_alert_info cli_alert_warning
#' 
#' @return a rendered book
#' 
#' @export
render_book <- function(
  rmd_to_render = "index.Rmd",
  output_format = c("lozen::bs4_book_template", "lozen::paged_template"),
  output_dir = "_book",
   ...){
    
match.arg(output_format, c("lozen::bs4_book_template", "lozen::paged_template"))

book_format <- output_format[1]

if(book_format == "lozen::bs4_book_template") {
  bookdown::render_book(
    input = rmd_to_render,
    output_format = output_format,
    output_dir = output_dir,
    ... )
} else if(book_format == "lozen::paged_template") {
  # avec "lozen::paged_template" le output_dir n'est pas pris en compte, on va bouger le fichier produit a posteriori
  bookdown::render_book(
    input = rmd_to_render,
    output_format = output_format,    
    ... )
    if(!dir.exists(output_dir)) {
      dir.create(output_dir)
    }
      file.copy(
        "_main.html",
      file.path(output_dir, "_main.html")
       )
       unlink("_main.html")
    }

  cli_alert_info(paste0("Your book has been rendered in the directory ", output_dir)) 
  cli_alert_warning("Please ensure this directory in not listed in your `.gitignore` file !")
}  

```
  
```{r example-render_book, eval=FALSE}
#' \dontrun{
render_book("index.Rmd", output_format = "lozen::bs4_book_template")
render_book("index.Rmd", output_format = "lozen::paged_template")
#' }
```
  
```{r tests-render_book}
test_that("render_book works", {
  expect_true(inherits(render_book, "function")) 
})
```
   
# html_to_odt
    
```{r function-html_to_odt}
#' Convert html to odt with template
#' @param input_html Path to html file to convert
#' @param output_odt Path to odt to create
#' @export
html_to_odt <- function(input_html = "_main.html", output_odt = "_main.odt") {
  compil_dir <- dirname(input_html)
  # Get template
  # detect if "pandoc/" dir is present
  if (!dir.exists(file.path(compil_dir, "pandoc"))) {
    fs::dir_copy(
      system.file("pandoc", package = "lozen"),
      compil_dir)
  }
  
  # Create config.pandoc
  cat('quiet:\ndata-dir:', file.path(compil_dir, "pandoc"), sep = " ",
      file = file.path(compil_dir, "config.pandoc"))
  
  # odt first, html then
  message("Convert to odt with pandoc: ", basename(output_odt))
  knitr::pandoc(input = input_html,
                format = "odt", ext = ".odt",
                config = file.path(compil_dir, "config.pandoc"))
  
  outodt_intermediate <- gsub("[.]html", ".odt", input_html)
  file.copy(outodt_intermediate, output_odt)
  file.remove(outodt_intermediate)
  file.remove(file.path(compil_dir, "config.pandoc"))
  message(basename(output_odt), " file created")
}

```
  
```{r example-html_to_odt, eval=FALSE}
#' \dontrun{
html_to_odt(input_html = "_main.html", output_odt = "_main.odt")
#'}
```
  
```{r tests-html_to_odt}
test_that("html_to_odt works", {
  expect_true(inherits(html_to_odt, "function")) 
})
```
  
# compile_fiche
    
```{r function-compile_fiche}
#' Compile a unique "fiche" Rmd
#' @param fiche Path to fiche Rmd
#' @param outdir Directory where to save the output HTML
#' @param type Choose output type: html or odt
#' @param open Logical. Whether to open file at the end
#' @return compiled fiches
#' @noRd 
compile_fiche <- function(fiche, outdir = "public", type = "html", open = TRUE) {
  type <- match.arg(type, choices = c("html", "odt"), several.ok = TRUE)
  
  fiche <- normalizePath(fiche, mustWork = TRUE)
  if (!dir.exists(outdir)) {
    dir.create(outdir, recursive = TRUE)
  }
  
  # copy all except Rmd in tempdir
  compil_dir <- tempfile("compildir")
  fs::dir_copy(dirname(fiche), compil_dir)
  
  all_rmds <- list.files(compil_dir, pattern = "[.](R|r)md",
                         full.names = TRUE, recursive = FALSE)
  rmds_to_remove <- all_rmds[!grepl(
    paste0("^index[.]Rmd$|^", basename(fiche), "$"), basename(all_rmds))]
  file.remove(rmds_to_remove)
  
  withr::with_dir(compil_dir, {
    bookdown::render_book(
      "index.Rmd",
      output_format = "lozen::paged_template"
    )
  })
  
  outfile <- file.path(outdir, gsub("[.](R|r)md", ".html", basename(fiche)))
  file.copy(file.path(compil_dir, "_main.html"), outfile)
  message(basename(outfile), " file created")
  
  # transform as odt
  if ("odt" %in% type) {
    # file path
    outodt <- file.path(outdir, gsub("[.](R|r)md", ".odt", basename(fiche)))
    html_to_odt(input_html = file.path(compil_dir, "_main.html"),
                output_odt = outodt)
    
  } else {
    outodt <- NULL
  }
  
  # clean compil_dir
  unlink(compil_dir, recursive = TRUE)
  
  if (isTRUE(open)) {
    utils::browseURL(outfile)
  }
  
  return(c(outfile, outodt))
    
}
```


```{r tests-compile_fiche}
test_that("compile_fiche works", {
  expect_true(inherits(compile_fiche, "function")) 
})
```
  
# compile_fiches

```{r function-compile_fiches}
#' Compile all fiches Rmd
#' @param fiches Path to fiches Rmd
#' @param outdir Directory where to save the output HTML
#' @param type Choose output type: html or odt
#' @param open Logical. Whether to open file at the end
#' @return compiled fiches
#' @noRd 
#' 
compile_fiches <- function(fiches, type = "html", outdir = "public", open = TRUE) {
  type <- match.arg(type, choices = c("html", "odt"), several.ok = TRUE)
  out <- lapply(fiches, compile_fiche, type = type, outdir = outdir, open = open)
  return(unlist(out))
}
```
  
```{r example-compile_fiches}
compile_fiches()
```
  
```{r tests-compile_fiches}
test_that("compile_fiches works", {
  expect_true(inherits(compile_fiches, "function")) 
})
```
 

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_book_utils.Rmd",
  vignette_name = NA,
  check = FALSE
)
```
