# WARNING - Generated by {fusen} from dev/flat_build_pkgdown_with_reports.Rmd: do not edit by hand

test_that("build_pkgdown_with_reports works", {
  # create tmp folder
  tmppkg <- tempfile(pattern = "pkg-")
  dir.create(tmppkg)
  # Copy fake package from attachment in "inst/" for {lozen}
  # file.copy(
  #   system.file("dummypackage", package = "attachment"),
  #   "inst/dummypackage",
  #   recursive = TRUE
  # )
  file.copy(
    system.file("dummypackage", package = "lozen"),
    tmppkg,
    recursive = TRUE
  )
  path <- file.path(tmppkg, "dummypackage")

  # Add _pkgdown.yml file for tests
  if (requireNamespace("thinkrtemplate", quietly = TRUE)) {
    cat("template:\n  package: thinkrtemplate\n", file = file.path(path, "_pkgdown.yml"))
    cat("^_pkgdown\\.yml$\n", file = file.path(path, "Rbuildignore"))
  }

  if (requireNamespace("testdown", quietly = TRUE)) {
    # Test testdown ----
    build_pkgdown_with_reports(
      pkg = path,
      pkgdown_path = file.path(path, "public"),
      assets_path = file.path(path, "pkgdown/assets"),
      reports = c("testdown")
    )

    # Browse interactively
    # browseURL(file.path(path, "public", "index.html"))

    # Test file are correctly created in pkgdown and public folders
    # ignore libs
    expect_setequal(
      object = list.files(file.path(path, "pkgdown", "assets", "testdown")),
      expected = c(
        "_bookdown.yml", "_output.yml", "404.html", "aggregated-failures-and-errors.html",
        "aggregated-skipped.html", "aggregated-warnings.html", "global-results-for-package-dummypackage.html",
        "how-to-read-this-report.html", "index.html", "libs", "style.css",
        "test-addition.html", "testdown-report-for-dummypackage.html"
      )
    )
    expect_true(
      all(
        c(
          "404.html", "articles", "authors.html",
          # "deps",
          "index.html",
          # "LICENSE-text.html", "LICENSE.html", # if package with license
          "link.svg", "pkgdown.js",
          "pkgdown.yml", "reference",
          # "search.json", # Bootstrap > 5.0
          "sitemap.xml", "testdown"
        ) %in%
          list.files(file.path(path, "public"))
      )
    )

    # Test navbar is correctly set with testdown url
    expect_true(
      any(grepl("<a href=\"testdown/index.html\">testdown</a>", readLines(file.path(path, "public", "index.html"))))
    )
  }

  if (requireNamespace("covr", quietly = TRUE)) {
    # Test coverage ----
    # Note : potential check issues :
    # https://github.com/r-lib/covr/tree/84836b3f2267d861b4110570e221dd7a418a9787#why-cant-covr-run-during-r-cmd-check
    build_pkgdown_with_reports(
      pkg = path,
      pkgdown_path = file.path(path, "public"),
      assets_path = file.path(path, "pkgdown/assets"),
      reports = "coverage"
    )

    # Browse interactively
    # browseURL(file.path(path, "public", "index.html"))

    expect_true(
      all(c(
        "codecoverage_explanation.html",
        "coverage.html"
      ) %in%
        list.files(file.path(path, "pkgdown", "assets", "coverage")))
    )

    # Navbar
    expect_true(
      any(grepl(
        "<a href=\"coverage/coverage.html\">coverage</a>",
        readLines(file.path(path, "public", "index.html"))
      ))
    )
    expect_true(
      any(grepl(
        "<a href=\"coverage/codecoverage_explanation.html\">coverage explained</a>",
        readLines(file.path(path, "public", "index.html"))
      ))
    )
  }

  # # The repo is not a git repository (yet?)
  # build_pkgdown_with_reports(
  #   pkg = path,
  #   pkgdown_path = file.path(path, "public"),
  #   assets_path = file.path(path, "pkgdown/assets"),
  #   reports = "gitdown"
  # )

  # Clean
  unlink(path, recursive = TRUE)
})
