# WARNING - Generated by {fusen} from dev/flat_deploy_connect.Rmd: do not edit by hand

test_that("deploy_connect_shiny works", {
  if (Sys.getenv("ALLOW_TESTS_TO_DEPLOY_ON_CONNECT", unset = "FALSE") == "TRUE") {
  expect_true(inherits(deploy_connect_shiny, "function"))
  }
})
