# WARNING - Generated by {fusen} from /dev/flat_init_gitlab_ci.Rmd: do not edit by hand

test_that("combine_ci works", {
  # pkgdown yml
  full <- yaml::read_yaml(file = system.file("yaml", ".gitlab-ci-pkg.yml", package = "lozen"))

  # shiny yaml
  connect <- yaml::read_yaml(file = system.file("yaml", ".gitlab-ci-shiny.yml", package = "lozen"))

  ci_list <- combine_ci(ci1 = full, ci2 = connect)

  expect_equal(
    object = ci_list,
    expected = list(
      image = c("rocker/verse", "rocker/verse:latest"), variables = list(
        GIT_DEPTH = 10L, REPO_NAME = "https://packagemanager.rstudio.com/all/__linux__/focal/latest",
        R_LIBS_USER = "ci/lib"
      ), cache = list(
        key = "global-cache",
        paths = "${R_LIBS_USER}"
      ), stages = c(
        "build", "test", "pkgdown",
        "pkgdown-move", "deploy", "deploy_connect"
      ), building = list(
        stage = "build", script = c(
          "lsb_release -c", "R -e \"sessionInfo()\"",
          "if [[ $CI_DEFAULT_BRANCH == \"master\" || $CI_DEFAULT_BRANCH = \"main\" ]]; then echo \"OK - Default branch is master or main\"; else echo \"Default branch is not master or main; please add yours ($CI_DEFAULT_BRANCH) where needed, as well as in the present line of code\" ; exit 1; fi",
          "apt-get update -qq && apt-get install -y libharfbuzz-dev libfribidi-dev",
          "echo \"Library path for packages :\" $R_LIBS_USER", "mkdir -p $R_LIBS_USER",
          "Rscript -e 'install.packages(\"remotes\")'", "Rscript -e 'install.packages(\"rcmdcheck\")'",
          "Rscript -e 'remotes::install_local(upgrade = \"never\")'",
          "R -e 'rcmdcheck::rcmdcheck(args = c(\"--no-manual\"), error_on = \"warning\", check_dir = \"check\")'"
        ), artifacts = list(paths = "check", expire_in = "30 days")
      ),
      coverage = list(
        stage = "test", allow_failure = TRUE, when = "on_success",
        only = c("main", "master", "production"), script = c(
          "Rscript -e 'remotes::install_local(upgrade = \"never\")'",
          "Rscript -e 'remotes::install_cran(c(\"covr\", \"DT\"), upgrade = \"never\")'",
          "Rscript -e 'covr::gitlab(quiet = FALSE)'"
        ), coverage = "/Coverage: \\d+\\.\\d+/",
        artifacts = list(paths = "public", expire_in = "30 days")
      ),
      integration = list(
        stage = "pkgdown", allow_failure = TRUE,
        when = "on_success", only = c(
          "main", "master", "production",
          "test-ci"
        ), script = c(
          "Rscript -e 'install.packages(\"thinkrtemplate\", repos = c(\"thinkropen\" = \"https://thinkr-open.r-universe.dev\"))'",
          "Rscript -e 'remotes::install_cran(c(\"pkgdown\"), upgrade = \"never\")'",
          "Rscript -e 'remotes::install_local(upgrade = \"never\")'",
          "Rscript -e 'pkgdown::build_site()'"
        ), artifacts = list(
          paths = "docs", expire_in = "30 days"
        )
      ), `integration-test` = list(
        stage = "pkgdown-move", dependencies = "integration",
        only = "test-ci", script = c(
          "mkdir -p public/test",
          "curl --location --output artifacts.zip --header \"JOB-TOKEN: $CI_JOB_TOKEN\" \"$CI_API_V4_URL/projects/$CI_PROJECT_ID/jobs/artifacts/$CI_DEFAULT_BRANCH/download?job=pages\" && unzip artifacts.zip && rm artifacts.zip && echo \"copied $CI_DEFAULT_BRANCH artifacts\" || echo \"copied $CI_DEFAULT_BRANCH artifacts failed\"",
          "curl --location --output artifacts.zip --header \"JOB-TOKEN: $CI_JOB_TOKEN\" \"$CI_API_V4_URL/projects/$CI_PROJECT_ID/jobs/artifacts/production/download?job=pages\" && unzip artifacts.zip && rm artifacts.zip && echo \"copied production artifacts\" || echo \"copied production artifacts failed\"",
          "cp -r docs/* public/test"
        ), artifacts = list(
          paths = "public",
          expire_in = "30 days"
        )
      ), `integration-production` = list(
        stage = "pkgdown-move", dependencies = "integration",
        only = "production", script = c(
          "mkdir -p public/production",
          "curl --location --output artifacts.zip --header \"JOB-TOKEN: $CI_JOB_TOKEN\" \"$CI_API_V4_URL/projects/$CI_PROJECT_ID/jobs/artifacts/$CI_DEFAULT_BRANCH/download?job=pages\" && unzip artifacts.zip && rm artifacts.zip && echo \"copied $CI_DEFAULT_BRANCH artifacts\" || echo \"copied $CI_DEFAULT_BRANCH artifacts failed\"",
          "cp -r docs/* public/production"
        ), artifacts = list(
          paths = "public",
          expire_in = "30 days"
        )
      ), `integration-main` = list(
        stage = "pkgdown-move", dependencies = "integration",
        only = c("main", "master"), script = c(
          "mkdir -p public",
          "curl --location --output artifacts.zip --header \"JOB-TOKEN: $CI_JOB_TOKEN\" \"$CI_API_V4_URL/projects/$CI_PROJECT_ID/jobs/artifacts/production/download?job=pages\" && unzip artifacts.zip && rm artifacts.zip && echo \"copied production artifacts\" || echo \"copied production artifacts failed\"",
          "cp -r docs/* public"
        ), artifacts = list(
          paths = "public",
          expire_in = "30 days"
        )
      ), pages = list(
        stage = "deploy",
        script = "echo \"deployment with cache\"", artifacts = list(
          paths = "public"
        ), only = c(
          "main", "master", "production",
          "test-ci"
        )
      ), deploying = list(
        stage = "deploy_connect",
        script = c(
          "echo \"Library path for packages :\" R_LIBS_USER",
          "mkdir -p R_LIBS_USER", "Rscript -e 'install.packages(c(\"git2r\"));install.packages(\"gitlabr\", repos = c(\"https://thinkr-open.r-universe.dev\", \"https://cloud.r-project.org\"))'",
          "Rscript -e 'options(remotes.git_credentials = git2r::cred_user_pass(\"gitlab-ci-token\", Sys.getenv(\"CI_JOB_TOKEN\")));remotes::install_git(\"https://forge.thinkr.fr/thinkr/thinkrverse/lozen\", build_vignettes = FALSE, ref = Sys.getenv(\"LOZEN_BRANCH\", unset = \"main\"))'",
          "Rscript -e 'lozen::deploy_connect_shiny(connect_url = Sys.getenv(\"CONNECT_URL\"),connect_user = Sys.getenv(\"CONNECT_USER\"),connect_api_token = Sys.getenv(\"CONNECT_TOKEN\"),app_name = Sys.getenv(\"APP_NAME\", unset = Sys.getenv(\"CI_PROJECT_NAME\")))'"
        )
      )
    )
  )
})
