# WARNING - Generated by {fusen} from dev/flat_move_issues_from_gitlab_to_github.Rmd: do not edit by hand

## 04-05-2023 On skip pour des raisons d'auth sur le CI
skip_on_ci()

test_that("move_issues_from_gitlab_to_github works", {
  on.exit({
    # admin access (delete_repo scope)
    gh::gh(paste0("DELETE /repos/", owner, "/", repo_name))
    # delete gitlab repo

    gitlabr::gitlab(
      req = paste0("projects/", project_id),
      verb = httr::DELETE
    )
  })


  gitlab_url <-
    Sys.getenv("GITLAB_URL", unset = "https://gitlab.com")

  gitlab_token <- Sys.getenv("GITLAB_TOKEN")

  # GitLab con
  my_gitlab <- gl_connection(
    gitlab_url = gitlab_url,
    private_token = gitlab_token
  )

  # Set the connection for the session
  set_gitlab_connection(my_gitlab)

  # Get user infos
  user_info <- gitlab(req = paste0("user"), verb = httr::GET)
  user_name <- user_info %>% pull(username)

  project_name <- "lozentransferGLGH"

  # Get user namespace (= group_id)
  # namespace_id <- gitlabr::gitlab(req = "namespaces", search = user_name)[["id"]]
  group_url <- user_info[["web_url"]]


  # create_group_project ----
  project_id <-
    create_group_project(project_name, namespace_id = NULL)

  ### List of issues
  issues_need <- list(
    test1 = list(created_at = Sys.Date()),
    test2 = list(created_at = Sys.Date()),
    test3 = list(created_at = Sys.Date()),
    test4 = list(created_at = Sys.Date()),
    test5 = list(created_at = Sys.Date())
  )

  url <- paste0("/projects/", project_id, "/", "issues")

  # Open issues
  purrr::iwalk(issues_need, ~ {
    gitlab(
      url,
      title = .y,
      verb = httr::POST,
      created_at = as.character(.x[["created_at"]])
    )
  })


  gl_list_issues <- gl_list_issues(
    project = project_id,
    max_page = 10
  )


  # let's open the github repo
  github_token <- Sys.getenv("GITHUB_PAT")
  github_url <- "https://github.com/"

  user <- gh::gh("GET /user")
  owner <- user$login
  repo_name <- "my-new-repo-for-gh-testing"

  gh::gh("POST /user/repos", name = repo_name)


  # let's copy the issues from GL to GH
  moving_issues <- try(move_issues_from_gitlab_to_github(
    gitlab_url = gitlab_url,
    github_url = github_url,
    gitlab_group = user_name,
    gitlab_repo = project_name,
    gitlab_project_id = project_id,
    github_owner = owner,
    github_repo = repo_name,
    gitlab_private_token = gitlab_token,
    github_token = github_token,
    sleep_time = 30,
    issue_start_over = 1,
    max_page = 10,
    force = FALSE
  ))

  # listing the issues present on the gitlab repo
  gh_list_issues <-
    gh(
      "/repos/{github_owner}/{github_repo}/issues",
      state = "all",
      github_owner = owner,
      github_repo = repo_name
    ) %>%
    multilist_to_tibble()

  gl_list_cleaned <- gl_list_issues %>%
    dplyr::select(title, state) %>%
    dplyr::arrange(title) %>%
    dplyr::mutate(title = as.character(title))

  gh_list_cleaned <- gh_list_issues %>%
    dplyr::select(title, state, node_id) %>%
    dplyr::arrange(title) %>%
    dplyr::mutate(state = ifelse(state == "open", "opened", state)) %>%
    dplyr::mutate(title = as.character(title))

  expect_true(all.equal(
    as.character(gl_list_cleaned$title),
    as.character(gh_list_cleaned$title)
  ))
  expect_true(all.equal(
    as.character(gl_list_cleaned$state),
    as.character(gh_list_cleaned$state)
  ))



  # Clean GitLab => Remove the project
  # GitLab con
  my_gitlab <- gl_connection(
    gitlab_url = gitlab_url,
    private_token = gitlab_token
  )

  # Set the connection for the session
  set_gitlab_connection(my_gitlab)
})
