# WARNING - Generated by {fusen} from dev/flat_helper_testthat.Rmd: do not edit by hand

test_that("with_gitlab_project works", {
  # TODO - Remove ; allow test to pass on CI
  skip_on_ci()

  if (Sys.getenv("ALLOW_CI_TESTS_ON_GITLAB", unset = "FALSE") == "TRUE") {
    output <- with_gitlab_project(
      gitlab_url = Sys.getenv("GITLAB_URL", unset = "https://gitlab.com"),
      namespace_id = NULL,
      private_token = Sys.getenv("GITLAB_TOKEN"),
      project_name = "bookdown.test.project",
      exp = {
        lozen::create_r_project(
          project_path = getwd(),
          type = "book",
          name_licence = "Bobo",
          type_licence = usethis::use_mit_license
        )
        lozen::use_gitlab_ci(type = "bookdown", bookdown_output_format = "lozen::paged_template")
      }
    )

    if (is.null(output)) {
      message("No CI jobs were launched. A user validation might be required on your Gitlab account. To use free CI/CD minutes on shared runners, you\u2019ll need to validate your account with a credit card. If you prefer not to provide one, you can run pipelines by bringing your own runners and disabling shared runners for your project.")
    } else {
      expect_equal(
        output$status,
        "success"
      )
    }
  }
})
