# WARNING - Generated by {fusen} from dev/flat_init_gitlab_ci.Rmd: do not edit by hand

test_that("create_deploy_ci_stage works", {
  expect_true(inherits(create_deploy_ci_stage, "function"))
  expect_true(is.list(create_deploy_ci_stage(
    image = "rocker/verse",
    deploy_function = "deploy_connect_shiny"
  )))
})
