# WARNING - Generated by {fusen} from /dev/flat_book_utils.Rmd: do not edit by hand

test_that("paged_template works", {
  skip_on_ci()
  
  withr::with_tempdir({
    
    lozen::create_r_project(
      project_path = getwd(),
      type = "book",
      type_licence = usethis::use_mit_license,
      name_licence = "Bibi"
    )

    bookdown::render_book("index.Rmd", output_format = "lozen::paged_template")

    expect_true(
      file.exists(file.path(getwd(), "_main.html"))
    )
  })
})
