# WARNING - Generated by {fusen} from dev/flat_create_special_issues.Rmd: do not edit by hand

# project_path <- tempfile("myproject")
# dir.create(project_path)

withr::with_tempdir({
  test_that("gh_add_template_issue works", {
    project_path <- getwd()

    # create temp dir and file
    # check full french template works
    expect_message(
      gh_add_template_issue(project_path, language = "fr", type = "full"),
      "Issue template added"
    )

    expect_true(object = file.exists(
      file.path(
        project_path,
        ".github",
        "ISSUE_TEMPLATE",
        "Template issue.md"
      )
    ))

    # check full english template works
    expect_message(
      gh_add_template_issue(project_path, language = "en"),
      "Issue template added"
    )

    expect_true(object = file.exists(
      file.path(
        project_path,
        ".github",
        "ISSUE_TEMPLATE",
        "Template issue.md"
      )
    ))

    # check light french template works
    expect_message(
      gh_add_template_issue(project_path, language = "fr", type = "light"),
      "Issue template added"
    )

    expect_true(object = file.exists(
      file.path(
        project_path,
        ".github",
        "ISSUE_TEMPLATE",
        "Light template issue.md"
      )
    ))

    # check full english template works
    expect_message(
      gh_add_template_issue(project_path, language = "en", type = "light"),
      "Issue template added"
    )

    expect_true(object = file.exists(
      file.path(
        project_path,
        ".github",
        "ISSUE_TEMPLATE",
        "Light template issue.md"
      )
    ))

    # unlink(project_path, recursive = TRUE)
  })
})
