# WARNING - Generated by {fusen} from dev/flat_manage_git.Rmd: do not edit by hand

test_that("push_main works", {
  expect_true(inherits(push_all_to_branch, "function"))
  expect_true(inherits(push_main, "function"))
  expect_true(inherits(push_master, "function"))
})
