# WARNING - Generated by {fusen} from /dev/flat_init_gitlab_ci.Rmd: do not edit by hand

test_that("clean_image works", {
  # pkgdown yml
  full <- yaml::read_yaml(file = system.file("yaml", ".gitlab-ci-pkg.yml", package = "lozen"))

  # shiny yaml
  connect <- yaml::read_yaml(file = system.file("yaml", ".gitlab-ci-shiny.yml", package = "lozen"))

  ci_list_order1 <- clean_image(
    combine_ci(
      ci1 = full,
      ci2 = connect
    )
  )

  expect_equal(
    object = ci_list_order1["image"],
    expected = list(image = "rocker/verse")
  )

  ci_list_order2 <- clean_image(
    combine_ci(
      ci1 = connect,
      ci2 = full
    )
  )

  expect_equal(
    object = ci_list_order2["image"],
    expected = list(image = "rocker/verse:latest")
  )
})
