# WARNING - Generated by {fusen} from /dev/flat_create_weekly.Rmd: do not edit by hand

user <- "ThinkR-open"
repo <- "example-weekly"
date_min <- "2022-06-30"
date_max <- "2022-06-30"
board_url_old <- glue::glue("/repos/{user}/{repo}/projects")
board_url_new <- "https://github.com/orgs/ThinkR-open/projects/4/"

test_that("gh_create_weekly_old_and_new_boards works with old boards", {
  if (Sys.getenv("GITHUB_PAT") != "") {
    weekly_old <- gh_create_weekly_old_and_new_boards(
      date_min = date_min,
      date_max = date_max,
      user = user,
      repo = repo,
      board_url = board_url_old,
      new_board = FALSE,
      verbose = FALSE
    )


    info <- weekly_old$weekly_info

    expect_length(info, 1)
    expect_true(grepl(":spiral_notepad: In progress", info))
    expect_true(grepl(":stop_sign: Blocked", info))
    expect_true(grepl(":seedling: New issues opened", info))
    expect_true(grepl(":thumbsup: Ready", info))
    expect_true(grepl(":thumbsup: Realised and to validate", info))
    expect_true(grepl(":white_check_mark: Realised and validated", info))

    expect_equal(
      weekly_old$weekly_issues$info,
      c(
        rep("__2__:stop_sign: Blocked", 3),
        rep("__4__:spiral_notepad: In progress", 2),
        "__3__:thumbsup: Realised and to validate",
        "__5__:thumbsup: Ready",
        rep("__1__:white_check_mark: Realised and validated", 2),
        rep("__9__:seedling: New issues opened", 7)
      )
    )

    expect_equal(
      as.character(weekly_old$weekly_issues$issue_li[1]),
      "- Issue blocked: [issue 6](https://github.com/ThinkR-open/example-weekly/issues/6) - Not assigned"
    )
  }
})

test_that("gh_create_weekly_old_and_new_boards works with new boards", {
  skip_on_ci()
  if (Sys.getenv("GITHUB_PAT") != "") {
    weekly_new <- gh_create_weekly_old_and_new_boards(
      date_min = date_min,
      date_max = date_max,
      user = user,
      repo = repo,
      board_url = board_url_new,
      github_token = Sys.getenv("GITHUB_PAT"),
      new_board = TRUE,
      verbose = FALSE
    )

    info <- weekly_new$weekly_info

    expect_length(info, 1)
    expect_true(grepl(":spiral_notepad: In progress", info))
    expect_true(grepl(":stop_sign: Blocked", info))
    expect_true(grepl(":seedling: New issues opened", info))
    expect_true(grepl(":thumbsup: Ready", info))
    expect_true(grepl(":thumbsup: Realised and to validate", info))
    expect_true(grepl(":white_check_mark: Realised and validated", info))

    expect_equal(
      weekly_new$weekly_issues$info,
      c(
        rep("__2__:stop_sign: Blocked", 3),
        rep("__4__:spiral_notepad: In progress", 2),
        "__3__:thumbsup: Realised and to validate",
        "__5__:thumbsup: Ready",
        rep("__1__:white_check_mark: Realised and validated", 2),
        rep("__9__:seedling: New issues opened", 7)
      )
    )

    expect_equal(
      as.character(weekly_new$weekly_issues$issue_li[1]),
      "- [dev] Checklist mise en place: [issue 11](https://github.com/ThinkR-open/example-weekly/issues/11) - Not assigned"
    )
  }
})


test_that("gh_create_weekly_old_and_new_boards works checks the board url format correctly", {
  if (Sys.getenv("GITHUB_PAT") != "") {
    ############################
    ## WORKING WITH NEW BOARD ##
    ############################

    # new board with incorrect url (no http)
    board_url_new_without_http <- "orgs/ThinkR-open/projects/4/"

    expect_error(
      object = gh_create_weekly_old_and_new_boards(
        date_min = date_min,
        date_max = date_max,
        user = user,
        repo = repo,
        board_url = board_url_new_without_http,
        github_token = Sys.getenv("GITHUB_PAT"),
        new_board = TRUE,
        verbose = FALSE
      )
    )

    # user uses new_board = TRUE but the url seems to indicate this is an old board
    board_url_which_seems_to_be_an_old_board <- "https://github.com/ThinkR-open/example-weekly/projects/1"

    expect_error(
      object = gh_create_weekly_old_and_new_boards(
        date_min = date_min,
        date_max = date_max,
        user = user,
        repo = repo,
        board_url = board_url_which_seems_to_be_an_old_board,
        github_token = Sys.getenv("GITHUB_PAT"),
        new_board = TRUE,
        verbose = FALSE
      )
    )

    ############################
    ## WORKING WITH OLD BOARD ##
    ############################

    # if board_url is missing the user should be warned the url is guessed from the parameters user and repo
    expect_message(
      object = gh_create_weekly_old_and_new_boards(
        date_min = date_min,
        date_max = date_max,
        user = user,
        repo = repo,
        github_token = Sys.getenv("GITHUB_PAT"),
        new_board = FALSE,
        verbose = FALSE
      ),
      regexp = paste(
        "`board_url` is guessed from `user` and `repo` as you specified `new_board = FALSE`:",
        glue::glue("/repos/{user}/{repo}/projects")
      )
    )


    # if 'repos' if missing from board_url there is an error
    expect_error(
      object = gh_create_weekly_old_and_new_boards(
        date_min = date_min,
        date_max = date_max,
        user = user,
        repo = repo,
        board_url = glue::glue("/{user}/{repo}/projects"),
        github_token = Sys.getenv("GITHUB_PAT"),
        new_board = FALSE,
        verbose = FALSE
      )
    )
  }
})



test_that("gh_create_weekly_old_and_new_boards works also with a 'user' and not necessarily an 'organization'", {
  if (Sys.getenv("GITHUB_PAT_THE_THINKR") != "") {
    weekly_new <- gh_create_weekly_old_and_new_boards(
      date_min = "2023-01-01",
      date_max = "2023-03-01",
      user = "the-thinkr",
      repo = "toy_project_board",
      board_url = "https://github.com/users/the-thinkr/projects/1",
      github_token = Sys.getenv("GITHUB_PAT_THE_THINKR"),
      new_board = TRUE,
      verbose = FALSE
    )

    info <- weekly_new$weekly_info

    expect_length(info, 1)
    expect_true(grepl(":spiral_notepad: In progress", info))
    expect_true(grepl(":seedling: New issues opened", info))


    expect_equal(
      weekly_new$weekly_issues$info,
      c(
        rep("__4__:spiral_notepad: In progress", 1),
        rep("__9__:seedling: New issues opened", 3)
      )
    )

    expect_equal(
      as.character(weekly_new$weekly_issues$issue_li[1]),
      "- Une issue dans InProgress: [issue 2](https://github.com/the-thinkr/toy_project_board/issues/2) - Not assigned"
    )
  }
})
