# WARNING - Generated by {fusen} from dev/flat_helper_testthat.Rmd: do not edit by hand

test_that("fetch_connect works", {
  skip_if_not(isTRUE(Sys.getenv("CONNECT_TOKEN") != ""))
  skip_if_not(isTRUE(Sys.getenv("CONNECT_URL") != ""))

  expect_message(
    object = fetch_connect(app_name = "this-app-does-not-exist"),
    regexp = "The app this-app-does-not-exist is not found on Connect server"
  )



  lozen_infos <- fetch_connect(
    app_name = "lozen-pkgdown-website"
  )

  expect_equal(
    object = lozen_infos[["status"]],
    expected = 200
  )

  expect_equal(
    object = lozen_infos[["guid"]],
    expected = "5e89ed9a-f63b-4b5c-8268-d898579419ef"
  )
})
