# WARNING - Generated by {fusen} from dev/flat_helper_testthat.Rmd: do not edit by hand

test_that("with_gitlab_project works", {
  # TODO - Remove ; allow test to pass on CI
  skip_on_ci()

  if (Sys.getenv("ALLOW_CI_TESTS_ON_GITLAB", unset = "FALSE") == "TRUE") {
    
    output <- with_gitlab_project(
      gitlab_url = Sys.getenv("GITLAB_URL", unset = "https://gitlab.com"),
      namespace_id = NULL,
      project_name = "lozen.test.project",
      exp = {
        bookdown::create_bs4_book(path = ".")
        bookdown::render_book()
        lozen::use_gitlab_ci(
          type = "bookdown"
        )
      }
    )
    
    if(is.null(output)) {
      message("No CI jobs were launched. A user validation might be required on your Gitlab account. To use free CI/CD minutes on shared runners, you\u2019ll need to validate your account with a credit card. If you prefer not to provide one, you can run pipelines by bringing your own runners and disabling shared runners for your project.")
    } else {
    expect_equal(
      output$status,
      "success"
    )
    }
  }
})
