# WARNING - Generated by {fusen} from dev/flat_init_gitlab_ci.Rmd: do not edit by hand

test_that("init_gitlab_ci throws expected messages", {
  withr::with_tempdir({
    expect_message(
      lozen::use_gitlab_ci(
        type = "check-coverage-pkgdown"
      ),
      "There is no ./.gitlab-ci.yml in your project, a new one will be created."
    )

    expect_message(
      lozen::use_gitlab_ci(
        type = "check-coverage-pkgdown",
        overwrite = TRUE
      ),
      "Overwriting ./.gitlab-ci.yml."
    )
  })
})


test_that("init_gitlab_ci works for bookdown and  bookdown_output_format = lozen::paged_template", {
  # TODO - Remove ; allow test to pass on CI
  skip_on_ci()

  # Test on Gitlab : Create a bookdown and test the CI
  if (Sys.getenv("ALLOW_CI_TESTS_ON_GITLAB", unset = "FALSE") == "TRUE") {
    # Pour un template CI "bookdown"
    output_bookdown <- with_gitlab_project(
      gitlab_url = Sys.getenv("GITLAB_URL", unset = "https://gitlab.com"),
      namespace_id = NULL,
      private_token = Sys.getenv("GITLAB_TOKEN"),
      project_name = "bookdown.test.project",
      exp = {
        lozen::create_r_project(
          project_path = getwd(),
          type = "book", name_licence = "Bobo", type_licence = usethis::use_mit_license
        )
        lozen::use_gitlab_ci(type = "bookdown", bookdown_output_format = "lozen::paged_template")
      }
    )

    expect_equal(
      object = output_bookdown$status,
      expected = "success"
    )
  }
})

test_that("init_gitlab_ci works for bookdown and  bookdown_output_format = lozen::bs4_book_template", {
  # TODO - Remove ; allow test to pass on CI
  skip_on_ci()

  # Test on Gitlab : Create a bookdown and test the CI
  if (Sys.getenv("ALLOW_CI_TESTS_ON_GITLAB", unset = "FALSE") == "TRUE") {
    # Pour un template CI "bookdown"
    output_bookdown <- with_gitlab_project(
      gitlab_url = Sys.getenv("GITLAB_URL", unset = "https://gitlab.com"),
      namespace_id = NULL,
      private_token = Sys.getenv("GITLAB_TOKEN"),
      project_name = "bookdown.test.project",
      exp = {
        lozen::create_r_project(
          project_path = getwd(),
          type = "book", name_licence = "Bobo", type_licence = usethis::use_mit_license
        )
        lozen::use_gitlab_ci(type = "bookdown", bookdown_output_format = "lozen::bs4_book_template")
      }
    )

    expect_equal(
      object = output_bookdown$status,
      expected = "success"
    )
  }
})


test_that("init_gitlab_ci works for shiny", {
  # TODO - Remove ; allow test to pass on CI
  skip_on_ci()

  # Test on Gitlab : Create a Golem and test the CI
  if (Sys.getenv("ALLOW_CI_TESTS_ON_GITLAB", unset = "FALSE") == "TRUE") {
    # Pour un template CI "check-coverage-pkgdown"
    output_golem <- lozen::with_gitlab_project(
      gitlab_url = Sys.getenv("GITLAB_URL", unset = "https://gitlab.com"),
      namespace_id = NULL,
      private_token = Sys.getenv("GITLAB_TOKEN"),
      project_name = "golem.test.project",
      exp = {
        lozen::create_r_project(project_path = getwd(), type = "golem", name_licence = "test", type_licence = usethis::use_mit_license)
        lozen::use_gitlab_ci(type = "check-coverage-pkgdown")
      }
    )

    expect_equal(
      object = output_golem$status,
      expected = "success"
    )
  }
})

test_that("init_gitlab_ci works for a R package", {
  # TODO - Remove ; allow test to pass on CI
  skip_on_ci()

  # Test on Gitlab : Create a Package and test the CI
  if (Sys.getenv("ALLOW_CI_TESTS_ON_GITLAB", unset = "FALSE") == "TRUE") {
    # Pour un template CI "check-coverage-pkgdown"
    output_package <- lozen:::with_gitlab_project(
      gitlab_url = Sys.getenv("GITLAB_URL", unset = "https://gitlab.com"),
      namespace_id = NULL,
      private_token = Sys.getenv("GITLAB_TOKEN"),
      project_name = "package.test.project",
      exp = {
        lozen::create_r_project(project_path = getwd(), type = "package", name_licence = "test", type_licence = usethis::use_mit_license)
        # Add dummy function
        dir.create(file.path(getwd(), "R/"))
        file.create(file.path(getwd(), "R/fun.R"))
        writeLines(con = file.path(getwd(), "R/fun.R"), "somme <- function(a,b) a+b")
        lozen::use_gitlab_ci(type = "check-coverage-pkgdown")
      }
    )

    expect_equal(
      object = output_package$status,
      expected = "success"
    )
  }
})


test_that("init_gitlab_ci works for a quarto or Rmd file", {
  # TODO
})
