# WARNING - Generated by {fusen} from dev/flat_init_gitlab_ci.Rmd: do not edit by hand

test_that("check_if_yaml_exists throws expected messages", {
withr::with_tempdir({
  lozen::use_gitlab_ci(    
    type = "check-coverage-pkgdown"
  )

  expect_message(
    check_if_yaml_exists(),
  "Appending new stages in ./.gitlab-ci.yml"
  )

  unlink(file.path(getwd(), ".gitlab-ci.yml"))

  expect_message(
    check_if_yaml_exists(),
  "There is no ./.gitlab-ci.yml in your project, a new one will be created."
  )

})

})
