# WARNING - Generated by {fusen} from dev/flat_create_special_issues.Rmd: do not edit by hand

withr::with_tempdir({
  test_that("gl_add_template_issue works", {
    project_path <- getwd()

    # check full french template works
    expect_message(
      gl_add_template_issue(project_path, language = "fr", type = "full"),
      "Issue template added"
    )

    expect_true(object = file.exists(
      file.path(
        project_path,
        ".gitlab",
        "issue_templates",
        "Template issue.md"
      )
    ))

    # check full english template works
    expect_message(
      gl_add_template_issue(project_path, language = "en", type = "full"),
      "Issue template added"
    )

    expect_true(object = file.exists(
      file.path(
        project_path,
        ".gitlab",
        "issue_templates",
        "Template issue.md"
      )
    ))

    # check light french template works
    expect_message(
      gl_add_template_issue(project_path, language = "fr", type = "light"),
      "Issue template added"
    )

    expect_true(object = file.exists(
      file.path(
        project_path,
        ".gitlab",
        "issue_templates",
        "Light template issue.md"
      )
    ))

    # check light english template works
    expect_message(
      gl_add_template_issue(project_path, language = "en", type = "light"),
      "Issue template added"
    )

    expect_true(object = file.exists(
      file.path(
        project_path,
        ".gitlab",
        "issue_templates",
        "Light template issue.md"
      )
    ))


    # Suppress tmp folder
    # unlink(project_path, recursive = TRUE)
  })
})
