# WARNING - Generated by {fusen} from /dev/flat_create_weekly.Rmd: do not edit by hand

test_that("gh_create_weekly_new_projects_board works", {
  expect_true(inherits(gh_create_weekly_new_projects_board, "function"))

  test_user <- "thinkr-open"
  test_repo <- "example-weekly"
  board_url <- "https://github.com/orgs/ThinkR-open/projects/4/"


  if (Sys.getenv("GITHUB_PAT") != "") {
    weekly <- gh_create_weekly_new_projects_board(
      date_min = "2022-06-30",
      date_max = "2022-06-30",
      user = test_user,
      repo = test_repo,
      board_url = board_url,
      github_token = Sys.getenv("GITHUB_PAT"),
      verbose = FALSE
    )

    info <- weekly$weekly_info
    expect_length(info, 1)
    expect_true(grepl("1 - :heavy_check_mark: Realised", info))
    expect_true(grepl("2 - :stop_sign: Blocked", info))
    expect_true(grepl("3 - :thumbsup: To validate", info))
    expect_true(grepl("4 - :spiral_notepad: In progress", info))
    expect_true(grepl("9 - :seedling: New issues opened", info))

    expect_equal(
      weekly$weekly_issues$info,
      c(
        rep("2 - :stop_sign: Blocked", 3),
        "4 - :spiral_notepad: In progress",
        "4 - :spiral_notepad: In progress",
        "3 - :thumbsup: To validate",
        "1 - :heavy_check_mark: Realised",
        "1 - :heavy_check_mark: Realised",
        rep("9 - :seedling: New issues opened", 7)
      )
    )

    expect_equal(
      as.character(weekly$weekly_issues$issue_li[1]),
      "- [dev] Checklist mise en place: [issue 11](https://github.com/ThinkR-open/example-weekly/issues/11) - Not assigned"
    )
  }
})
