# WARNING - Generated by {fusen} from /dev/flat_create_r_project_skeleton.Rmd: do not edit by hand

test_that("add_git_ignore works", {

})

project_path <- tempfile("my.project")
dir.create(project_path)
# usethis::create_project(project_path, open = FALSE)

# create_r_project ----
test_that("create_r_project works", {
  # project_path <- usethis::create_project(path = tempfile(), open = FALSE)
  expect_message(
    r_project <- create_r_project(project_path, type = c("package"), name_licence = "Test", type_licence = usethis::use_mit_license),
    "package created"
  )
  # expect_equal(r_project, project_path)
  expect_true(file.exists(file.path(r_project, "DESCRIPTION")))
  expect_true(file.exists(file.path(r_project, "NAMESPACE")))
  # expect_true(file.exists(file.path(r_project, "_pkgdown.yml")))
  expect_true(file.exists(file.path(r_project, ".gitattributes")))
  expect_true(file.exists(file.path(r_project, "dev", "dev_history_package.Rmd")))
  expect_true(file.exists(file.path(r_project, "dev", "dev_history_renv.Rmd")))
  expect_true(file.exists(file.path(r_project, "NEWS.md")))
  expect_true(file.exists(file.path(r_project, "LICENSE")))
})

# add_git_templates ----
test_that("add_git_templates works", {
  # project_path is not a git repository in this case
  expect_message(
    add_git_templates(project_path, type = c("commit")),
    "this is not a git repository"
  )
  expect_true(file.exists(file.path(project_path, ".gitlab", "template_commit")))
  expect_message(
    add_git_templates(project_path, type = c("mr")),
    "MR template added"
  )
  expect_true(file.exists(file.path(project_path, ".gitlab", "merge_request_templates", "template_mr.md")))

  # project_path is a git repository in this case
  gert::git_init(project_path)
  expect_message(
    add_git_templates(project_path, type = c("commit")),
    "Your local git configuration"
  )
})

# Clean local projects
unlink(project_path, recursive = TRUE)

# BOOK ====
project_path_book <- tempfile("book-")
dir.create(project_path_book)

# create_book_project ----
test_that("create_book_project works", {
  expect_message(
    r_project <- create_book_project(project_path_book),
    "book created"
  )
  expect_equal(r_project, project_path_book)
  # (!file.exists(file.path(project_path_book, "DESCRIPTION")))
  expect_true(file.exists(file.path(project_path_book, "DESCRIPTION")))

  expect_true(file.exists(file.path(r_project, "dev", "dev_history_book.Rmd")))
  expect_true(file.exists(file.path(r_project, "R", "functions_exemples.R")))
  expect_true(file.exists(file.path(r_project, "pandoc", "reference.odt")))
  # expect_true(file.exists(file.path(r_project, ".gitlab-ci.yml")))
  # expect_true(file.exists(file.path(r_project, ".gitattributes")))
  expect_true(file.exists(file.path(r_project, ".gitignore")))
  expect_true(all(
    file.exists(
      file.path(
        r_project,
        c(
          "01-page1.Rmd", "02-page2.Rmd", "03-page3.Rmd",
          "DESCRIPTION", "_bookdown.yml"
        )
      )
    )
  ))
})

# add_kit_project to book ----
add_kit_project(project_path = project_path_book, name_licence = "Test", type_licence = usethis::use_mit_license)
test_that("add_kit_project works", {
  expect_true(file.exists(file.path(project_path_book, ".gitattributes")))
  expect_true(file.exists(file.path(project_path_book, "NEWS.md")))
  expect_true(file.exists(file.path(project_path_book, "LICENSE")))
})

# Clean local projects
unlink(project_path_book, recursive = TRUE)
