# WARNING - Generated by {fusen} from dev/flat_create_r_project_skeleton.Rmd: do not edit by hand

#' Add necessary files for any R project
#'
#' @param project_path project_path
#' @param name_licence Name for the licence
#' @param type_licence should be a function, example : type_licence = usethis::use_proprietary_license
#'
#' @return Side Effect, add new files :
#'
#' - gitattributes
#' - NEWS.md
#'
#' @export
#'
#' @examples
#' withr::with_tempdir({
#'   project_path <- getwd()
#'   usethis::create_project(path = project_path, open = FALSE)
#'   add_kit_project(
#'     project_path,
#'     name_licence = "Bob",
#'     type_licence = usethis::use_proprietary_license
#'   )
#' })
add_kit_project <- function(project_path = ".", name_licence, type_licence) {
  if (!inherits(type_licence, "function")) {
    stop("type_licence should be a function, example : type_licence = usethis::use_proprietary_license")
  }
  # Add gitattributes
  gitattributes <- system.file("gitlab", "gitattributes", package = "lozen")
  file.copy(gitattributes, file.path(project_path, ".gitattributes"), overwrite = TRUE)

  # Change wd and proj for usethis
  # old <- setwd(project_path)
  # on.exit(setwd(old))
  usethis::with_project(project_path, setwd = TRUE, {
    # Licence
    type_licence(name_licence)

    # NEWS
    usethis::use_template("NEWS.md", data = list(), open = FALSE)
  })

  message("Kit project created")
}
