# WARNING - Generated by {fusen} from /dev/flat_create_r_project_skeleton.Rmd: do not edit by hand

#' Add files necessary for a package, including {golem}
#'
#' @param project_path project_path
#' @param pkgdown_yml path to yaml conf for pkgdown
#' @inheritParams use_dev_history
#'
#' @return Side Effect, add new files :
#'
#' - dev/dev_history
#' - templates for pkgdown if pkgodwn_yml is not null
#' - testthat
#'
#' @export
#'
#' @examples
#' withr::with_tempdir({
#'   project_path <- getwd()
#'   usethis::create_package(path = project_path, open = FALSE)
#'   add_kit_package(project_path, type = c("package", "book", "renv"))
#' })
add_kit_package <- function(
  project_path = ".",
  type = c("package", "renv"),
  pkgdown_yml = NULL
    ) {
  type <- match.arg(type, several.ok = TRUE)

  ## Add dev_history in "dev/"
  dev_path <- normalizePath(file.path(project_path, "dev"), mustWork = FALSE)
  if (!dir.exists(dev_path)) {
    dir.create(dev_path)
  }
  use_dev_history(path = project_path, type = type)

  ## Add pkgdown file
  old <- setwd(project_path)
  on.exit(setwd(old))
  usethis::with_project(project_path, setwd = TRUE, {
    # gitignore
    add_git_ignore(c("docs"))
    # buildignore
    add_build_ignore(c("_pkgdown.yml", "pkgdown", "ci/lib"))

    if (!is.null(pkgdown_yml)) {
      file.copy(
        pkgdown_yml,
        file.path(project_path, "_pkgdown.yml")
      )
    }


    ## Add testthat
    usethis::use_testthat()
    usethis::use_test("start")
  })
  message("Kit package created")

  return(project_path)
}
