# WARNING - Generated by {fusen} from dev/flat_manage_github_projects.Rmd: do not edit by hand

#' add_wikis_github
#'
#' @param owner Owner of the repository
#' @param repo Repository name
#' @param type Wiki type to add
#'
#' @importFrom glue glue
#' @importFrom yesno yesno
#' @importFrom gert git_clone git_pull git_add git_commit git_push
#'
#'
#' @export
#' @examples
#' \dontrun{
#' add_wikis_github(
#'   owner = "ghowner",
#'   repo = "areponame"
#' )
#' }
add_wikis_github <- function(owner,
                             repo, type = c("home", "cr", "keys", "weekly")) {
  type <- match.arg(type, several.ok = TRUE)

  tempwiki <- tempfile(pattern = "wiki")
  wikigit <- glue("https://github.com/{owner}/{repo}.wiki.git")

  wiki_clone <- try(gert::git_clone(url = wikigit, path = tempwiki), silent = TRUE)

  if (!inherits(wiki_clone, "try-error")) {
    message("There already are some wikis")
    # existing wiki are cloned
    # existing_wiki <- gh(req = paste0("projects/", project_id, "/wikis"),
    #                     verb = httr::GET)
  } else {
    yesno::yesno("You need to create a Wiki Home Page on GitHub.com first. Is it done now?")

    wiki_clone <- try(gert::git_clone(url = wikigit, path = tempwiki), silent = TRUE)

    existing_wiki <- list.files(wiki_clone)
    #
    # existing_wiki <- tibble(name = character(0))
    # usethis::create_project(tempwiki, open = FALSE)
    # usethis::with_project(path = tempwiki, {
    #   usethis::use_git()
    #   usethis::use_git_remote(url = wikigit)
    # })
  }

  if ( # "home.md" %in% tolower(existing_wiki) &
    "home" %in% type) {
    gert::git_pull(repo = tempwiki)

    # Always home
    wiki <- readLines(system.file("github", "wiki_home.md", package = "lozen"))
    # Changer {repo}
    wiki <- gsub(pattern = "\\{repo\\}", replacement = repo, x = wiki)
    # Changer {owner}
    wiki <- gsub(pattern = "\\{owner\\}", replacement = owner, x = wiki)

    # Home
    writeLines(wiki, file.path(tempwiki, "Home.md"))
    # rstudioapi::openProject(path = tempwiki, newSession = TRUE)
    gert::git_add(files = c("Home.md", "*.Rproj"), repo = tempwiki)
    gert::git_commit(message = "Update Home wiki", repo = tempwiki)

    gert::git_push(repo = tempwiki)

    message("Wiki home page added")
  }

  if ("cr" %in% type) {
    gert::git_pull(repo = tempwiki)

    # Comptes-rendus
    wiki2 <- readLines(system.file("github", "wiki_cr.md", package = "lozen"))

    # Changer {date}
    wiki2 <- gsub(pattern = "\\{date\\}", replacement = Sys.Date(), x = wiki2)

    # Home
    writeLines(wiki2, file.path(tempwiki, "comptes-rendus.md"))
    # rstudioapi::openProject(path = tempwiki, newSession = TRUE)
    gert::git_add(files = c("comptes-rendus.md", "*.Rproj"), repo = tempwiki)
    gert::git_commit(message = "Add comptes-rendus wiki", repo = tempwiki)

    gert::git_push(repo = tempwiki)

    message("Wiki Comptes-rendus page added")
  }

  if ("keys" %in% type) {
    gert::git_pull(repo = tempwiki)

    # Comptes-rendus
    wiki3 <- readLines(system.file("github", "wiki_keys.md", package = "lozen"))
    # Changer {mon_projet}
    wiki3 <- gsub(pattern = "\\{date\\}", replacement = Sys.Date(), x = wiki3)

    writeLines(wiki3, file.path(tempwiki, "Key_Dates.md"))
    # rstudioapi::openProject(path = tempwiki, newSession = TRUE)
    gert::git_add(files = c("Key_Dates.md", "*.Rproj"), repo = tempwiki)
    gert::git_commit(message = "Add Key Dates wiki", repo = tempwiki)

    gert::git_push(repo = tempwiki)

    message("Wiki 'Key dates' page added")
  }

  if ("weekly" %in% type) {
    gert::git_pull(repo = tempwiki)

    # Comptes-rendus
    # wiki3 <- readLines(system.file("github", "wiki_keys.md", package = "lozen"))
    # Changer {mon_projet}
    # wiki3 <- gsub(pattern = "\\{date\\}", replacement = Sys.Date(), x = wiki3)

    cat("# Weekly", file = file.path(tempwiki, "Weekly.md"))
    # writeLines(wiki3, file.path(tempwiki, "Key_Dates.md"))
    # rstudioapi::openProject(path = tempwiki, newSession = TRUE)
    gert::git_add(files = c("Weekly.md", "*.Rproj"), repo = tempwiki)
    gert::git_commit(message = "Add Weekly wiki", repo = tempwiki)

    gert::git_push(repo = tempwiki)

    message("Wiki 'Key dates' page added")
  }
}
