# WARNING - Generated by {fusen} from dev/flat_manage_github_projects.Rmd: do not edit by hand

#' add_board_github
#'
#' @param owner Owner of the repository
#' @param repo Repository name
#' @param columns Names of columns to create in the Board
#'
#' @importFrom gh gh
#' @importFrom gitlabr multilist_to_tibble
#' @importFrom glue glue
#'
#' @export
#' @examples
#' \dontrun{
#' add_board_github(
#'   owner = "ghowner",
#'   repo = "areponame"
#' )
#' }
add_board_github <- function(owner,
                             repo,
                             columns = c("Open", "Blocked", "Meta", "Ready", "In Progress", "Review", "Validation")) {
  board <- gh::gh(glue("POST /repos/{owner}/{repo}/projects"),
    name = "Development"
  )

  board <- multilist_to_tibble(board)
  project_id <- board[["id"]]

  # Add columns
  for (the_col in columns) {
    gh::gh(glue("POST /projects/{project_id}/columns"),
      name = the_col
    )
    message(glue("Column '{the_col}' created"))
  }
}
