# WARNING - Generated by {fusen} from dev/flat_manage_gitlab_projects.Rmd: do not edit by hand

#' Add Wiki
#'
#' @param project_id project_id
#' @param project_name project_name
#' @param group_url group_url
#' @param group group
#' @param type type
#'
#' @details
#' Types:
#' - home: Home Page
#' - cr: Comptes-rendus
#' - keys: Key dates of the project
#'
#' @return Tibble with wikis and GitLab infos.
#'
#' @importFrom gitlabr gitlab
#' @export
#' @examples
#' \dontrun{
#' add_wikis(
#'   project_id = project_id, 
#'   project_name = project_name, 
#'   group_url = group_url, 
#'   group = basename(group_url)
#' )
#' }
add_wikis <- function(project_id, project_name, group_url, group = basename(group_url), type = c("home", "cr", "keys")) {

  existing_wiki <- gitlab(req = paste0("projects/", project_id, "/wikis"),
                          verb = httr::GET)

  type <- match.arg(type, several.ok = TRUE)

  if (nrow(existing_wiki) == 0 | "home" %in% type) {
    # Always home
    wiki <- readLines(system.file("gitlab", "wiki_home.md", package = "lozen"))
    # Changer {mon_projet}
    wiki <- gsub(pattern = "\\{mon_projet\\}", replacement = project_name, x = wiki)
    # Changer {group}
    wiki <- gsub(pattern = "\\{group\\}", replacement = group, x = wiki)
    # Changer {url}
    wiki <- gsub(pattern = "\\{url\\}", replacement = group_url, x = wiki)

    # Home
    wiki_home <- gitlab(req = paste0("projects/", project_id, "/wikis"),
                        verb = httr::POST,
                        content = paste(wiki, collapse = "\n"),
                        title = "home",
                        format = "markdown")

    message("Wiki home page added")
  }

  if ("cr" %in% type) {
    # Comptes-rendus
    wiki2 <- readLines(system.file("gitlab", "wiki_cr.md", package = "lozen"))
    # Changer {mon_projet}
    wiki2 <- gsub(pattern = "\\{date\\}", replacement = Sys.Date(), x = wiki2)

    wiki_cr <- gitlab(req = paste0("projects/", project_id, "/wikis"),
                      verb = httr::POST,
                      content = paste(wiki2, collapse = "\n"),
                      title = "Comptes-rendus",
                      format = "markdown")

    message("Wiki Comptes-rendus page added")
  }

  if ("keys" %in% type) {
    # Comptes-rendus
    wiki3 <- readLines(system.file("gitlab", "wiki_keys.md", package = "lozen"))
    # Changer {mon_projet}
    wiki3 <- gsub(pattern = "\\{date\\}", replacement = Sys.Date(), x = wiki3)

    wiki_keys <- gitlab(req = paste0("projects/", project_id, "/wikis"),
                      verb = httr::POST,
                      content = paste(wiki3, collapse = "\n"),
                      title = "Key dates",
                      format = "markdown")

    message("Wiki \'Key dates\' page added")
  }

  gitlab(req = paste0("projects/", project_id, "/wikis"),
         verb = httr::GET)
}

