# WARNING - Generated by {fusen} from dev/flat_manage_git.Rmd: do not edit by hand

#' Add MR GitLab or GitHub template and local issue template
#'
#' @param project_path project_path
#' @param type type
#' @param target_dir Directory name where to save templates
#'
#' @return Side effect: template in .gitlab/.github and in .git
#' @export
#'
#' @examples
#' \dontrun{
#' add_git_templates(
#'   project_path = project_path,
#'   type = c("commit", "mr")
#' )
#' }
add_git_templates <- function(
  project_path = ".",
  type = c("commit", "mr"),
  target_dir = ".gitlab"
    ) {
  old <- setwd(project_path)
  on.exit(setwd(old))

  type <- match.arg(type, several.ok = TRUE)

  gitlab_path <- file.path(project_path, target_dir)
  if (!dir.exists(gitlab_path)) {
    dir.create(gitlab_path)
  }

  if (!file.exists(".Rbuildignore")) {
    writeLines("", ".Rbuildignore")
  }
  r_build_ignore <- readLines(".Rbuildignore")
  if (paste0(target_dir, "/") %in% r_build_ignore) {
    writeLines(enc2utf8(c(r_build_ignore, paste0(target_dir, "/"))), ".Rbuildignore")
  }

  ## MR template
  if ("mr" %in% type) {
    if (grepl("gitlab", target_dir)) {
      file.copy(
        system.file("gitlab", "merge_request_templates", package = "lozen"),
        gitlab_path,
        overwrite = TRUE,
        recursive = TRUE
      )
    } else if (grepl("github", target_dir)) {
      file.copy(
        system.file("gitlab", "merge_request_templates", "template_mr.md", package = "lozen"),
        file.path(gitlab_path, "pull_request_template.md"),
        overwrite = TRUE
      )
    }

    message("MR template added, find it when creating a new MR on the graphical interface")
  }

  ## Issue template
  if ("commit" %in% type) {
    file.copy(
      system.file("gitlab", "template_commit", package = "lozen"),
      gitlab_path,
      overwrite = TRUE,
      recursive = TRUE
    )

    if (dir.exists(file.path(project_path, ".git"))) {
      gert::git_config_set(repo = project_path, name = "commit.template", value = paste0(target_dir, "/template_commit"))
      message("Your local git configuration now uses a template for commit message in Terminal")
    } else {
      message(
        "commit.template not set locally because this is not a git repository. ",
        "Start using git with `git init` and set your commit template with:\n",
        glue::glue('gert::git_config_set(repo = "{project_path}", name = "commit.template", value = "{paste0(target_dir, "/template_commit")}")')
      )
    }
  }

  # buildignore
  add_build_ignore(target_dir)
  add_git_ignore(paste0("!", target_dir, "/*/*"))
}
