# WARNING - Generated by {fusen} from dev/flat_manage_gitlab_projects.Rmd: do not edit by hand

#' Add board in the correct order
#'
#' @param project_id project_id
#' @param name Name of the Board
#' @param labels_order Name of the labels already existing in the project
#' @param lg language of the board, "fr" or "en"
#'
#' @importFrom gitlabr gitlab
#' @importFrom tibble tibble
#' @importFrom dplyr left_join filter
#' @export
#' @examples
#' \dontrun{
#' add_board(
#'   project_id = project_id
#' )
#'}
add_board <- function(
    project_id,
    name = "Development",
    labels_order = c("Bloqu\u00e9", "Pr\u00eat", "En cours", "R\u00e9vision", "Pr\u00e9-validation", "A valider"),
    lg = "fr"
) {

  add_labels(project_id, lg = lg)

  ## Checking if the board already exists
  check_if_board_exists <-
    gitlab(req = paste0("projects/", project_id, "/boards"),
           verb = httr::GET,
           name = name)

  if(nrow(check_if_board_exists) == 0) {

    board <- gitlab(req = paste0("projects/", project_id, "/boards"),
                    verb = httr::POST,
                    name = name)

    message("Created a new board")

  } else {
    
    message("The board already exists")
    
  }

  # get existing list of labels
  all_labels <- gitlab(
    req = c("projects", project_id, "labels"),
    verb = httr::GET)

  # get those for a list in the correct order
  all_labels_lists <- tibble(name = labels_order) %>%
    left_join(all_labels, by = "name") %>%
    filter(!is.na(id))

  # Create lists in the board
  for (label_list in all_labels_lists[["id"]]) {
    gitlab(
      req = c("projects", project_id, "boards", board[["id"]][1], "lists"),
      verb = httr::POST,
      label_id = label_list)
  }

  board <- gitlab(req = paste0("projects/", project_id, "/boards"),
                  verb = httr::GET)

  return(board)
}
