# WARNING - Generated by {fusen} from dev/flat_init_gitlab_ci.Rmd: do not edit by hand

#' Amend yaml
#'
#' combien, if needed, to an existing .gitlab-ci.yml file
#'
#'
#' @param path_to_yaml pat to .gtilab-ci.yml file
#' @param connect_ci_list list, output of `create_deploy_ci_stage`
#'
#'
#' @export
#' @examples
#' # amend_yaml()
amend_yaml <- function(
  path_to_yaml,
  connect_ci_list
    ) {
  # Write CI to yaml
  if (file.exists(path_to_yaml)) {
    # Combine existing and new connect CI if yaml already exist
    init_ci_list <- read_ci(path = path_to_yaml)

    combine_ci(
      ci1 = init_ci_list,
      ci2 = connect_ci_list
    ) |>
      clean_image() |>
      write_yaml(
        file = path_to_yaml,
        line.sep = "\r"
      )
  } else {
    # Write connect CI as yaml if no yaml currently exist
    connect_ci_list |>
      write_yaml(
        file = path_to_yaml,
        line.sep = "\r"
      )
  }
}
