# WARNING - Generated by {fusen} from /dev/flat_book_utils.Rmd: do not edit by hand

#' Render bookdown bs4book
#'
#' @return A pagedown template
#' @inheritParams bookdown::bs4_book
#' @importFrom bookdown bs4_book
#' @export
#'
bs4_book_template <- bookdown::bs4_book

