# WARNING - Generated by {fusen} from /dev/flat_book_utils.Rmd: do not edit by hand

#' Render bookdown bs4book
#'
#' @return A pagedown template
#' @inheritParams bookdown::bs4_book
#' @importFrom bookdown bs4_book
#' @export
#'
#' @examples
#' \dontrun{
#' bookdown::render_book("index.Rmd", output_format = "lozen::bs4_book_template")
#' }
bs4_book_template <- function(...) {
  bs4_book(...)
}
