# WARNING - Generated by {fusen} from dev/flat_build_pkgdown_with_reports.Rmd: do not edit by hand

#' Build a pkgdown with extra reports tab for testdown and coverage output
#'
#' @importFrom fs dir_create file_move
#' @importFrom pkgdown build_site
#'
#' @param pkg character The path to the package to be build and reported
#' @param pkgdown_path character The relative path inside the package to store the final site
#' @param assets_path character The relative path within the package to store the reports outputs
#' @param reports character A vector of reports to be produced, can be any subset of `c("testdown","coverage")`
#' @param git_branch_ref character A vector of the git branch to use, 'main' by default
#' @param overwrite_assets logical Whether the assets directory to store reports should be overwritten
#'
#' @return None Generate a pkgdown with test and coverage reports
#' @export
#' @examples
#' \dontrun{
#' # build_pkgdown_with_reports(
#' #    pkg = ".",
#' #    pkgdown_path = "public",
#' #    assets_path = "pkgdown/assets",
#' #    reports = c("testdown","coverage")
#' }
build_pkgdown_with_reports <- function(pkg = ".",
                                       pkgdown_path = "public",
                                       assets_path = "pkgdown/assets",
                                       reports = c("coverage", "testdown", "gitdown"),
                                       git_branch_ref = "main",
                                       overwrite_assets = TRUE) {
  # Selected reports
  reports <- match.arg(
    arg = reports,
    several.ok = TRUE
  )

  # clear assets dir if needed
  if (isTRUE(overwrite_assets)) {
    unlink(file.path(pkg, assets_path), recursive = TRUE)
  }

  # initialize navbar report
  menu <- list()
  if (length(reports) != 0) {
    dir_create(file.path(pkg, assets_path))
  }

  # generate covr report in a tmp folder and move it to assets path
  if (isTRUE("coverage" %in% reports)) {
    if (!requireNamespace("covr", quietly = TRUE)) {
      stop(
        "{covr} needs to be installed for",
        " `lozen::build_pkgdown_with_reports(reports = 'coverage')`",
        " to use `covr::report()`."
      )
    }
    if (!requireNamespace("DT", quietly = TRUE)) {
      stop(
        "{DT} needs to be installed for",
        " `lozen::build_pkgdown_with_reports(reports = 'coverage')`",
        " to use `covr::report()`."
      )
    }
    if (!requireNamespace("htmltools", quietly = TRUE)) {
      stop(
        "{htmltools} needs to be installed for",
        " `lozen::build_pkgdown_with_reports(reports = 'coverage')`",
        " to use `covr::report()`."
      )
    }
    if (!requireNamespace("markdown", quietly = TRUE)) {
      stop(
        "{markdown} needs to be installed for",
        " `lozen::build_pkgdown_with_reports(reports = 'coverage')`",
        " to use `markdown::markdownToHTML()`."
      )
    }
    covr_pkg <- covr::package_coverage(path = pkg)
    covr::report(
      x = covr_pkg,
      file = file.path(assets_path, "coverage", "coverage.html"),
      browse = FALSE
    )

    # file_move(file.path(pkg, "coverage"), file.path(assets_path, "coverage"))
    menu[[length(menu) + 1]] <- list(text = "coverage", href = "coverage/coverage.html")
    # Add coverage explanation
    markdown::markdownToHTML(
      file = system.file("package", "codecoverage_explanation.md",
        package = "lozen"
      ),
      output = file.path(assets_path, "coverage", "codecoverage_explanation.html")
    )
    menu[[length(menu) + 1]] <- list(
      text = "coverage explained",
      href = "coverage/codecoverage_explanation.html"
    )
  }

  # generate testdown report in assets path
  if (isTRUE("testdown" %in% reports)) {
    if (!requireNamespace("testdown", quietly = TRUE)) {
      stop(
        "{testdown} needs to be installed for",
        " `lozen::build_pkgdown_with_reports(reports = 'testdown')`",
        " to use `testdown::test_down()`."
      )
    }

    testdown::test_down(
      pkg = pkg,
      book_path = file.path(assets_path, "testdown"),
      open = FALSE
    )
    menu[[length(menu) + 1]] <- list(text = "testdown", href = "testdown/index.html")
  }

  # generate gitdown report in assets path
  if (isTRUE("gitdown" %in% reports)) {
    if (!requireNamespace("gitdown", quietly = TRUE)) {
      stop(
        "{gitdown} needs to be installed for",
        " `lozen::build_pkgdown_with_reports(reports = 'gitdown')`",
        " to use `gitdown::git_down()`."
      )
    }

    gitdown::git_down(
      repo = pkg,
      book_path = file.path(assets_path, "gitdown"),
      ref = git_branch_ref,
      open = FALSE
    )
    homepage <- file.path(
      "gitdown",
      list.files(
        pattern = "^gitbook-for",
        file.path(assets_path, "gitdown")
      )[1]
    )
    menu[[length(menu) + 1]] <- list(text = "gitdown", href = homepage)
  }

  # prepare yaml settings to add reports in navbar
  yaml_settings <- list(
    destination = pkgdown_path,
    template = list(
      assets = assets_path
    ),
    navbar = list(
      structure = list(
        left = c("intro", "reference", "articles", "tutorials", "news", "reports")
      ),
      components = list(
        reports = list(
          text = "Reports",
          menu = menu
        )
      )
    )
  )

  # build site without preview
  build_site(
    pkg = pkg,
    override = yaml_settings,
    preview = FALSE
  )
}
