# WARNING - Generated by {fusen} from dev/flat_init_gitlab_ci.Rmd: do not edit by hand

#' clean image
#'
#' Manage image in yaml
#'
#' @param ci List of CI parameters, imported from yaml file
#'
#' @return list the list of CI parameters with a unique docker image
#'
#' @export
#' @examples
#' # pkgdown yml
#' full <- yaml::read_yaml(file = system.file("yaml", ".gitlab-ci-pkg.yml", package = "lozen"))
#'
#' # shiny yaml
#' connect <- yaml::read_yaml(file = system.file("yaml", ".gitlab-ci-shiny.yml", package = "lozen"))
#'
#' ci_list <- combine_ci(ci1 = full, ci2 = connect)
#' ci_list <- clean_image(ci_list)
clean_image <- function(ci) {
  ci[["image"]] <- ci[["image"]][1]
  return(ci)
}
