# WARNING - Generated by {fusen} from dev/flat_manage_git.Rmd: do not edit by hand

#' Clone project locally
#'
#' @param project_name project_name
#' @param group_url group_url
#' @param full_url Full url to the repository. Superseeds group_url and project_name if used.
#' @param project_path project_path
#' @param open Logical. Whether to open the RStudio project.
#'
#' @importFrom utils browseURL
#'
#' @return project_path. Side effect: clone the project.
#' @export
#'
#' @examples
#' \dontrun{
#' project_path <- clone_locally(
#'   project_name = the_project[["name"]],
#'   group_url = group_url,
#'   open = TRUE
#' )
#' }
clone_locally <- function(project_name, group_url, full_url, project_path, open = TRUE) {
  if (!missing(full_url)) {
    project_name <- gsub("[.]git$", "", basename(full_url))
  }

  if (missing(project_path)) {
    # Local installation
    tmpdir <- tempfile(pattern = "pkg-")
    dir.create(tmpdir)
    project_path <- file.path(tmpdir, project_name)
  }

  if (!missing(full_url)) {
    # normalgit2r <- try(
    #   git2r::clone(url = full_url, local_path = project_path)
    # )
    #
    # if (inherits(normalgit2r, "try-error")) {
    gert::git_clone(
      url = full_url,
      path = project_path
    )
    # }
    # }
  } else {
    # normalgit2r <- try(
    #   git2r::clone(url = paste0(group_url, "/", project_name), local_path = project_path)
    # )
    #
    # if (inherits(normalgit2r, "try-error")) {
    #   cleangit2r <- try(
    #     git2r::clone(
    #       url = paste0(group_url, "/", gsub("[.]", "-", project_name)),
    #       local_path = project_path
    #     )
    #   )
    #
    #   if (inherits(cleangit2r, "try-error")) {
    normal <- try(
      gert::git_clone(
        url = paste0(group_url, "/", project_name),
        path = project_path
      )
    )

    if (inherits(normal, "try-error")) {
      gert::git_clone(
        url = paste0(group_url, "/", gsub("[.]", "-", project_name)),
        path = project_path
      )
      #   }
      # }
    }
  }

  if (isTRUE(open)) {
    browseURL(project_path)
  }

  message("Project cloned locally: ", project_path)
  project_path
}
