# WARNING - Generated by {fusen} from dev/flat_init_gitlab_ci.Rmd: do not edit by hand

#' combine CI
#'
#' Merge two yaml as a list into a combined list
#'
#' @param ci1 List of initial CI parameters
#' @param ci2 List of CI parameters to append to the initial CI
#'
#' @importFrom purrr map map2
#' @importFrom stats setNames
#'
#' @return list list of combined CI parameters
#'
#' @export
#' @examples
#' # pkgdown yml
#' full <- yaml::read_yaml(file = system.file("yaml", ".gitlab-ci-pkg.yml", package = "lozen"))
#' 
#' # shiny yaml
#' connect <- yaml::read_yaml(file = system.file("yaml", ".gitlab-ci-shiny.yml", package = "lozen"))
#' 
#' ci_list <- combine_ci(ci1 = full, ci2 = connect)
combine_ci <- function(ci1, ci2) {
  les_nom <- unique(c(names(ci1), names(ci2)))

  duplicated_with_name <- function(.x, .y, ...) {
    !duplicated(paste(names(.x), .x))
  }

  bonne_base <- les_nom %>%
    map(~ {
      (c(ci1[[.x]], ci2[[.x]]))
    }) %>%
    setNames(les_nom)
  bool <- map2(
    .x = bonne_base, .y = names(bonne_base),
    .f = duplicated_with_name
  )
  out <- map2(bonne_base, bool, .f = ~ .x[.y])
  return(out)
}
