# WARNING - Generated by {fusen} from dev/flat_book_utils.Rmd: do not edit by hand

#' Compile a unique "fiche" Rmd
#' @param fiche Path to fiche Rmd
#' @param outdir Directory where to save the output HTML
#' @param type Choose output type: html or odt
#' @param open Logical. Whether to open file at the end
#' @return compiled fiches
#' @noRd 
compile_fiche <- function(fiche, outdir = "public", type = "html", open = TRUE) {
  type <- match.arg(type, choices = c("html", "odt"), several.ok = TRUE)
  
  fiche <- normalizePath(fiche, mustWork = TRUE)
  if (!dir.exists(outdir)) {
    dir.create(outdir, recursive = TRUE)
  }
  
  # copy all except Rmd in tempdir
  compil_dir <- tempfile("compildir")
  fs::dir_copy(dirname(fiche), compil_dir)
  
  all_rmds <- list.files(compil_dir, pattern = "[.](R|r)md",
                         full.names = TRUE, recursive = FALSE)
  rmds_to_remove <- all_rmds[!grepl(
    paste0("^index[.]Rmd$|^", basename(fiche), "$"), basename(all_rmds))]
  file.remove(rmds_to_remove)
  
  withr::with_dir(compil_dir, {
    bookdown::render_book(
      "index.Rmd",
      output_format = "lozen::paged_template"
    )
  })
  
  outfile <- file.path(outdir, gsub("[.](R|r)md", ".html", basename(fiche)))
  file.copy(file.path(compil_dir, "_main.html"), outfile)
  message(basename(outfile), " file created")
  
  # transform as odt
  if ("odt" %in% type) {
    # file path
    outodt <- file.path(outdir, gsub("[.](R|r)md", ".odt", basename(fiche)))
    html_to_odt(input_html = file.path(compil_dir, "_main.html"),
                output_odt = outodt)
    
  } else {
    outodt <- NULL
  }
  
  # clean compil_dir
  unlink(compil_dir, recursive = TRUE)
  
  if (isTRUE(open)) {
    utils::browseURL(outfile)
  }
  
  return(c(outfile, outodt))
    
}
