# WARNING - Generated by {fusen} from dev/flat_book_utils.Rmd: do not edit by hand

#' Compile all fiches Rmd
#' @param fiches Path to fiches Rmd
#' @param outdir Directory where to save the output HTML
#' @param type Choose output type: html or odt
#' @param open Logical. Whether to open file at the end
#' @return compiled fiches
#' @noRd
#'
#' @examples
#' compile_fiches()
compile_fiches <- function(fiches, type = "html", outdir = "public", open = TRUE) {
  type <- match.arg(type, choices = c("html", "odt"), several.ok = TRUE)
  out <- lapply(fiches, compile_fiche, type = type, outdir = outdir, open = open)
  return(unlist(out))
}
