# WARNING - Generated by {fusen} from dev/flat_init_gitlab_ci.Rmd: do not edit by hand

#' Title
#'

#' @param image image
#'
#' @param deploy_function deploy_function
#' @param stage_name stage_name
#' @param ... dots not used
#' @importFrom purrr map2_chr
#' @importFrom utils getFromNamespace
#' @export
#' @examples
#' create_deploy_ci_stage(
#'   image = "rocker/verse",
#'   deploy_function = "deploy_connect_shiny"
#' )
create_deploy_ci_stage <- function(image,
                                   deploy_function,
                                   stage_name = deploy_function,
                                   ...) {
  stopifnot("deploy_function exist" = length(getFromNamespace(x = deploy_function, "lozen")) > 0)
  #  dots <- list(...)
  #  if ( length(dots) == 0){  dots <-""}
  #  bonus <- paste(map2_chr(as.character(names(dots)),
  #
  #                           as.character(glue::glue('"{dots}"'))
  #
  #
  #                          ,paste, sep = " = "),collapse=",")
  #
  # le_call <- glue::glue("Rscript -e 'lozen::{deploy_function}(connect_url = Sys.getenv(\"CONNECT_URL\"),connect_user = Sys.getenv(\"CONNECT_USER\"),connect_api_token = Sys.getenv(\"CONNECT_TOKEN\"),app_name = Sys.getenv(\"APP_NAME\", unset = Sys.getenv(\"CI_PROJECT_NAME\")),{bonus})'"
  #        )
  # IDEE de COlin a creuser pour permettre un controle fin des parametres depuis le CI
  #   build_rscript_call <- function(lozen_fun, ...) {
  #   dots <- match.call(expand.dots = FALSE)$`...`
  #   sprintf(
  #     "Rscript -e 'lozen::%s(%s)'",
  #     as.character(substitute(lozen_fun)),
  #     paste(
  #       names(dots),
  #       dots,
  #       sep = "=",
  #       collapse = ","
  #     )
  #   )
  # }



  le_call <- glue::glue("Rscript -e 'lozen::{deploy_function}(connect_url = Sys.getenv(\"CONNECT_URL\"),connect_user = Sys.getenv(\"CONNECT_USER\"),connect_api_token = Sys.getenv(\"CONNECT_TOKEN\"),app_name = Sys.getenv(\"APP_NAME\", unset = Sys.getenv(\"CI_PROJECT_NAME\")))'")

  # Create list of Connect CI parameters
  connect_ci_list <- list(
    image = image,
    variables = list(
      R_LIBS_USER = "ci/lib"
    ),
    cache = list(
      key = "global-cache",
      paths = list(
        "${R_LIBS_USER}"
      )
    ),
    stages = list(
      stage_name
    ),
    deploying = list(
      stage = stage_name,
      script = c(
        "echo \"Library path for packages :\" $R_LIBS_USER",
        "mkdir -p $R_LIBS_USER",
        # Install git2r and pak
        "Rscript -e 'install.packages(c(\"git2r\"));install.packages(\"gitlabr\", repos = c(\"https://thinkr-open.r-universe.dev\", \"https://cloud.r-project.org\"))'",
        "Rscript -e 'remotes::install_github(\"thinkr-open/lozen\", auth_token = Sys.getenv(\"GITHUB_TOKEN\"), build_vignettes = FALSE, ref = Sys.getenv(\"LOZEN_BRANCH\", unset = \"main\"))'",
        le_call
      )
    )
  )
  connect_ci_list
}
