# WARNING - Generated by {fusen} from dev/flat_create_special_issues.Rmd: do not edit by hand

#' Add First issue client for GitLab
#'
#' @param project_id project_id
#' @param project_name project_name
#' @param group_url group_url
#'
#' @importFrom gitlabr gl_new_issue
#'
#' @return A tibble with the issue added and GitLab infos
#'
#'
#' @export
#' @examples
#' \dontrun{
#' add_issue_clients(
#'   project_id = "<get_your_id_project>",
#'   project_name = "<get_your_project_name>",
#'   group_url = "<group_url_repo>" # should looks like "https://gitlab.com/cervan.girard/"
#' )
#' }
add_issue_clients <- function(project_id, project_name, group_url) {
  # create issue text
  issue_client <- create_issue_content_clients(project_name = project_name, group_url = group_url)

  # Create issue
  issue_client_id <- gl_new_issue(
    title = "Bienvenue sur le suivi de projet GitLab",
    project = project_id,
    description = paste(issue_client, collapse = "\n"),
    labels = c("Bloqu\u00e9")
  )

  message("Issue Client cr\u00e9\u00e9e : ", issue_client_id[["iid"]])
  return(issue_client_id)
}

#' Add First issue client for GitHub
#'
#' @param owner GitHub owner (username or organisation)
#' @param repo Name of the repository
#'
#' @importFrom gh gh
#' @importFrom dplyr filter pull
#' @importFrom gitlabr multilist_to_tibble
#'
#' @return A tibble with the issue added and GitLab infos
#'
#'
#' @export
#' @examples
#' \dontrun{
#' add_issue_clients_github(
#'   owner = "owner",
#'   repo = "repo"
#' )
#' }
add_issue_clients_github <- function(owner, repo) {
  # Fetch text

  issue_client <- create_issue_content_clients_github(
    owner = owner,
    repo = repo
  )

  # Fetch current issues
  issue_listing <- gh(
    "GET /repos/{owner}/{repo}/issues",
    owner = owner,
    repo = repo,
    state = "all"
  )
  issue_listing_tbl <- multilist_to_tibble(issue_listing)

  # Check issue exists
  issue_title <- "Bienvenue sur le suivi de projet GitHub"
  issue_is_in_list <- issue_title %in% issue_listing_tbl[["title"]]

  if (isTRUE(issue_is_in_list)) { # if the issue already exists

    issue_client_id <- issue_listing_tbl %>% filter(title == issue_title)
    issue_status <- issue_client_id %>% pull(state)
    issue_number <- issue_client_id %>% pull(number)

    # Reopen issue if closed
    if (isTRUE(issue_status == "closed")) {
      issue_client_id <- gh(
        "PATCH /repos/{owner}/{repo}/issues/{issue_number}",
        owner = owner,
        repo = repo,
        issue_number = issue_number,
        state = "open"
      )

      message("The issue dedicated to the client is open again: ", issue_client_id[["id"]])

      # json to tibble
      issue_client_id <- multilist_to_tibble(issue_client_id)
    } else {
      message("The issue dedicated to the client is open : ", issue_client_id[["id"]])
    }
  } else {
    # Create new issue
    issue_client_id <- gh(
      "POST /repos/{owner}/{repo}/issues",
      owner = owner,
      repo = repo,
      title = issue_title,
      body = paste(issue_client, collapse = "\n"),
      labels = list("Bloqu\u00e9")
    )
    # json to tibble
    issue_client_id <- multilist_to_tibble(issue_client_id)

    message("The issue dedicated to the client has been created : ", issue_client_id[["id"]])
  }
  return(issue_client_id)
}

#' Create issue for developers to initiate the project
#'
#' @param project_id project_id
#' @param project_name project_name
#' @param group_url group_url
#'
#' @importFrom gitlabr gl_new_issue
#'
#' @return Side effect: new issue on GitLab
#'
#'
#' @export
#' @examples
#' # exemple nécessite des opérations sur gitlab : à voir
#' \dontrun{
#' add_issue_dev(
#'   project_id = "<get_your_id_project>",
#'   project_name = "<get_your_project_name>",
#'   group_url = "<group_url_repo>" # should looks like "https://gitlab.com/cervan.girard/"
#' )
#' }
add_issue_dev <- function(project_id, project_name, group_url) {
  # create issue text
  issue_dev <- create_issue_content_dev(
    project_id = project_id,
    group_url = group_url,
    project_name = project_name
  )

  # Create issue
  issue_dev_id <- gl_new_issue(
    title = "[dev] Checklist mise en place",
    project = project_id,
    description = paste(issue_dev, collapse = "\n"),
    labels = c("Bloqu\u00e9")
  )

  message("Rdv dans votre premi\u00e8re issue pour finaliser : ", issue_dev_id[["web_url"]])

  return(issue_dev_id)
}

#' Create issue for dev on github
#'
#' Create dev first issue in github
#'
#' @param owner owner of the project
#' @param repo name of the project
#'
#' @importFrom gh gh
#' @importFrom gitlabr multilist_to_tibble
#'
#'
#'
#' @return tibble with github issue info
#'
#' @export
#' @examples
#' \dontrun{
#' add_issue_dev_github(
#'   owner = "owner",
#'   repo = "repo"
#' )
#' }
add_issue_dev_github <- function(owner, repo) {
  # Fetch content
  issue_dev <- create_issue_content_dev_github(
    owner = owner,
    repo = repo
  )

  # Fetch current issues
  issue_listing <- gh(
    "GET /repos/{owner}/{repo}/issues",
    owner = owner,
    repo = repo,
    state = "all"
  )
  issue_listing_tbl <- multilist_to_tibble(issue_listing)

  # Check issue exists
  issue_title <- "[dev] Checklist mise en place"
  issue_is_in_list <- issue_title %in% issue_listing_tbl[["title"]]

  if (isTRUE(issue_is_in_list)) { # if the issue already exists

    issue_client_id <- issue_listing_tbl %>% filter(title == issue_title)
    issue_status <- issue_client_id %>% pull(state)
    issue_number <- issue_client_id %>% pull(number)

    # Reopen issue if closed
    if (isTRUE(issue_status == "closed")) {
      issue_client_id <- gh(
        "PATCH /repos/{owner}/{repo}/issues/{issue_number}",
        owner = owner,
        repo = repo,
        issue_number = issue_number,
        state = "open"
      )

      message("The issue dedicated to the dev is open again: ", issue_client_id[["id"]])

      # json to tibble
      issue_client_id <- multilist_to_tibble(issue_client_id)
    } else {
      message("The issue dedicated to the dev is open : ", issue_client_id[["id"]])
    }
  } else {
    # Create new issue
    issue_client_id <- gh(
      "POST /repos/{owner}/{repo}/issues",
      owner = owner,
      repo = repo,
      title = issue_title,
      body = paste(issue_dev, collapse = "\n"),
      labels = list("Bloqu\u00e9")
    )
    # json to tibble
    issue_client_id <- multilist_to_tibble(issue_client_id)

    message("Rdv dans votre premi\u00e8re issue pour finaliser : ", issue_client_id[["url"]])
  }
  return(issue_client_id)
}

#' Add Kickoff issue client for GitLab
#'
#' @param project_id project_id
#'
#' @importFrom gitlabr gl_new_issue gl_list_issues
#' @importFrom dplyr filter
#'
#' @return A tibble with the issue added and GitLab infos
#'
#'
#' @export
#' @examples
#' \dontrun{
#' add_issue_kickoff(project_id = "<get_your_id_project>")
#' }
add_issue_kickoff <- function(project_id) {
  kickoff_title <- "ETQ client, j\'ai compris le fonctionnement de la validation des tickets"

  project_issues <- gl_list_issues(project = project_id)

  # fetch issue in project
  if (nrow(project_issues) != 0) {
    project_kickoff_issue <- project_issues %>%
      filter(title == kickoff_title)

    # check issue already exists
    if (!isTRUE(nrow(project_kickoff_issue) == 0)) {
      message("Kickoff issue already exists in this project.")
      return(project_kickoff_issue)
    }
  }


  # create issue text
  issue_kickoff <- create_issue_content_kickoff()

  # Create issue
  issue_kickoff_id <- gl_new_issue(
    title = kickoff_title,
    project = project_id,
    description = paste(issue_kickoff, collapse = "\n"),
    labels = c("Pr\u00eat")
  )

  message("Issue Kickoff cr\u00e9\u00e9e : ", issue_kickoff_id[["iid"]])
  return(issue_kickoff_id)
}

#' Add Kickoff issue for GitHub
#'
#' @param owner GitHub owner (username or organisation)
#' @param repo Name of the repository
#'
#' @importFrom gh gh
#' @importFrom dplyr filter pull
#' @importFrom gitlabr multilist_to_tibble
#'
#' @return A tibble with the issue added and GitHub infos
#'
#'
#' @export
#' @examples
#' \dontrun{
#' add_issue_kickoff_github(
#'   owner = "owner",
#'   repo = "repo"
#' )
#' }
add_issue_kickoff_github <- function(owner, repo) {
  # Fetch issue text and title
  kickoff_title <-
    "ETQ client, j\'ai compris le fonctionnement de la validation des tickets"
  issue_kickoff <- create_issue_content_kickoff()

  # Fetch current issues
  issue_listing <- gh(
    "GET /repos/{owner}/{repo}/issues",
    owner = owner,
    repo = repo,
    state = "all"
  )
  issue_listing_tbl <- multilist_to_tibble(issue_listing)

  # Check issue exists
  issue_is_in_list <- kickoff_title %in% issue_listing_tbl[["title"]]

  if (isTRUE(issue_is_in_list)) { # if the issue already exists

    issue_kkoff_id <- issue_listing_tbl %>% filter(title == kickoff_title)
    issue_status <- issue_kkoff_id %>% pull(state)
    issue_number <- issue_kkoff_id %>% pull(number)

    # Reopen issue if closed
    if (isTRUE(issue_status == "closed")) {
      issue_kkoff_id <-
        gh(
          "PATCH /repos/{owner}/{repo}/issues/{issue_number}",
          owner = owner,
          repo = repo,
          issue_number = issue_number,
          state = "open"
        )

      # json to tibble
      issue_kkoff_id <- multilist_to_tibble(issue_kkoff_id)

      message("The Kickoff issue is re-opened : ", issue_kkoff_id[["id"]])
    } else {
      message("The Kickoff issue is already open : ", issue_kkoff_id[["id"]])
    }
  } else {
    # Create new issue
    issue_kkoff_id <- gh(
      "POST /repos/{owner}/{repo}/issues",
      owner = owner,
      repo = repo,
      title = kickoff_title,
      body = paste(issue_kickoff, collapse = "\n")
    )

    # json to tibble
    issue_kkoff_id <- multilist_to_tibble(issue_kkoff_id)

    message("Kickoff issue created : ", issue_kkoff_id[["id"]])
  }
  return(issue_kkoff_id)
}

#' Create issue content for client
#'
#' Generate text for client first issue in gitlab
#'
#' @param project_name name of the project
#' @param group_url url to gitlab website
#'
#' @return character vector of the issue content
#'
#'
#' @export
#' @examples
#' \dontrun{
#' create_issue_content_clients(
#'   project_name = "<get_your_project_name>",
#'   group_url = "<group_url_repo>" # should looks like "https://gitlab.com/cervan.girard/"
#' )
#' }
create_issue_content_clients <- function(project_name, group_url) {
  # gl_list_issues(project_id)
  issue_client <-
    readLines(system.file("gitlab", "first_issue_client.md", package = "lozen"))

  # Changer {mon_projet}
  issue_client <-
    gsub(
      pattern = "\\{mon_projet\\}",
      replacement = project_name,
      x = issue_client
    )

  # Changer {url}
  issue_client <-
    gsub(
      pattern = "\\{url\\}",
      replacement = group_url,
      x = issue_client
    )

  return(issue_client)
}

#' Create issue content for client
#'
#' Generate text for client first issue in github
#'
#' @param owner owner of the project
#' @param repo name of the project
#'
#' @return character vector of the issue content
#'
#'
#' @export
#' @examples
#' \dontrun{
#' create_issue_content_clients_github(
#'   owner = "owner",
#'   repo = "repo"
#' )
#' }
create_issue_content_clients_github <- function(owner, repo) {
  # get text from md file
  issue_client <- readLines(
    system.file(
      "github",
      "first_issue_client.md",
      package = "lozen"
    )
  )

  # Changer {mon_projet}
  issue_client <- gsub(
    pattern = "\\{mon_projet\\}",
    replacement = repo,
    x = issue_client
  )

  # Changer {url}
  issue_client <- gsub(
    pattern = "\\{url\\}",
    replacement = paste0("https://github.com/", owner, "/", repo),
    x = issue_client
  )

  return(issue_client)
}

#' Create issue content for devs
#'
#' Generate text for devs first issue in gitlab
#'
#' @param project_id project_id
#' @param group_url group_url
#' @param project_name project_name
#'
#' @importFrom gitlabr gl_list_issues
#'
#' @return character vector of the issue content
#'
#'
#' @export
#' @examples
#' \dontrun{
#' create_issue_content_dev(
#'   project_id = "<get_your_id_project>",
#'   project_name = "<get_your_project_name>",
#'   group_url = "<group_url_repo>" # should looks like "https://gitlab.com/cervan.girard/"
#' )
#' }
create_issue_content_dev <- function(project_id, group_url, project_name) {
  issues_list <- gl_list_issues(project = project_id)
  is_bienvenue <- grepl("Bienvenue", issues_list[["title"]])

  if (isTRUE(any(is_bienvenue))) {
    url_issue_client <- issues_list[is_bienvenue, ][1, ][["web_url"]]
  } else {
    url_issue_client <- NA
  }

  issue_dev <- paste(
    "## Mise en place de la plateforme de dev",
    "Il faut anticiper les demandes pour le d\u00e9veloppement de ce projet :",
    "Ce projet sera d\u00e9velopp\u00e9 sur [[ A REMPLIR]]. Il faut anticiper les demandes pour la plateforme de d\u00e9veloppement de ce projet :",
    "- [ ] R\u00e9fl\u00e9chir \u00e0 l\'infra n\u00e9cessaire. Faut-il une version sp\u00e9cifique de R ? Une version du CRAN sp\u00e9cifique ?",
    "- [ ] R\u00e9fl\u00e9chir aux sessions des users qui auront acc\u00e8s \u00e0 la plateforme. Quels users (les devs, les client.e.s) ?",
    "## Finalisation du board",
    "- [ ] Ajouter les colonnes des issues dans le board dans l\'ordre : Bloqu\u00e9, Pr\u00eat, En cours, R\u00e9vision, A valider. Les autres sont en bonus.",
    "## Calendrier",
    "- [ ] Remplir les Key Dates - _e.g. dates de livraisons interm\u00e9diaires, date range des phases du projet_",
    "- [ ] Remplir le calendrier pr\u00e9visionnel",
    "## Gestion des compte-rendus",
    paste0(
      "- [ ] Choisir la m\u00e9thode de partage de comptes-rendus (Wiki ou projet s\u00e9par\u00e9) et l\'indiquer dans la pr\u00e9sentation du projet (= Wiki Home) : ",
      group_url,
      "/",
      project_name,
      "/-/wikis/home"
    ),
    paste0("- [ ] Indiquer aussi la m\u00e9thode de partage de CR dans l\'issue de Bienvenue du Client : ", url_issue_client),
    "## Acc\u00e8s au projet (si n\u00e9cessaire)",
    "### Pour des raisons de s\u00e9curit\u00e9, il est conseill\u00e9 de stocker les projets d\'un client donn\u00e9 dans un groupe d\u00e9di\u00e9 :",
    "- [ ] Cr\u00e9er un groupe d\u00e9di\u00e9, par d\u00e9faut sans utilisateurs - _Menu > Groups > Create group_",
    "- [ ] Inviter les clients sur le groupe - _Menu > Admin puis dans Users > New user (mettre Projects limit \u00e0 0 et d\u00e9cocher Can create group)_",
    '- [ ] Ajouter chaque utilisateur au groupe d\u00e9di\u00e9 en tant que \"Guest\"',
    '- [ ] Ajouter le groupe en tant que \"Guest\" dans le d\u00e9p\u00f4t cr\u00e9\u00e9 pour le projet (Ils pourront voir le Kanban, mais pas le code)',
    paste0(
      "- [ ] Notifier chaque utilisateur en les mentionnant dans un commentaire de l\'issue : ",
      url_issue_client,
      " avec le texte suivant : \n```\nMerci de bien vouloir lire et valider le contenu de cette page.\n",
      "Si vous lisez ce message dans un email, vous pouvez cliquer sur le lien suivant pour acc\u00e9der \u00e0 la page :\n",
      url_issue_client,
      "\n@mention, @mention, ...\n```\n"
    ),
    '- [ ] Pr\u00e9venir les chefs de projets de monter le niveau de Notification \u00e0 \"Watch\" sur la page d\'accueil du projet pour recevoir toutes les notifications',
    sep = "\n"
  )

  return(issue_dev)
}

#' Create issue content for dev
#'
#' Generate text for dev first issue in github
#'
#' @param owner owner of the project
#' @param repo name of the project
#'
#' @importFrom glue glue
#' @importFrom gh gh
#' @importFrom gitlabr multilist_to_tibble
#'
#' @return character vector of the issue content
#'
#'
#'
#' @export
#' @examples
#' \dontrun{
#' create_issue_content_dev_github(
#'   owner = "owner",
#'   repo = "repo"
#' )
#' }
create_issue_content_dev_github <- function(owner, repo) {
  # Get Bienvenue issue
  issues <- gh(
    "GET /repos/{owner}/{repo}/issues",
    owner = owner,
    repo = repo,
    state = "all"
  )
  issues_list <- multilist_to_tibble(issues)

  is_bienvenue <- grepl("Bienvenue", issues_list[["title"]])
  if (isTRUE(any(is_bienvenue))) {
    url_issue_client <- issues_list[is_bienvenue, ][1, ][["html_url"]]
  } else {
    url_issue_client <- NA
  }

  issue_dev <- paste(
    "- [ ] Remplir les Key Dates et le calendrier pr\u00e9visionnel",
    '- [ ] Ajouter chaque utilisateur au projet en tant que \"Guest\"',
    '- [ ] Pr\u00e9venir les chefs de projets de monter le niveau de Notification \u00e0 \"Watch\" sur la page d\'accueil du projet pour recevoir toutes les notifications',
    paste0("- [ ] S'assurer que le Board est pret:", glue("https://github.com/{owner}/{repo}/projects/1")),
    paste0("- [ ] S'assurer que le Wiki Home est pret:", glue("https://github.com/{owner}/{repo}/wiki/Home")),
    paste0("- [ ] Indiquer aussi la m\u00e9thode de partage de CR dans l'issue de Bienvenue du Client : ", url_issue_client),
    paste0(
      "- [ ] Notifier chaque utilisateur en les mentionnant dans un commentaire de l'issue : ",
      url_issue_client,
      " avec le texte suivant : \n```\nMerci de bien vouloir lire et valider le contenu de cette page.\n",
      "Si vous lisez ce message dans un email, vous pouvez cliquer sur le lien suivant pour acc\u00e9der \u00e0 la page :\n",
      url_issue_client,
      "\n@mention, @mention, ...\n```\n"
    ),
    '- [ ] Mettre en place {renv} en suivant \"dev/dev_history_renv.R\"',
    '- [ ] Si n\u00e9cessaires, ex\u00e9cuter les \u00e9tapes de \"dev/dev_history.R\". La plupart sont d\u00e9ja faites.',
    sep = "\n"
  )

  return(issue_dev)
}

#' Create issue content for kickoff
#'
#' Generate text for kickoff issue
#'
#' @return character vector of the issue content
#'
#'
#' @export
#' @examples
#' create_issue_content_kickoff()
create_issue_content_kickoff <- function() {
  # get content from md file
  issue_kickoff <-
    readLines(system.file("gitlab", "kickoff_issue_client.md", package = "lozen"))

  return(issue_kickoff)
}
