# WARNING - Generated by {fusen} from dev/flat_init_gitlab_ci.Rmd: do not edit by hand

#' Title
#'

#' @param image image#'
#' @param deploy_function deploy_function
#' @param stage_name stage_name
#' @param ... dots not used
#' @importFrom purrr map2_chr
#' @importFrom utils getFromNamespace
#' @export
#' @examples
#' create_deploy_ci_stage(
#'   image = "rocker/verse",
#'   deploy_function = "deploy_connect_shiny"
#' )
create_deploy_ci_stage <- function(
    image,
    deploy_function,
    stage_name = deploy_function,
    ...) {
  stopifnot("deploy_function exist" = length(getFromNamespace(x = deploy_function, "lozen")) > 0)

  le_call <- glue::glue(
    "Rscript -e 'options(rsconnect.packrat = TRUE); lozen::{deploy_function}(forceUpdate=TRUE, connect_url = Sys.getenv(\"CONNECT_URL\"),connect_user = Sys.getenv(\"CONNECT_USER\"),connect_api_token = Sys.getenv(\"CONNECT_TOKEN\"),app_name = Sys.getenv(\"APP_NAME\", unset = Sys.getenv(\"CI_PROJECT_NAME\")))'"
  )

  # Create list of Connect CI parameters
  connect_ci_list <- list(
    image = image,
    variables = list(
      GIT_DEPTH= 10L,
      REPO_NAME = "https://packagemanager.rstudio.com/all/__linux__/focal/latest",
      R_LIBS_USER = "ci/lib"
    ),
    cache = list(
      key = "global-cache",
      paths = list(
        "${R_LIBS_USER}"
      )
    ),
    stages = list(
      stage_name
    ),
    deploying = list(
      stage = stage_name,
      script = c(
        "echo \"Library path for packages :\" $R_LIBS_USER",
        "mkdir -p $R_LIBS_USER",
        # Install git2r and pak
        "Rscript -e 'install.packages(c(\"git2r\"));install.packages(\"gitlabr\", repos = c(\"https://thinkr-open.r-universe.dev\", \"https://cloud.r-project.org\"))'",
        "Rscript -e 'install.packages(\"lozen\", repos = c(\"https://thinkr-open.r-universe.dev\", \"https://cran.rstudio.com\"))'",
        "Rscript -e 'remotes::install_local(dependencies = TRUE)'",
        le_call
      )
    )
  )
  connect_ci_list
}
