# WARNING - Generated by {fusen} from dev/flat_create_r_project_skeleton.Rmd: do not edit by hand

#' Create a R project with full content skeleton
#'
#' @param project_path project_path
#' @param type type
#' @param name_licence name for the licence
#' @param type_licence type of the licence, should be a function like usethis::use_mit_licence
#'
#' @return Side Effect: Transform project as package or book:
#'
#' - With package, golem or book skeleton
#' - git necessary files
#' - pkgdown or book template
#' - GitLab CI
#'
#' @export
#'
#' @examples
#' ### R package skeleton
#' withr::with_tempdir({
#'   project_path <- getwd()
#'   create_r_project(
#'     project_path,
#'     type = c("package"),
#'     name_licence = "Bob",
#'     type_licence = usethis::use_proprietary_license
#'   )
#' })
#'
#'
#' ### Shiny app
#' withr::with_tempdir({
#'   project_path <- getwd()
#'   create_r_project(
#'     project_path,
#'     type = c("golem"),
#'     name_licence = "Bob",
#'     type_licence = usethis::use_proprietary_license
#'   )
#' })
#'
#' ### Bookdown
#' withr::with_tempdir({
#'   project_path <- getwd()
#'   create_r_project(
#'     project_path,
#'     type = c("book"),
#'     name_licence = "Bob",
#'     type_licence = usethis::use_proprietary_license
#'   )
#' })
#'
create_r_project <- function(project_path, type = c("package", "golem", "book"), name_licence, type_licence) {
  type <- match.arg(type)

  if (type == "book") {
    create_book_project(project_path)
  } else {
    # Transform as R package
    # Change wd and proj for usethis
    # old <- setwd(project_path)
    # Create project in case not already a project
    usethis::create_project(project_path, open = FALSE)
    # create content
    usethis::with_project(project_path, {
      if (type == "package") {
        usethis::create_package(path = project_path, open = FALSE)
        attachment::att_amend_desc()
      } else if (type == "golem") {
        golem::create_golem(path = project_path, open = FALSE, overwrite = TRUE)
        attachment::att_amend_desc()
      }
    })
  }
  # setwd(old)

  add_kit_project(project_path, name_licence = name_licence, type_licence = type_licence)

  if (type %in% c("package", "golem")) {
    add_kit_package(project_path)
  }

  project_path
}
