# WARNING - Generated by {fusen} from dev/flat_manage_github_projects.Rmd: do not edit by hand

#' Create new project on GitHub
#'
#' @param repo name of the project to create
#' @param owner Owner of the repo
#'
#' @importFrom gh gh
#' @importFrom glue glue
#' @importFrom yesno yesno
#'
#' @return project_id. Side effect: Create a project on GitHub if not exists.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' create_group_project_github(
#'   repo = "areponame",
#'   owner = "ghowner"
#' )
#' }
create_group_project_github <- function(repo, owner) {
  repo_exists <- try(gh(glue("/repos/{owner}/{repo}")), silent = TRUE)

  if (!inherits(repo_exists, "try-error")) {
    message("Project: '", repo, "' already exists in group: ", owner)
  } else {
    # Create project
    # my_project <- gh(glue("POST /repos/{owner}/{repo}"))
    # project_id <- my_project$id
    # message("New project created: ", project_id)
    yesno::yesno(glue("You need to create the repository yourself. Did you created {owner}/{repo} ?"))
  }

  glue("{owner}/{repo}")
  # as.numeric(project_id)
}
