# WARNING - Generated by {fusen} from dev/flat_manage_gitlab_projects.Rmd: do not edit by hand

#' Create new project in a group
#'
#' @param project_name name of the project to create
#' @param namespace_id id of the group in which to add the project
#' @param gitlab_con Connection credentials to GitLab.
#'  Better use `set_gitlab_connection()` before this function
#' @param default_branch Default branch for the project created. Default to "main".
#'
#' @return project_id. Side effect: Create a project on GitLab if not exists.
#' @importFrom gitlabr gitlab
#' @importFrom dplyr filter pull
#' @export
#'
#' @examples
#' \dontrun{
#' create_group_project(
#'   project_name = project_name,
#'   namespace_id = namespace_id,
#'   default_branch = "main"
#' )
#' }
create_group_project <- function(project_name, namespace_id, gitlab_con = "default", default_branch = "main") {
  if (!is.null(namespace_id)) {
    group_projects <- gitlab(
      req = paste0("groups/", namespace_id, "/projects"),
      verb = httr::GET,
      gitlab_con = gitlab_con
    )

    if (project_name %in% group_projects[["name"]]) {
      project_id <- filter(group_projects, name == project_name)[["id"]]

      message(
        "Project: \'",
        project_name,
        "\' already exists in group: ",
        namespace_id,
        # filter(all_groups, id == namespace_id)[["name"]],
        ". ",
        "Using project_id: ",
        project_id
      )
    } else {
      # Create project
      my_project <- gitlab(
        req = "projects",
        name = project_name,
        namespace_id = namespace_id,
        default_branch = default_branch,
        initialize_with_readme = FALSE,
        verb = httr::POST,
        gitlab_con = gitlab_con
      )
      project_id <- my_project$id
      message("New project created: ", project_id)
    }
  } else {
    user_id <- gitlab(
      req = paste0("user"),
      verb = httr::GET,
      gitlab_con = gitlab_con
    ) %>%
      pull(id)

    user_projects <- gitlab(
      req = paste0("users/", user_id, "/projects"),
      verb = httr::GET,
      gitlab_con = gitlab_con
    )

    if (project_name %in% user_projects[["name"]]) {
      project_id <- filter(user_projects, name == project_name)[["id"]]

      message(
        "Project: \'",
        project_name,
        "\' already exists in your personal namespace",
        # filter(all_groups, id == namespace_id)[["name"]],
        ". ",
        "Using project_id: ",
        project_id
      )
    } else {
      # Create project
      my_project <- gitlab(
        req = "projects",
        name = project_name,
        namespace_id = NULL,
        default_branch = default_branch,
        initialize_with_readme = FALSE,
        verb = httr::POST,
        gitlab_con = gitlab_con
      )
      project_id <- my_project$id
      message("New project created: ", project_id)
    }
  }

  as.numeric(project_id)
}
