# WARNING - Generated by {fusen} from dev/flat_create_r_project_skeleton.Rmd: do not edit by hand

#' Transform project as book with lozen template
#'
#' @param project_path project_path
#' @param bookdown_path a path to a bookdown
#' @param css path(s) for css to copy
#' @param footer path for footer to copy
#' @param logo path for logo to copy
#' @param index path for index to copy
#' @param output_yml path for output_yml to copy

#'
#' @return Side Effect: Transform project as book
#' @export
#' @examples
#' withr::with_tempdir({
#'   project_path <- getwd()
#'   create_book_project(project_path)
#' })
create_book_project <- function(
  project_path,
  bookdown_path = system.file("lozendown", package = "lozen"),
  css = NULL,
  footer = NULL,
  logo = NULL,
  index = NULL,
  output_yml = NULL
    ) {
  old <- setwd(project_path)
  on.exit(setwd(old))

  all_files <- list.files(
    bookdown_path,
    full.names = TRUE,
    all.files = TRUE,
    no.. = TRUE
  )


  alldirs <- all_files[fs::is_dir(all_files)]
  purrr::walk(alldirs, ~ fs::dir_copy(.x, project_path))
  allfiles <- all_files[!fs::is_dir(all_files)]
  purrr::walk(allfiles, ~ fs::file_copy(.x, project_path))

  ## Add dev_history_book in "dev/"
  dev_path <- file.path(project_path, "dev")
  if (!file.exists(dev_path)) {
    dir.create(path = dev_path)
  }
  use_dev_history(path = project_path, type = c("book", "renv"))

  # ## Template HTML
  ## CSS
  if (!is.null(css)) {
    file.copy(from = css, to = project_path, overwrite = TRUE)
  }
  ## FOOTER
  if (!is.null(footer)) {
    file.copy(from = footer, to = project_path, overwrite = TRUE)
  }
  ## logo
  if (!is.null(logo)) {
    file.copy(from = logo, to = project_path, overwrite = TRUE)
  }

  # ## Modify index.Rmd
  if (!is.null(index)) {
    file.copy(
      index,
      "index.Rmd",
      overwrite = TRUE
    )
  }

  ## DESCRIPTION
  file_desc <- file.path(project_path, "DESCRIPTION")
  if (!file.exists(file_desc)) {
    fields <- c(list(Type = "Compendium"), usethis::use_description_defaults())
    desc <- desc::desc(text = glue::glue("{names(fields)}: {fields}"))
    desc$write(file_desc)
  }
  # Update content
  imports <- unique(c("bookdown", "knitr", attachment::att_from_rmds(".", recursive = FALSE)))
  attachment::att_to_desc_from_is(path.d = file_desc, imports = imports)

  ## Add _output.yml pour template lozen
  if (!is.null(output_yml)) {
    file.copy(
      output_yml,
      file.path(project_path, "_output.yml"),
      overwrite = TRUE
    )
  }

  ## Hide _book from git
  # gitignore
  add_git_ignore(c(
    "_book/",
    "*.log",
    "_main.tex",
    "*_files/",
    ".Rproj.user",
    ".Rhistory",
    "gitbook.*"
  ))

  message("book created")
  message("You need to follow \'dev_history_book.Rmd\' after that for the CI to create the pdf_book.")
  project_path
}
