# WARNING - Generated by {fusen} from dev/flat_manage_git.Rmd: do not edit by hand

#' Create branch production from master
#'
#' @param project_path project_path
#'
#' @return Side effect: New branch on the server
#' @export
#'
#' @examples
#' \dontrun{
#' create_production(
#'   project_path = project_path
#' )
#' }
create_production <- function(project_path) {
  gert::git_branch_create(branch = "production", repo = project_path)
  gert::git_push(repo = project_path)
  gert::git_pull(repo = project_path)
  # normal <- try(git2r::push(project_path, set_upstream = TRUE))
  # # gl_list_branches(project_id)
  # gl_create_branch(project = project_id, ref = "master", branch = "production")
  message("Branch named 'production' created")
}
