# WARNING - Generated by {fusen} from /dev/flat_deploy_connect.Rmd: do not edit by hand

#' @noRd
# This is an internal function to deploy on connect,
# it will be used by deploy_connect_shiny,deploy_connect_pkgdown and other functions
# that will be added later.
deploy_connect <- function(connect_url,
                           connect_user,
                           connect_api_token,
                           app_name,
                           app_primary_doc = NULL,
                           deploy_dir,
                           connect_name,
                           file_to_ignore_regex,
                           forceUpdate,
                           lint,
                           ...) {
  ## TODO
  # stop_missing <- function(x){
  #   if (missing(x)) {
  #
  #     name_param <- names(formals())
  #   stop(name_param, " is missing")
  #  }
  # }

  if (missing(connect_url)) {
    stop("connect_url is missing")
  }
  if (missing(connect_user)) {
    stop("connect_user is missing")
  }
  if (missing(connect_api_token)) {
    stop("connect_api_token is missing")
  }
  if (missing(app_name)) {
    stop("app_name is missing")
  }

  # app_name must not have punctuation to can be deploy

  message("old app_name:", app_name)
  app_name <- gsub(x = app_name, pattern = "\\.", replacement = "-")
  message("NEW app_name:", app_name)

  withr::with_options(
    # This option prevents the following error:
    # Error: The application directory contains more than 100000 files.
    c(
      "rsconnect.max.bundle.files" = 1e5
    ),
    {
      cli::cat_rule("Adding server")
      rsconnect::addServer(
        httr::modify_url(connect_url, path = "__api__"),
        name = connect_name
      )

      cli::cat_rule("Adding user")
      rsconnect::connectApiUser(
        account = connect_user,
        server = connect_name,
        apiKey = connect_api_token
      )

      appFiles <- list.files(
        deploy_dir,
        recursive = TRUE
      )
      appFiles <- appFiles[
        !grepl(
          file_to_ignore_regex,
          appFiles
        )
      ]

      cli::cat_rule("Deploying app")

      rsconnect::deployApp(
        appDir = deploy_dir,
        appName = app_name,
        appFiles = appFiles,
        appPrimaryDoc = app_primary_doc,
        account = connect_user,
        server = connect_name,
        forceUpdate = forceUpdate,
        lint = lint,
        ...
      )
    }
  )
}
