# WARNING - Generated by {fusen} from dev/flat_deploy_connect.Rmd: do not edit by hand

#' deploy_connect_bookdown
#'
#' Before using it, please follow these steps :
#'
#' - Ask the Mission Lead Dev for their deployment token on Connect, this is the one you will need to use.
#'
#' - Add the environment variables to your personal ".Renviron" to manually deploy to Connect:
#'   + Add `CONNECT_USER` with username.
#'   + Add `CONNECT_TOKEN` with the token.
#'   + Add `CONNECT_URL` with the connect url
#'
#'
#' @return used for side effects
#'
#' @param connect_url URL of the Connect server
#' @param connect_user User name to use to connect to the Connect server
#' @param connect_api_token API token to use to connect to the Connect server
#' @param app_name Name of the app to deploy
#' @param deploy_dir Directory to deploy
#' @param connect_name Name of the Connect server
#' @param file_to_ignore_regex Regex to use to ignore files
#' @param ... Other arguments to pass to rsconnect::deployApp
#' @inheritParams rsconnect::deployApp
#' @inheritParams rsconnect::deployApp
#'
#' @details
#' TODO
#'
#' @export
#' @examples
#' \dontrun{
#' if (
#'   Sys.getenv("CONNECT_URL") != "" &
#'     Sys.getenv("CONNECT_USER") != "" &
#'     Sys.getenv("CONNECT_TOKEN") != ""
#' ) {
#'   project_name <- "lozen-example-bookdown"
#'
#'   tmpdir <- tempfile(pattern = "book-")
#'   dir.create(tmpdir)
#'   project_path <- file.path(tmpdir, project_name)
#'
#'   bookdown::create_bs4_book(path = project_path)
#'
#'   bookdown::render_book(input = project_path)
#'
#'   deploy_connect_bookdown(
#'     app_name = project_name,
#'     deploy_dir = file.path(project_path, "_book")
#'   )
#' }
#' }
deploy_connect_bookdown <- function(
  connect_url = Sys.getenv("CONNECT_URL"),
  connect_user = Sys.getenv("CONNECT_USER"),
  connect_api_token = Sys.getenv("CONNECT_TOKEN"),
  app_name = NULL,
  deploy_dir = file.path(getwd(), "_book"),
  connect_name = Sys.getenv("CONNECT_NAME", unset = "connect"),
  file_to_ignore_regex = ".Rprofile$|^.Renviron$|renv/|rstudio_.*/|deliverables/|dev/|data-raw/|dockerfiles/",
  forceUpdate = FALSE,
  lint = FALSE,
  ...
    ) {
  cli::cat_bullet("Deploying the app on Connect")
  deploy_connect(
    connect_url = connect_url,
    connect_user = connect_user,
    connect_api_token = connect_api_token,
    app_name = app_name,
    deploy_dir = deploy_dir,
    connect_name = connect_name,
    file_to_ignore_regex = file_to_ignore_regex,
    forceUpdate = forceUpdate,
    lint = lint,
    ...
  )
}
