# WARNING - Generated by {fusen} from /dev/flat_deploy_connect.Rmd: do not edit by hand

#' detect the proper folder to deploy
#'
#'
#' @noRd
detect_deploy_dir <- function(deploy_dir = c(
                                file.path(getwd(), "public"),
                                file.path(getwd(), "docs"),
                                file.path(getwd(), "inst/site/"),
                                file.path(getwd(), ".")
                              )) {
  available <- deploy_dir[which(dir.exists(deploy_dir))]
  used <- available[1]

  message("available deploy_dir ", available)
  message("used deploy_dir ", used)

  return(used)
}
