# WARNING - Generated by {fusen} from /dev/flat_helper_testthat.Rmd: do not edit by hand

#' fetch_connect
#'
#' Fetch deployment status on Connect of a given app
#'
#' @param app_name character Name of the app to be fetched
#' @param connect_api_token character API token to enable access to Connect
#' @param connect_url character URL to Connect server
#'
#' @importFrom httr GET add_headers content status_code
#' @importFrom purrr map_df
#' @importFrom tibble tibble
#' @importFrom dplyr filter pull
#'
#' @return list A list containing the HTTP code status and the guid of the app
#'
#' @export
#' @examples
#' \dontrun{
#' fetch_connect(app_name = "my_app_name")
#' }
fetch_connect <- function(app_name,
                          connect_api_token = Sys.getenv("CONNECT_TOKEN"),
                          connect_url = Sys.getenv("CONNECT_URL")) {
  stopifnot("connect_api_token is missing" = isTRUE(connect_api_token != ""))
  stopifnot("connect_url is missing" = isTRUE(connect_url != ""))


  # Search Connect for content id
  result <- GET(
    sprintf(
      "%s/__api__/v1/content",
      connect_url
    ),
    add_headers(Authorization = paste("Key", connect_api_token))
  )

  # Search for app matching the input name
  selected_apps <- result |>
    content() |>
    purrr::map_df(
      ~ tibble::tibble(
        guid = .x$guid,
        name = .x$name,
      )
    ) |>
    dplyr::filter(
      name == app_name
    )

  # Return job fail if app is not found
  if (nrow(selected_apps) == 0) {
    message(sprintf("The app %s is not found on Connect server", app_name))
    return(
      list(
        "status" = "no app found",
        "guid" = ""
      )
    )
  } else {
    # Return HTTP request status if app is found
    app_guid <- selected_apps[1, ] %>%
      dplyr::pull(guid)

    result <- GET(
      sprintf(
        "%s/connect/#/apps/%s/access",
        connect_url,
        app_guid
      ),
      add_headers(Authorization = paste("Key", connect_api_token))
    )

    return(
      list(
        "status" = status_code(result),
        "guid" = app_guid
      )
    )
  }
}
