# WARNING - Generated by {fusen} from /dev/flat_create_special_issues.Rmd: do not edit by hand

#' Create the template for standard issue on gitlab
#'
#' @param project_path Path to the project
#' @param language Language. Should be one of 'fr' or 'en'
#' @param type Verbosity of comments in the template. Should be 'full' or 'light'.
#'
#' @importFrom glue glue
#'
#' @return Side effect: create the template
#' @export
#' @examples
#' # Try with a temp project
#' ## Create temp dir and file
#' project_path <- tempfile("myproject")
#' dir.create(project_path)
#' 
#' ## Add the full template in french
#' gh_add_template_issue(project_path, language = "fr", type = "full")
#' 
#' ## Add the full template in english
#' gh_add_template_issue(project_path, language = "en", type = "full")
#' 
#' ## Add the light template in french
#' gh_add_template_issue(project_path, language = "fr", type = "light")
#' 
#' ## Add the light template in english
#' gh_add_template_issue(project_path, language = "en", type = "light")
#' 
#' # suppress tmp folder
#' unlink(project_path, recursive = TRUE)
gh_add_template_issue <- function(
  project_path = ".",
  language = c("fr", "en"),
  type = c("full", "light")
    ) {
  old <- setwd(project_path)
  on.exit(setwd(old))

  language <- match.arg(language, several.ok = FALSE)
  type <- match.arg(type, several.ok = FALSE)

  github_path <- file.path(project_path, ".github")

  if (!dir.exists(github_path)) {
    dir.create(github_path)
    add_build_ignore(".github")
    add_git_ignore("!.github/*/*")
  }

  if (!dir.exists(file.path(github_path, "ISSUE_TEMPLATE"))) {
    dir.create(file.path(github_path, "ISSUE_TEMPLATE"))
  }

  # Find the name of the file
  name_file <- glue("template_issues_{type}_{language}.md")

  # Define template name
  if (type == "light") {
    name_template_in_gh <- glue("Light template issue.md")
  } else if (type == "full") {
    name_template_in_gh <- glue("Template issue.md")
  }

  # Add the template
  file.copy(
    system.file("github", "issue_templates", name_file, package = "lozen"),
    file.path(github_path, "ISSUE_TEMPLATE", name_template_in_gh),
    overwrite = TRUE,
    recursive = FALSE
  )

  message("Issue template added, find it when creating a new issue on the graphical interface")
}
