# WARNING - Generated by {fusen} from dev/flat_create_weekly.Rmd: do not edit by hand

#' Create a weekly issues summary for GitHub
#'
#' @param date_min Minimal date to look for issues
#' @param date_max Maximal date to look for issues
#' @param user username or company name as shown on GitHub
#' @param repo GitHub repository
#' @param board_url url of the GitHub board. If using the "classic" board, which is deprecated by GitHub, you may want to use this url: `glue("/repos/{user}/{repo}/projects")`
#' @param verbose Logical. Whether to return output in the console too.
#'
#' @importFrom lubridate as_date as_datetime format_ISO8601 now
#' @importFrom dplyr select mutate filter rename any_of bind_rows
#' @importFrom purrr map_dfr map_lgl
#' @importFrom gh gh
#' @importFrom glue glue
#' @importFrom gitlabr multilist_to_tibble

#' @return A Weekly to copy-paste in a Wiki and a tibble
#'
#' @export
#' @examples
#' \dontrun{
#' if (Sys.getenv("GITHUB_PAT") != "") {
#'   user <- "ThinkR-open"
#'   repo <- "example-weekly"
#'   weekly <- gh_create_weekly(
#'     date_min = "2022-06-30",
#'     date_max = "2022-06-30",
#'     user = user,
#'     repo = repo,
#'     board_url = glue::glue("/repos/{user}/{repo}/projects")
#'   )
#' }
#' }
#' # Copier dans le presse papier pour copier directement
#' # clipr::write_clip(weekly$weekly_info)
gh_create_weekly <- function(date_min = Sys.Date() - 7,
                             date_max = Sys.Date(),
                             user = "thinkr-open",
                             repo = "fusen",
                             verbose = FALSE,
                             board_url) {
  .Deprecated("lozen::gh_create_weekly_old_and_new_boards()")

  date_min <- as_date(date_min)
  date_max <- as_date(date_max)

  if (date_max < date_min) {
    stop("date_min should be lower or equal to date_max")
  }


  # Github Projects
  # >> Classic URL: glue("/repos/{user}/{repo}/projects")
  board <- gh(board_url, state = "open", per_page = 100)
  board_tbl <- multilist_to_tibble(board)
  # Get the first
  board_tbl$id[1]

  # GitHub columns of a project
  project_id <- board_tbl$id[1]
  # >> Change here for new board
  columns <- gh(glue("/projects/{project_id}/columns"), per_page = 100)
  # <<<
  columns_tbl <- multilist_to_tibble(columns)
  columns_tbl$name

  # 1 - Cards from a column - Realised
  the_column <- grep("close|closed|a valider|validation|done", tolower(columns_tbl$name))
  column_id <- columns_tbl$id[the_column]
  cards_tbl_done <- map_dfr(
    column_id,
    # >> Change here for new board
    ~ gh(glue("/projects/columns/{.x}/cards"), per_page = 100) %>%
      # <<
      multilist_to_tibble()
  )
  if (nrow(cards_tbl_done) != 0) {
    cards_tbl_done <- cards_tbl_done %>%
      mutate(info = "1 - :heavy_check_mark: Realised") %>%
      filter(
        as_date(as_datetime(updated_at)) >= date_min,
        as_date(as_datetime(updated_at)) <= date_max
      )
  }

  # 2 - Cards from a column - Blocked
  the_column <- grep("blocked|bloque|bloqu\\\\u00e9", stringi::stri_escape_unicode(tolower(columns_tbl$name)))
  column_id <- columns_tbl$id[the_column]
  cards_tbl_blocked <- map_dfr(
    column_id,
    # >> Change here for new board
    ~ gh(glue("/projects/columns/{.x}/cards"), per_page = 100) %>%
      # <<
      multilist_to_tibble()
  )
  if (nrow(cards_tbl_blocked) != 0) {
    cards_tbl_blocked <- cards_tbl_blocked %>%
      mutate(info = "2 - :stop_sign: Blocked")
  }


  # 3 - Cards from a column - Validation
  the_column <- grep("a valider|validation", tolower(columns_tbl$name))
  column_id <- columns_tbl$id[the_column]
  cards_tbl_valid <- map_dfr(
    column_id,
    # >> Change here for new board
    ~ gh(glue("/projects/columns/{.x}/cards"), per_page = 100) %>%
      # <<<
      multilist_to_tibble()
  )
  if (nrow(cards_tbl_valid) != 0) {
    cards_tbl_valid <- cards_tbl_valid %>%
      mutate(info = "3 - :thumbsup: To validate")
  }

  # 4 - Cards from a column - En cours/Review
  the_column <- grep("in progress|en cours|review|revision|r\\\\u00e9vision", stringi::stri_escape_unicode(tolower(columns_tbl$name)))
  column_id <- columns_tbl$id[the_column]
  cards_tbl_progress <- map_dfr(
    column_id,
    # >> Change here for new board
    ~ gh(glue("/projects/columns/{.x}/cards"), per_page = 100) %>%
      # <<
      multilist_to_tibble()
  )
  if (nrow(cards_tbl_progress) != 0) {
    cards_tbl_progress <- cards_tbl_progress %>%
      mutate(info = "4 - :spiral_notepad: In progress") %>%
      filter(as_date(as_datetime(updated_at)) <= date_max)
  }


  # New issues opened during the week (even if closed)
  # >> DO NOT Change here for new board
  new_issues <- gh(glue("/repos/{user}/{repo}/issues"),
    sort = "created", since = format_ISO8601(
      as_datetime(paste0(date_min, "T00:00:01"),
        tz = lubridate::tz(now())
      ),
      usetz = TRUE
    ),
    state = "all"
  )

  new_issues_all_tbl <- multilist_to_tibble(new_issues)
  # Remove PR as they are listed as issues
  if (any(grepl("pull_request", names(new_issues_all_tbl)))) {
    new_issues_all_tbl <- new_issues_all_tbl %>%
      filter(map_lgl(.[["pull_request"]], is.null))
  }

  if (nrow(new_issues_all_tbl) != 0) {
    new_issues_tbl <- new_issues_all_tbl %>%
      filter(
        as_date(as_datetime(created_at)) >= date_min,
        as_date(as_datetime(created_at)) <= date_max
      ) %>%
      rename(content_url = url) %>%
      select(any_of(
        unique(c(
          "state",
          names(cards_tbl_blocked),
          names(cards_tbl_progress),
          names(cards_tbl_valid),
          names(cards_tbl_done)
        ))
      )) %>%
      mutate(info = "9 - :seedling: New issues opened")
  } else {
    new_issues_tbl <- new_issues_all_tbl
  }

  # Combine cards ----
  list_all_cards <- list(
    cards_tbl_blocked,
    cards_tbl_progress,
    cards_tbl_valid,
    cards_tbl_done,
    new_issues_tbl
  )

  card_is_full <- purrr::map_lgl(list_all_cards, ~ nrow(.x) != 0)
  all_cards_weekly <- bind_rows(list_all_cards[card_is_full])


  # create_issue_li_gh(glue("/repos/{user}/{repo}/issues/1"))

  all_cards_weekly_text <- all_cards_weekly %>%
    mutate(
      issue_get = gsub("https://api.github.com", "", content_url),
      issue_li = create_issue_li_gh(issue_get)
    )

  all_cards_weekly_text_collapse <- collapse_li(all_cards_weekly_text)

  out <- list(
    weekly_issues = all_cards_weekly_text,
    weekly_info = all_cards_weekly_text_collapse$text_weekly_all
  )

  if (verbose) {
    cat(out$weekly_info)
  }
  return(out)
}

#' Get issue title for GitHub
#' @noRd
create_issue_li_gh <- function(issues_get) {
  purrr::map_chr(issues_get, create_one_issue_li_gh)
}

#' Get one issue title for GitHub
#' @noRd
create_one_issue_li_gh <- function(issue_get) {
  issue <- gh(issue_get, per_page = 100)
  issue_tbl <- multilist_to_tibble(issue)
  login <- purrr::map_chr(issue_tbl$assignee, ~ ifelse(length(.x) == 1, "Not assigned", paste0("@", .x[["login"]])))
  glue("- {issue_tbl$title}: [issue {issue_tbl$number}{ifelse(issue_tbl$state == \'closed\', \' (closed)\', \'\')}]({issue_tbl$html_url}) - {login}")
}


#' Combine issues li list
#' @noRd
collapse_li <- function(x) {
  x %>%
    group_by(info) %>%
    summarise(
      text_weekly = paste(issue_li, collapse = "\n")
    ) %>%
    summarise(
      text_weekly_all = paste(
        paste0(info, "\n\n", text_weekly),
        collapse = "\n\n\n"
      )
    )
}
