# WARNING - Generated by {fusen} from dev/flat_create_weekly.Rmd: do not edit by hand

#' Create a weekly issues summary for GitHub
#'
#' @param date_min Minimal date to look for issues
#' @param date_max Maximal date to look for issues
#' @param user username or company name as shown on GitHub
#' @param repo GitHub repository
#' @param board_url url of the GitHub board. If using the "classic" board, which is deprecated by GitHub, you may want to use this url: `glue("/repos/{user}/{repo}/projects")`
#' otherwise you may want to use this kind of url: `"https://github.com/orgs/myorganization/projects/someprojectnumber/" `
#' Please not this not mandatory if you are setting `new_board = FALSE` since `board_url` can be guessed from `user` and `repo`
#' @param new_board logical. Are you working with the classic board or the new board.
#' @param regex_validation Regular expression to detect labels for issues waiting for validation
#' @param regex_done Regular expression to detect labels for issues done by developers (and potentially awaiting validation by clients)
#' @param regex_blocked Regular expression to detect labels for issues blocked (and potentially awaiting information by clients)
#' @param regex_inprogress Regular expression to detect labels for issues in progress (and potentially awaiting review by lead dev.)
#' @param regex_ready Regular expression to detect labels for issues ready (and potentially reorder by lead dev.)
#' @param github_token token access to github API (read:project scope is required for the new github board).
#' @param verbose Logical. Whether to return output in the console too.
#'
#' @importFrom lubridate as_date as_datetime format_ISO8601 now
#' @importFrom dplyr select mutate filter rename any_of bind_rows inner_join
#' @importFrom purrr map_dfr map_lgl
#' @importFrom gh gh
#' @importFrom glue glue
#' @importFrom gitlabr multilist_to_tibble
#'

#' @return A Weekly to copy-paste in a Wiki and a tibble
#'
#' @export
#'
#' @examples
#' \dontrun{
#' user <- "ThinkR-open"
#' repo <- "example-weekly"
#' date_min <- "2022-06-30"
#' date_max <- "2022-06-30"
#' board_url_old <- glue::glue("/repos/{user}/{repo}/projects")
#' board_url_new <- "https://github.com/orgs/ThinkR-open/projects/4/"
#' 
#' # old board
#' weekly_old <- gh_create_weekly_old_and_new_boards(
#'   date_min = date_min,
#'   date_max = date_max,
#'   user = user,
#'   repo = repo,
#'   board_url = board_url_old,
#'   new_board = FALSE,
#'   verbose = FALSE
#' )
#' cat(weekly_old$weekly_info)
#' 
#' # clipr::write_clip(weekly_old$weekly_info)
#' 
#' 
#' # new board
#' weekly_new <- gh_create_weekly_old_and_new_boards(
#'   date_min = date_min,
#'   date_max = date_max,
#'   user = user,
#'   repo = repo,
#'   board_url = board_url_new,
#'   github_token = Sys.getenv("GITHUB_PAT"),
#'   new_board = TRUE,
#'   verbose = FALSE
#' )
#' cat(weekly_new$weekly_info)
#' # clipr::write_clip(weekly_new$weekly_info)
#' 
#' }

gh_create_weekly_old_and_new_boards <- function(date_min,
                                                date_max,
                                                user,
                                                repo,
                                                board_url,
                                                new_board = TRUE,
                                                regex_done = "close|closed|done",
                                                regex_validation = "a valider|validation",
                                                regex_blocked = "blocked|bloque|bloqu\\\\u00e9",
                                                regex_inprogress = "in progress|en cours|review|revision|r\\\\u00e9vision|r\\\\u00e9-validation",
                                                regex_ready = "ready|pret|pr\\\\u00eat",
                                                github_token = Sys.getenv("GITHUB_PAT"),
                                                verbose = FALSE) {
  word_to_validate <- "Realised and to validate"
  word_realised <- "Realised and validated"
  word_blocked <- "Blocked"
  word_in_progress <- "In progress"
  word_new_issues <- "New issues opened"
  word_ready <- "Ready"

  date_min <- as_date(date_min)
  date_max <- as_date(date_max)

  if (date_max < date_min) {
    stop("date_min should be lower or equal to date_max")
  }

  # get GH board
  if (new_board) {
    if (!grepl("^http", board_url)) {
      stop("board_url with `new_board = TRUE` should be a real URL that works in your browser, starting with http(s)://")
    }
    if (!grepl("/orgs/|/users/", board_url)) {
      stop("board_url does not seem to be a new board type. It should be created at the scale of the user or the organization. Otherwise, it may be a classic board, which requires to define `new_board = FALSE`")
    }
    board_tbl <- graphql_to_tibble(
      board_url = board_url,
      github_token = github_token
    )
  } else {
    if (missing(board_url)) {
      board_url <- glue::glue("/repos/{user}/{repo}/projects")
      message(paste0("`board_url` is guessed from `user` and `repo` as you specified `new_board = FALSE`: ", board_url))
    }
    if (!grepl("^/repos", board_url)) {
      stop("board_url should be like '/repos/{user}/{repo}/projects' as you specified `new_board = FALSE`. You can also keep it empty, it will be built automatically")
    }
    board <- gh(board_url, state = "open", per_page = 100)
    board_tbl <- multilist_to_tibble(board)
  }


  if (nrow(board_tbl) == 0) {
    stop("The board of the project is empty")
  }

  # Retrieve all issues
  all_issues <- gh(glue("/repos/{user}/{repo}/issues"), state = "all")
  all_issues_tbl <- multilist_to_tibble(all_issues)

  #####################
  # NEW PROJECT BOARD #
  #####################

  if (new_board) {
    board_tbl <- board_tbl %>%
      rename(
        content_url = url,
        created_at = createdAt,
        updated_at = updatedAt,
        closed_at = closedAt
      ) %>%
      mutate(state = tolower(state)) %>%
      select(-id) %>%
      mutate(content_url = gsub(content_url,
        pattern = "https://github.com",
        replacement = "https://api.github.com/repos"
      ))

    # Board columns names
    board_tbl$board_column

    # 2 - Cards from a column - Blocked
    cards_tbl_blocked <- board_tbl %>%
      filter(grepl(regex_blocked, stringi::stri_escape_unicode(tolower(board_column))) &
        state == "open")

    if (nrow(cards_tbl_blocked) != 0) {
      cards_tbl_blocked <- inner_join(cards_tbl_blocked,
        select(all_issues_tbl, id, number, assignees),
        by = "number"
      )

      cards_tbl_blocked <- cards_tbl_blocked %>%
        # mutate(info = "2 - :stop_sign: Blocked")
        mutate(info = paste("__2__:stop_sign:", word_blocked))
    }

    # 4 - Cards from a column - En cours/Review

    cards_tbl_progress <- board_tbl %>%
      filter(
        grepl(regex_inprogress, stringi::stri_escape_unicode(tolower(board_column))) &
          state == "open" &
          as_date(as_datetime(created_at)) <= date_max
      )

    if (nrow(cards_tbl_progress) != 0) {
      cards_tbl_progress <- inner_join(cards_tbl_progress,
        select(all_issues_tbl, id, number, assignees),
        by = "number"
      )
      cards_tbl_progress <- cards_tbl_progress %>%
        mutate(info = paste("__4__:spiral_notepad:", word_in_progress))
    }

    # 3 - Cards from a column - Validation
    cards_tbl_valid <- board_tbl %>%
      filter(
        grepl(regex_validation, stringi::stri_escape_unicode(tolower(board_column))) &
          state == "open"
      )

    if (nrow(cards_tbl_valid) != 0) {
      cards_tbl_valid <- inner_join(cards_tbl_valid,
        select(all_issues_tbl, id, number, assignees),
        by = "number"
      )

      cards_tbl_valid <- cards_tbl_valid %>%
        mutate(info = paste("__3__:thumbsup:", word_to_validate))
    }


    # 5 - Cards from a column - Pret/Ready

    cards_tbl_ready <- board_tbl %>%
      filter(
        grepl(regex_ready, stringi::stri_escape_unicode(tolower(board_column))) &
          state == "open"
      )

    if (nrow(cards_tbl_ready) != 0) {
      cards_tbl_ready <- inner_join(cards_tbl_ready,
        select(all_issues_tbl, id, number, assignees),
        by = "number"
      )

      cards_tbl_ready <- cards_tbl_ready %>%
        mutate(info = paste("__5__:thumbsup:", word_ready))
    }

    # 1 - Cards from a column - Done - Will get Validation later in duplicates
    cards_tbl_done_closed <- board_tbl %>%
      filter(
        as_date(as_datetime(closed_at)) >= date_min &
          state == "closed"
      )

    cards_tbl_done_open <- board_tbl %>%
      filter(
        grepl(regex_done, stringi::stri_escape_unicode(tolower(board_column))) &
          state == "open" &
          as_date(as_datetime(closed_at)) >= date_min &
          as_date(as_datetime(closed_at)) <= date_max
      )

    cards_tbl_done <- bind_rows(
      cards_tbl_done_closed,
      cards_tbl_done_open
    )

    if (nrow(cards_tbl_done) != 0) {
      cards_tbl_done <- inner_join(cards_tbl_done,
        select(all_issues_tbl, id, number, assignees),
        by = "number"
      )

      cards_tbl_done <- cards_tbl_done %>%
        mutate(info = paste("__1__:white_check_mark:", word_realised))
    }

    #####################
    # OLD PROJECT BOARD #
    #####################
  } else {
    project_id <- board_tbl$id[1]
    columns <- gh(glue("/projects/{project_id}/columns"), per_page = 100)

    columns_tbl <- multilist_to_tibble(columns)

    columns_tbl$name

    # 2 - Cards from a column - Blocked
    the_column <- grep(regex_blocked, stringi::stri_escape_unicode(tolower(columns_tbl$name)))
    column_id <- columns_tbl$id[the_column]
    cards_tbl_blocked <- map_dfr(
      column_id,
      ~ gh(glue("/projects/columns/{.x}/cards"), per_page = 100) %>%
        multilist_to_tibble()
    )


    if (nrow(cards_tbl_blocked) != 0) {
      cards_tbl_blocked <- cards_tbl_blocked %>%
        mutate(issue_number = as.numeric(
          gsub(content_url,
            pattern = glue("https://api.github.com/repos/{user}/{repo}/issues/"),
            replacement = ""
          )
        )) %>%
        inner_join(., select(all_issues_tbl, number, state), by = c("issue_number" = "number"))

      cards_tbl_blocked <- cards_tbl_blocked %>%
        mutate(info = paste("__2__:stop_sign:", word_blocked)) %>%
        filter(state == "open")
    }

    # 4 - Cards from a column - En cours/Review
    the_column <- grep(regex_inprogress, stringi::stri_escape_unicode(tolower(columns_tbl$name)))
    column_id <- columns_tbl$id[the_column]
    cards_tbl_progress <- map_dfr(
      column_id,
      ~ gh(glue("/projects/columns/{.x}/cards"), per_page = 100) %>%
        multilist_to_tibble()
    )


    if (nrow(cards_tbl_progress) != 0) {
      cards_tbl_progress <- cards_tbl_progress %>%
        mutate(issue_number = as.numeric(
          gsub(content_url,
            pattern = glue("https://api.github.com/repos/{user}/{repo}/issues/"),
            replacement = ""
          )
        )) %>%
        inner_join(., select(all_issues_tbl, number, state), by = c("issue_number" = "number"))

      cards_tbl_progress <- cards_tbl_progress %>%
        mutate(info = paste("__4__:spiral_notepad:", word_in_progress)) %>%
        filter(
          state == "open" &
            as_date(as_datetime(created_at)) <= date_max
        )
    }


    # 3 - Cards from a column - Validation
    the_column <- grep(regex_validation, stringi::stri_escape_unicode(tolower(columns_tbl$name)))
    column_id <- columns_tbl$id[the_column]
    cards_tbl_valid <- map_dfr(
      column_id,
      ~ gh(glue("/projects/columns/{.x}/cards"), per_page = 100) %>%
        multilist_to_tibble()
    )
    if (nrow(cards_tbl_valid) != 0) {
      cards_tbl_valid <- cards_tbl_valid %>%
        mutate(issue_number = as.numeric(
          gsub(content_url,
            pattern = glue("https://api.github.com/repos/{user}/{repo}/issues/"),
            replacement = ""
          )
        )) %>%
        inner_join(., select(all_issues_tbl, number, state), by = c("issue_number" = "number"))

      cards_tbl_valid <- cards_tbl_valid %>%
        mutate(info = paste("__3__:thumbsup:", word_to_validate)) %>%
        filter(state == "open")
    }


    # 5 - Cards from a column - Pret/Ready
    the_column <- grep(regex_ready, stringi::stri_escape_unicode(tolower(columns_tbl$name)))
    column_id <- columns_tbl$id[the_column]
    cards_tbl_ready <- map_dfr(
      column_id,
      ~ gh(glue("/projects/columns/{.x}/cards"), per_page = 100) %>%
        multilist_to_tibble()
    )


    if (nrow(cards_tbl_ready) != 0) {
      cards_tbl_ready <- cards_tbl_ready %>%
        mutate(issue_number = as.numeric(
          gsub(content_url,
            pattern = glue("https://api.github.com/repos/{user}/{repo}/issues/"),
            replacement = ""
          )
        )) %>%
        inner_join(., select(all_issues_tbl, number, state), by = c("issue_number" = "number"))



      cards_tbl_ready <- cards_tbl_ready %>%
        mutate(info = paste("__5__:thumbsup:", word_ready)) %>%
        filter(state == "open")
    }


    # 1 - Cards from a column - Done - Will get Validation later in duplicates

    cards_tbl_done_closed <- map_dfr(
      columns_tbl$id,
      ~ gh(glue("/projects/columns/{.x}/cards"), per_page = 100) %>%
        multilist_to_tibble()
    )

    if (nrow(cards_tbl_done_closed) != 0) {
      cards_tbl_done_closed <- cards_tbl_done_closed %>%
        mutate(issue_number = as.numeric(
          gsub(content_url,
            pattern = glue("https://api.github.com/repos/{user}/{repo}/issues/"),
            replacement = ""
          )
        )) %>%
        inner_join(., select(all_issues_tbl, number, state, closed_at), by = c("issue_number" = "number"))

      cards_tbl_done_closed <- cards_tbl_done_closed %>%
        mutate(info = paste("__1__:white_check_mark:", word_realised)) %>%
        filter(
          as_date(as_datetime(closed_at)) >= date_min &
            state == "closed"
        )
    }



    the_column <- grep(regex_done, stringi::stri_escape_unicode(tolower(columns_tbl$name)))
    column_id <- columns_tbl$id[the_column]
    cards_tbl_done_open <- map_dfr(
      column_id,
      ~ gh(glue("/projects/columns/{.x}/cards"), per_page = 100) %>%
        multilist_to_tibble()
    )

    if (nrow(cards_tbl_done_open) != 0) {
      cards_tbl_done_open <- cards_tbl_done_open %>%
        mutate(issue_number = as.numeric(
          gsub(content_url,
            pattern = glue("https://api.github.com/repos/{user}/{repo}/issues/"),
            replacement = ""
          )
        )) %>%
        inner_join(., select(all_issues_tbl, number, state, closed_at), by = c("issue_number" = "number"))

      cards_tbl_done_open <- cards_tbl_done_open %>%
        mutate(info = paste("__1__:white_check_mark:", word_realised)) %>%
        filter(state == "open" &
          as_date(as_datetime(closed_at)) >= date_min &
          as_date(as_datetime(closed_at)) <= date_max)
    }
    cards_tbl_done <- bind_rows(
      cards_tbl_done_closed,
      cards_tbl_done_open
    )
  }

  # New issues opened during the week (even if closed)
  new_issues <- gh(glue("/repos/{user}/{repo}/issues"),
    sort = "created", since = format_ISO8601(
      as_datetime(paste0(date_min, "T00:00:01"),
        tz = lubridate::tz(now())
      ),
      usetz = TRUE
    ),
    state = "all"
  )

  new_issues_all_tbl <- multilist_to_tibble(new_issues)
  # Remove PR as they are listed as issues
  if (any(grepl("pull_request", names(new_issues_all_tbl)))) {
    new_issues_all_tbl <- new_issues_all_tbl %>%
      filter(map_lgl(.[["pull_request"]], is.null))
  }

  if (nrow(new_issues_all_tbl) != 0) {
    new_issues_tbl <- new_issues_all_tbl %>%
      filter(
        as_date(as_datetime(created_at)) >= date_min,
        as_date(as_datetime(created_at)) <= date_max
      ) %>%
      rename(content_url = url) %>%
      select(any_of(
        unique(c(
          "state",
          names(cards_tbl_blocked),
          names(cards_tbl_progress),
          names(cards_tbl_valid),
          names(cards_tbl_ready),
          names(cards_tbl_done)
        ))
      )) %>%
      mutate(info = "__9__:seedling: New issues opened")
  } else {
    new_issues_tbl <- new_issues_all_tbl
  }

  # Combine cards ----
  list_all_cards <- list(
    cards_tbl_blocked,
    cards_tbl_progress,
    cards_tbl_valid,
    cards_tbl_ready,
    cards_tbl_done,
    new_issues_tbl
  )

  card_is_full <- purrr::map_lgl(list_all_cards, ~ nrow(.x) != 0)
  all_cards_weekly <- bind_rows(list_all_cards[card_is_full])

  if (nrow(all_cards_weekly) == 0) {
    stop("There is nothing to report in the weekly")
  }

  all_cards_weekly_text <- all_cards_weekly %>%
    mutate(
      issue_get = gsub("https://api.github.com", "", content_url),
      issue_li = create_issue_li_gh(issue_get)
    )

  all_cards_weekly_text_collapse <-
    collapse_li(all_cards_weekly_text) %>%
    mutate(
      text_weekly_all = gsub(
        text_weekly_all,
        pattern = "__\\d{1,1}__",
        replacement = ""
      )
    )

  out <- list(
    weekly_issues = all_cards_weekly_text,
    weekly_info = all_cards_weekly_text_collapse$text_weekly_all
  )

  if (verbose) {
    cat(out$weekly_info)
  }
  return(out)
}
