# WARNING - Generated by {fusen} from dev/flat_create_special_issues.Rmd: do not edit by hand

#' Create the template for standard issue on gitlab
#'
#' @param project_path Path to the project
#' @param language Language. Should be one of 'fr' or 'en'
#' @param type Verbosity of comments in the template. Should be 'full' or 'light'.
#'
#' @importFrom glue glue
#'
#' @return Side effect: create the template
#' @export
#' @examples
#' # Try with a temp project
#' ## Create temp dir and file
#' project_path <- tempfile("myproject")
#' dir.create(project_path)
#'
#' ## Add the template in full french
#' gl_add_template_issue(project_path, language = "fr", type = "full")
#'
#' ## Add the template in full english
#' gl_add_template_issue(project_path, language = "en", type = "full")
#'
#' ## Add the template in light french
#' gl_add_template_issue(project_path, language = "fr", type = "light")
#'
#' ## Add the template in light english
#' gl_add_template_issue(project_path, language = "en", type = "light")
#'
#' # Suppress tmp folder
#' unlink(project_path, recursive = TRUE)
gl_add_template_issue <- function(
  project_path = ".",
  language = c("fr", "en"),
  type = c("full", "light")
    ) {
  old <- setwd(project_path)
  on.exit(setwd(old))

  language <- match.arg(language, several.ok = FALSE)
  type <- match.arg(type, several.ok = FALSE)

  gitlab_path <- file.path(project_path, ".gitlab")

  if (!dir.exists(gitlab_path)) {
    dir.create(gitlab_path)
    add_build_ignore(".gitlab")
    add_git_ignore("!.gitlab/*/*")
  }

  if (!dir.exists(file.path(gitlab_path, "issue_templates"))) {
    dir.create(file.path(gitlab_path, "issue_templates"))
  }

  # Find the name of the file
  name_file <- glue("template_issues_{type}_{language}.md")

  # Define template name
  if (type == "light") {
    name_template_in_gl <- glue("Light template issue.md")
  } else if (type == "full") {
    name_template_in_gl <- glue("Template issue.md")
  }

  # Add the template
  file.copy(
    system.file("gitlab", "issue_templates", name_file, package = "lozen"),
    file.path(gitlab_path, "issue_templates", name_template_in_gl),
    overwrite = TRUE,
    recursive = FALSE
  )

  message("Issue template added, find it when creating a new issue on the graphical interface")
}
