# WARNING - Generated by {fusen} from dev/flat_create_weekly.Rmd: do not edit by hand

#' Create a Weekly/Daily summary of what happened in your GitLab Board
#'
#'
#' @param project_id Id of the GitLab project
#' @param date_min Minimal date to search from. The oldest date.
#' @param date_max Maximal date to search to. The more recent date.
#' @param language Character. Language: 'fr' ou 'en'.
#' @param gitlab_url URL of the GitLab Forge
#' @param private_token Your private GitLab instance token allowed to use the "api".
#' @param verbose Logical. Whether to show the outputs in the console.
#' @param regex_validation Regular expression to detect labels for issues waiting for validation
#' @param regex_done Regular expression to detect labels for issues done by developers (and potentially awaiting validation by clients)
#' @param regex_blocked Regular expression to detect labels for issues blocked (and potentially awaiting information by clients)
#' @param regex_inprogress Regular expression to detect labels for issues in progress (and potentially awaiting review by lead dev.)
#' @param regex_ready Regular expression to detect labels for issues ready (and potentially reorder by lead dev.)
#' @param daily Logical. Create the daily issues summary for GitLab
#' @param date_daily Date to search from.
#' @param max_page_opened a numeric. The maximum number of pages to retrieve for open issues. Defaults to 10.
#' @param max_page_closed a numeric. The maximum number of pages to retrieve for close issues. Defaults to 5.
#' @importFrom gitlabr gl_connection set_gitlab_connection gl_list_issues gl_get_project
#' @importFrom dplyr bind_rows rowwise mutate starts_with case_when filter arrange pull ungroup c_across summarise group_by left_join
#' @importFrom glue glue
#' @importFrom lubridate as_date
#' @importFrom stats na.omit
#' @importFrom stringr str_remove_all str_c
#' @importFrom stringi stri_escape_unicode
#' @importFrom purrr map
#' @return A Weekly to copy-paste in a Wiki and a tibble
#'
#' @export
gl_create_weekly <- function(
  project_id,
  date_min = Sys.Date() - 7,
  date_max = Sys.Date(),
  language = c("fr", "en"),
  gitlab_url = Sys.getenv("GITLAB_URL", unset = "https://gitlab.com"),
  private_token = Sys.getenv("GITLAB_TOKEN"),
  verbose = FALSE,
  regex_done = "close|closed|done",
  regex_validation = "a valider|validation",
  regex_blocked = "blocked|bloque|bloqu\\\\u00e9",
  regex_inprogress = "in progress|en cours|review|revision|r\\\\u00e9vision|r\\\\u00e9-validation",
  regex_ready = "ready|pret|pr\\\\u00eat",
  daily = FALSE,
  date_daily = Sys.Date(),
  max_page_opened = 10,
  max_page_closed = 5
    ) {
  if (isFALSE(is.numeric(max_page_opened)) | isFALSE(max_page_opened >= 1)) {
    stop("max_page_opened should be upper or equal to 1")
  }

  if (isFALSE(is.numeric(max_page_closed)) | isFALSE(max_page_closed >= 1)) {
    stop("max_page_closed should be upper or equal to 1")
  }

  if (isTRUE(daily)) {
    date_daily <- as_date(date_daily)
    date_min <- date_daily
    date_max <- date_min + 1
  }

  date_min <- as_date(date_min)
  date_max <- as_date(date_max)

  if (date_max < date_min) {
    stop("date_min should be lower or equal to date_max")
  }

  if (private_token == "") {
    stop("Please specify your private_token. This may be an environment variable named GITLAB_TOKEN")
  }

  # Language
  language <- match.arg(
    language,
    several.ok = FALSE
  )

  if (language == "fr") {
    word_to_validate <- "R\u00e9alis\u00e9 et \u00e0 valider"
    word_to_validate_daily <- "Tout frais fait du jour et \u00e0 valider"
    word_realised <- "R\u00e9alis\u00e9 et valid\u00e9"
    word_realised_daily <- "Tout frais fait du jour et valid\u00e9"
    word_blocked <- "Bloqu\u00e9"
    word_blocked_daily <- "Bloqu\u00e9, besoin de votre retour"
    word_in_progress <- "En cours"
    word_in_progress_daily <- "En cours, \u00e0 garder au chaud pour la prochaine fois"
    word_in_progress_alert_daily <- "\u00c7a commence \u00e0 \u00eatre compliqu\u00e9 par ici, on va devoir r\u00e9-ajuster les priorit\u00e9s ou les besoins\n\n"
    word_new_issues <- "Nouvelles issues ouvertes"
    word_new_issues_daily <- "Les nouveaux tickets du jour"
    word_ready <- "Pr\u00eat"
    word_ready_daily <- "Les prochains sur la liste"
    next_date <- "La prochaine date : (A remplir)"
    last_weekly <- "Pour rappel, lien vers le Weekly pr\u00e9c\u00e9dent :"
  } else if (language == "en") {
    word_to_validate <- "Realised and to validate"
    word_to_validate_daily <- "Freshly made of day and to validate"
    word_realised <- "Realised and validated"
    word_realised_daily <- "Freshly made of day and validated"
    word_blocked <- "Blocked"
    word_blocked_daily <- "Blocked, need your feedback"
    word_in_progress <- "In progress"
    word_in_progress_daily <- "In progress, to keep warm for the next time"
    word_in_progress_alert_daily <- "It s getting complicated around here, we will have to readjust the priorities or needs\n\n"
    word_new_issues <- "New issues opened"
    word_new_issues_daily <- "The new tickets of the day"
    word_ready <- "Ready"
    word_ready_daily <- "Next on the list"
    next_date <- "The next date: (to complete)"
    last_weekly <- "As a reminder, links to the previous Weekly:"
  }

  # GitLab con
  my_gitlab <- gl_connection(
    gitlab_url = gitlab_url,
    private_token = private_token
  )

  # Set the connection for the session
  set_gitlab_connection(my_gitlab)

  issues_open <- gl_list_issues(project = project_id, state = "opened", max_page = max_page_opened)
  issues_closed <- gl_list_issues(project = project_id, state = "closed", max_page = max_page_closed)
  message(paste0(
    "Information: \n",
    dim(issues_open)[1],
    " open issues requested \n",
    dim(issues_closed)[1],
    " close issues requested"
  ))

  issues <- bind_rows(issues_open, issues_closed)

  if (nrow(issues) == 0) {
    message("There are no issues in the repository")
    return(NULL)
  }

  # Info label state event - keep only the last label added
  issues_info_label <- map(
    pull(issues, iid),
    ~ gl_resource_events(
      project_id = project_id,
      resource = "issues",
      resource_id = .x,
      event = "label"
    )
  ) %>%
    bind_rows() %>%
    filter(action != "remove") %>%
    group_by(resource_id) %>%
    filter(created_at == max(created_at)) %>%
    filter(grepl(
      str_c(
        regex_blocked,
        regex_ready,
        regex_done,
        regex_inprogress,
        regex_validation,
        sep = "|"
      ),
      stri_escape_unicode(tolower(label.name))
    )) %>%
    rename(last_state_date = "created_at") %>%
    select(last_state_date, resource_id, label.name)

  #------
  issues_labels <- issues %>%
    rowwise() %>%
    mutate(all_labels = list(na.omit(c(c_across(cols = starts_with("labels")))))) %>%
    ungroup() %>%
    filter(as_date(as_datetime(created_at)) <= date_max)
  # select(all_labels, starts_with("labels"))

  issues_relabel <- issues_labels %>%
    rowwise() %>%
    mutate(
      info = case_when(
        # 2 - Cards from a column - Blocked
        (state == "opened" &
          any(grepl(regex_blocked, stringi::stri_escape_unicode(tolower(all_labels))))) ~
          paste("2todelete - :octagonal_sign:", word_blocked),

        # 4 - Cards from a column - En cours/Review
        (state == "opened" &
          any(grepl(regex_inprogress, stringi::stri_escape_unicode(tolower(all_labels)))) &
          as_date(as_datetime(created_at)) <= date_max) ~
          paste("4todelete - :notepad_spiral:", word_in_progress),

        # 3 - Cards from a column - Validation
        # grepl("a valider|validation", stringi::stri_escape_unicode(tolower("A valider")))
        (state == "opened" &
          any(grepl(regex_validation, stringi::stri_escape_unicode(tolower(all_labels))))) ~
          paste("3todelete - :thumbsup:", word_to_validate),

        # 5 - Cards from a column - Pret/Ready
        (state == "opened" &
          any(grepl(regex_ready, stringi::stri_escape_unicode(tolower(all_labels))))) ~
          paste("5todelete - :thumbsup:", word_ready),

        # 1 - Cards from a column - Done - Will get Validation later in duplicates
        (state == "closed" & as_date(as_datetime(closed_at)) >= date_min) |
          (state == "opened" &
            any(grepl(regex_done, tolower(all_labels))) &
            as_date(as_datetime(closed_at)) >= date_min &
            as_date(as_datetime(closed_at)) <= date_max
          ) ~
          paste("1todelete - :white_check_mark:", word_realised)
      )
    ) # %>%
  # arrange(info) %>%
  # filter(!is.na(info)) %>%
  # select(closed_at, state, info, all_labels) %>%
  # View()
  # issues_labels$state == "opened" &
  # grepl(regex_inprogress, stringi::stri_escape_unicode(tolower(issues_labels$all_labels)))

  # Dupliquer les issues ouvertes cette semaine
  issues_relabel_dup <- issues_relabel %>%
    bind_rows(
      issues_relabel %>%
        filter(as_date(as_datetime(created_at)) >= date_min &
          as_date(as_datetime(created_at)) <= date_max) %>%
        mutate(info = paste("9todelete - :seedling:", word_new_issues))
    ) %>%
    # Dupliquer les issues en cours
    bind_rows(
      issues_relabel %>%
        filter(state == "opened" &
          any(grepl(regex_inprogress, stri_escape_unicode(tolower(all_labels)))) &
          as_date(as_datetime(created_at)) <= date_max) %>%
        mutate(info = paste("6todelete - :notepad_spiral:", word_in_progress))
    )

  if (!any(grepl("assignees.username", names(issues_relabel_dup)))) {
    issues_relabel_dup <- issues_relabel_dup %>%
      mutate(assignees.username = NA)
  }

  issues_relabel_dup <- issues_relabel_dup %>%
    left_join(issues_info_label, by = c("id" = "resource_id"))


  issues_relabel_dup_li <- issues_relabel_dup %>%
    # Add li text
    mutate(
      assignee_notempty = ifelse(is.na(assignees.username), "Not assigned", paste0("@", assignees.username)),
      issue_li = glue("- {title}: [issue {iid}{ifelse(state == \'closed\', \' (closed)\', \'\')}]({web_url}) - {assignee_notempty}")
    ) %>%
    filter(!is.na(info)) %>%
    arrange(info)


  # If daily -> filter issue (recently) + reorder section issues
  if (isTRUE(daily)) {
    issues_relabel_dup_li <- issues_relabel_dup_li %>%
      filter(!(info == paste("3todelete - :thumbsup:", word_to_validate) & as_date(as_datetime(updated_at)) < date_min) &
        !(info == paste("2todelete - :octagonal_sign:", word_blocked) & as_date(as_datetime(updated_at)) < date_min))

    issues_relabel_dup_li <- issues_relabel_dup_li %>%
      mutate(
        info = gsub(info, pattern = paste("3todelete - :thumbsup:", word_to_validate), replacement = paste("1todelete - :heavy_check_mark:", word_to_validate_daily)),
        info = gsub(info, pattern = paste("1todelete - :white_check_mark:", word_realised), replacement = paste("2todelete - :heavy_check_mark:", word_realised_daily)),
        info = gsub(info, pattern = paste("4todelete - :notepad_spiral:", word_in_progress), replacement = paste("3todelete - :memo:", word_in_progress_daily)),
        info = gsub(info, pattern = paste("6todelete - :notepad_spiral:", word_in_progress), replacement = paste("4todelete - :warning:", word_in_progress_alert_daily)),
        info = gsub(info, pattern = paste("2todelete - :octagonal_sign:", word_blocked), replacement = paste("5todelete - :octagonal_sign:", word_blocked_daily)),
        info = gsub(info, pattern = paste("5todelete - :thumbsup:", word_ready), replacement = paste("6todelete - :soon:", word_ready_daily)),
        info = gsub(info, pattern = paste("9todelete - :seedling:", word_new_issues), replacement = paste("9todelete - :seedling:", word_new_issues_daily))
      ) %>%
      arrange(info, updated_at)
  } else { # if WEEKLY
    issues_relabel_dup_li <- issues_relabel_dup_li %>%
      filter(info != paste("6todelete - :notepad_spiral:", word_in_progress))
  }

  all_cards_weekly_text_collapse <- collapse_li(issues_relabel_dup_li) %>%
    mutate(text_weekly_all = str_remove_all(text_weekly_all, "1todelete - |2todelete - |3todelete - |4todelete - |5todelete - |6todelete - |9todelete - "))

  # If daily -> add next date to dev + ref last weekly
  if (isTRUE(daily)) {
    # Add a text at the top to explain that some parts must be deleted
    title_paragraph <- paste0("## Daily - ", date_min, "\n\n\n")
    detail_paragraph <- "_Note for the Lead Dev: Some sections were automatically created. This is the case for the section :warning: and the section :soon:. In the section :warning:, please delete the not-appropriate issues, or write a specific text. In the section :soon:, please arrange the issues according to the priority. Also, you must complete the next date for the mission. => DELETE THIS PARAGRAPH_\n\n\n"

    all_cards_weekly_text_collapse <- all_cards_weekly_text_collapse %>%
      mutate(text_weekly_all = paste(title_paragraph, detail_paragraph, text_weekly_all))

    # Add the link to the previous weekly
    proj_info <- gl_get_project(project = project_id)

    all_cards_weekly_text_collapse <- all_cards_weekly_text_collapse %>%
      mutate(text_weekly_all = paste(
        text_weekly_all,
        paste0(":date: ", next_date),
        paste0(
          ":book: ",
          last_weekly,
          " ",
          paste0(gitlab_url, "/", proj_info$path_with_namespace, "/-/wikis/Weekly")
        ),
        sep = "\n\n\n"
      ))
  }

  out <- list(
    weekly_issues = issues_relabel_dup_li,
    weekly_info = pull(all_cards_weekly_text_collapse)
  )

  if (verbose) {
    cat(out$weekly_info)
  }
  return(out)
}

#' Gets a list of all state events for a single issue.
#' @noRd
gl_resource_events <- function(
  project_id,
  resource_id,
  resource = c("issues", "merge_requests", "epics"),
  event = c("label", "iteration", "milestone", "state", "weight"),
  ...
    ) {
  resource <- match.arg(resource)
  event <- match.arg(event)


  if (resource == "merge_requests" & event %in% c("iteration", "weight")) {
    stop('merge_requests can not be associated with \"iteration\", \"weight\"')
  }
  if (resource == "epics" & event %in% c("iteration", "milestone", "state", "weight")) {
    stop('epics can not be associated with \"iteration\", \"milestone\", \"state\", \"weight\"')
  }

  gitlab(
    req = paste0("projects/", project_id, "/", resource, "/", resource_id, "/resource_", event, "_events"),
    verb = httr::GET,
    ...
  )
}


#' @rdname gl_create_weekly
#' @param ... Additional arguments
#' @export
gl_create_daily <- purrr::partial(gl_create_weekly, daily = TRUE)
