# WARNING - Generated by {fusen} from dev/flat_create_weekly.Rmd: do not edit by hand

#' Visualise the progress of the milestones for GitLab
#'
#' @param project_id Id of the GitLab project
#' @param language Character. Language: 'fr' ou 'en'.
#' @param gitlab_url URL of the GitLab Forge
#' @param private_token Your private GitLab instance token allowed to use the "api".
#' @param color by defaut, warning color
#'
#' @importFrom gitlabr gl_connection set_gitlab_connection gl_proj_req gl_list_issues gitlab
#' @importFrom dplyr rename filter bind_rows group_by count ungroup left_join select mutate desc
#' @importFrom ggplot2 ggplot aes geom_col scale_x_continuous labs theme_minimal theme element_blank
#' @importFrom scales label_number
#' @importFrom forcats fct_reorder
#'
#' @return A ggplot
#' @export
#' @examples
#' \dontrun{
#' gl_get_milestones_progress(
#'   project_id = "<get_your_id_project>",
#'   private_token = Sys.getenv("GITLAB_TOKEN")
#' )
#' }
gl_get_milestones_progress <- function(project_id,
                                       language = c("fr", "en"),
                                       gitlab_url = Sys.getenv("GITLAB_URL", unset = "https://gitlab.com"),
                                       private_token = Sys.getenv("GITLAB_TOKEN"),
                                       color = "#f15522") {
  if (private_token == "") {
    stop("Please specify your private_token. This may be an environment variable named GITLAB_TOKEN")
  }

  # GitLab con
  my_gitlab <- gl_connection(
    gitlab_url = gitlab_url,
    private_token = private_token
  )

  # Set the connection for the session
  set_gitlab_connection(my_gitlab)

  # Language
  language <- match.arg(language,
    several.ok = FALSE
  )

  if (language == "fr") {
    title_plot <- "Progression des milestones"
  } else if (language == "en") {
    title_plot <- "Progression of milestones"
  }

  # Get global info about milestones
  milestones <- gitlab(
    req = gl_proj_req(
      project_id,
      req = "milestones"
    )
  )

  if (nrow(milestones) == 0) {
    message("No milestones recorded for this repository")
    return(NULL)
  }

  milestones <- milestones %>%
    rename(
      milestone_name = title,
      milestone_id = id
    )

  # Get all issues linked to a milestone from API
  data_issues <- purrr::map(
    milestones$milestone_id,
    ~ gitlab(
      req = gl_proj_req(
        project_id,
        req = c("milestones", .x, "issues")
      )
    )
  )

  progress_milestone <- milestones %>%
    select(milestone_id, milestone_name) %>%
    mutate(data = data_issues) %>%
    tidyr::unnest(data, keep_empty = TRUE) %>%
    select(milestone_id, milestone_name, id, iid, title, state) %>%
    group_by(milestone_id, milestone_name) %>%
    summarise(
      nb_closed_issues = sum(state == "closed"),
      total_nb = n(),
      nb_open_issues = sum(state != "closed"),
      progress = 100 * nb_closed_issues / n()
    ) %>%
    ungroup() %>%
    mutate(max_progress = 100) %>%
    select(
      milestone_name,
      milestone_id,
      nb_closed_issues,
      nb_open_issues,
      total_nb,
      progress,
      max_progress
    ) %>%
    mutate(milestone_name = fct_reorder(milestone_name, rev(milestone_id)))


  # Plot
  plot_milestones <- progress_milestone %>%
    ggplot() +
    geom_col(aes(x = max_progress, y = milestone_name),
      col = color, fill = NA, linewidth = 0.10
    ) +
    geom_col(aes(x = progress, y = milestone_name),
      fill = color
    ) +
    scale_x_continuous(
      limits = c(0, 100),
      labels = label_number(suffix = " %")
    ) +
    labs(
      title = title_plot,
      x = "",
      y = ""
    ) +
    theme_minimal() +
    theme(panel.grid = element_blank())

  return(plot_milestones)
}
