# WARNING - Generated by {fusen} from /dev/flat_init_project_with_all.Rmd: do not edit by hand

#' Init a new project with everything in one command
#' 
#' @param project_name The name of the project to be created
#' @param project_gitlab_id GitLab ID of the project if it already exist on your Forge
#' @param config_path The path to the yaml configuration file to use with your options to modify the default one. See details.
#' @param project_path The path to the project if your want to keep it locally. Default to temporary directory.
#' @param ... Any parameter existing in the configuration file that you would like to use to override your config files
#' @details By default, the project is a R package created on <https://gitlab.com/about/> in your personal repository. Use your own configuration file to amend the default one. 
#' The configuration file is a yaml file with all possible options. You do not have to specify all options as it will be combined with our default ones. Open the default one to see what is in it: `file.edit(system.file("config_default_thinkr_gitlab.yml", package = "lozen"))`
#' 
#' 
#' @importFrom yaml read_yaml
#' @importFrom purrr list_modify pluck
#' @importFrom cli cli_text cli_li cli_alert_info
#' @importFrom gitlabr gl_connection set_gitlab_connection gl_get_project
#' @importFrom usethis with_project use_github_action use_r
#' @importFrom gert git_config_set
#' @importFrom glue glue
#' @importFrom gh gh_gql
#' @importFrom yesno yesno
#' @importFrom golem add_rstudioconnect_file
#' @importFrom withr with_dir
#' 
#' @export
#' @examples
#' if (interactive()) {
#'   # Default on GitLab.com
#'   init_project_with_all(project_name = "newprojectpkg")
#'   # Change default options with your own config file
#'   init_project_with_all(project_name = "newprojectpkg", config_path = "<my-config-path>")
#'   # Add any extra option to override values of your config file once
#'   init_project_with_all(project_name = "newprojectpkg", config_path = "<my-config-path>", gitlab_namespace_id = "000")
#' }
init_project_with_all <- function(project_name, project_gitlab_id = NULL, config_path,
                                  project_path = tempfile('clone'), ...) {
  # Read ThinkR default in package
  config_default <- read_yaml(system.file("config_default_thinkr_gitlab.yml", package = "lozen"))
  if (!missing(config_path)) {
    config_user <- read_yaml(config_path)
    # Combine with user config file so that they do not have to define everything
    config <- list_modify(config_default, !!!config_user)
  } else {
    config <- config_default
  }
  # Override with ...
  config_local_dots <- list(...)
  config <- list_modify(config, !!!config_local_dots)

  forge <- tolower(config$forge)
  if (is.null(config$gitlab_namespace_id) || config$gitlab_namespace_id == "") {
    namespace_type = "user"
  } else {
    namespace_type = paste("group with id:", config$gitlab_namespace_id)
  }

  cat(
    cli_text("You are about to create a new project with these configuration:"),
    cli_li(c(
      paste("Forge:", forge),
      ifelse(forge == "gitlab", paste("Forge URL: ", config$gitlab_forge_url),
                   paste("GitHub: ", config$github_url)),
      ifelse(forge == "gitlab", paste("namespace: ", namespace_type),
                   paste("GitHub Owner: ", config$github_owner)),
      paste("project_name: ", project_name),
      paste("project_type: ", config$project_type)
    ))
  )
  # warning for manual steps
  if (forge == "github"){
    cli_alert_warning("Make sure you confirm all the manual steps to create the project")
  }
  answer <- readline("Are you ok with that? (y/n)")
  if (answer %in% c("n", "no")) {message("You stopped the process"); return(NULL)}

  # Connect to GitLab ----
  if (forge == "gitlab") {
    # Init GitLab
    gitlab_url <- Sys.getenv("GITLAB_URL", unset = config$gitlab_forge_url)

    # GitLab con
    my_gitlab <- gl_connection(
      gitlab_url = gitlab_url,
      private_token = Sys.getenv(config$gitlab_envt_token_name)
    )

    # Set the connection for the session
    set_gitlab_connection(my_gitlab)

    # Create / Connect project on GitLab ----
    if (is.null(project_gitlab_id)) {
      # If project does not exist
      project_id <- create_group_project(
        project_name = project_name,
        namespace_id = config$gitlab_namespace_id,
        default_branch = config$default_branch
      )
    }
    the_project <- gl_get_project(
      project = project_id
    )

    project_name <- the_project[["name"]]
    group_url <- gsub(the_project[["name"]], "", the_project[["web_url"]])
    project_url <- the_project$web_url
  }

  # Connect to GitHub ----
  if (forge == "github") {
    # GitHub con
    project_url <- paste(
      config$github_url,
      config$github_owner,
      project_name,
      sep = "/"
    )

    # Create / Connect project on GitHub ----
    project_id <- create_group_project_github(
      repo = project_name,
      owner = config$github_owner
      )

    group_url <- paste(
      config$github_url,
      config$github_owner,
      sep = "/"
    )
  }

  # Retrieve project locally
  project_path <- clone_locally(
    project_name = project_name,
    project_path = file.path(tempfile('clone'), project_name),
    group_url = group_url,
    open = FALSE
  )

  # Create the project
  create_r_project(
    project_path,
    type = config$project_type,
    name_licence = config$name_licence,
    type_licence = eval(parse(text = config$type_licence))
  )
  
  # Add a piece of code to pass codecov
  with_project(
    path = project_path,
    code = {use_r(name = "start", open = FALSE)}
  )
  
  # Add extra dev_history
  use_dev_history(path = project_path, type = config$dev_history)

  # Set up CI GitLab ----
  if (forge == "gitlab") {
    lozen::use_gitlab_ci(
      project_path = project_path,
      type = config$gitlab_ci_type,
      bookdown_output_format = config$bookdown_output_format
    )
  }

  # Set up CI GitHub ----
  if (forge == "github") {
    with_project(
      path = project_path,
      code = {
        sapply(
          X = config$github_ci,
          FUN = \(x) {use_github_action(
            name = x,
            badge = FALSE # requires readme file
          )})
      }
    )
  }

  # What to deploy on Connect GitLab ----
  if (forge == "gitlab") {
    if (isTRUE(config$deploy_connect)) {
      message("Note that you will need to specify some required environment variables in your GitLab project")
      # Deploy book if book
      if (config$project_type == "book") {
        with_dir(project_path, {
          lozen::use_gitlab_ci_deploy_connect_bookdown()
        })
      }
      # Deploy pkgdown if package
      if (config$project_type == "package") {
        with_dir(project_path, {
          lozen::use_gitlab_ci_deploy_connect_pkgdown()
        })
      }
      # Deploy app if golem
      if (config$project_type == "golem") {
        with_dir(project_path, {
          golem::add_rstudioconnect_file(pkg = project_path)
          use_gitlab_ci_deploy_connect_shiny()
        })
      }
    }
  }

  # Commit and MR templates ----
  if (!is.null(config$git_templates) || config$git_templates != "") {
    add_git_templates(
      project_path = project_path,
      type = config$git_templates,
      target_dir = paste0(".", forge)
    )
  }
  
  # Issue template
  if (!is.null(config$template_issue_type) ||
      config$template_issue_type != "") {
    if (forge == "gitlab") {
      gl_add_template_issue(
        project_path = project_path,
        language = config$lang,
        # "fr" # you can use "en" instead
        type = config$template_issue_type
      )
    }
    if (forge == "github") {
      sapply(X = config$template_issue_type,
             FUN = \(x) {
               gh_add_template_issue(
                 project_path = project_path,
                 language = config$lang,
                 # "fr" # you can use "en" instead
                 type = x
               )
             })
    }
  }
  
  # Name branch and push to server ----
  git_config_set(
    name = "init.defaultbranch",
    value = config$default_branch,
    repo = project_path
  )
  push_main(
    project_path = project_path
  )

  # Add production branch
  if (isTRUE(config$git_production_branch)) {
    create_production(
      project_path = project_path
    )
  }

  # Git configuration GitLab ----
  if (forge == "gitlab") {
    # Protect branches ----
    if (isTRUE(config$gitlab_protect_branches)) {
      protect_branches(
        project_id = project_id
      )
    }

    # Autoclose and coverage ----
    if (isTRUE(config$gitlab_protect_branches)) {
      modify_autoclose_and_coverage(
        project_id = project_id,
        autoclose = config$gitlab_autoclose_issue,
        build_coverage_regex = config$gitlab_coverage_regex
      )
    }
  }

  # Git configuration GitHub ----
  if (forge == "github") {
    # Protect branches ----
    protect_url <- paste0(
      project_url,
      "/settings/branch_protection_rules/new?branch_name=",
      config$default_branch
    )
    cli_alert_info(text = "To protech your branch, please visit :\n {.url {protect_url}}")
    continue <- yesno("Manual step in progress : protecting branch. Can we continue ?")
    if (isFALSE(continue)) {message("You stopped the process"); return(NULL)}
  }
  
  # GitLab project setup ----
  if (forge == "gitlab") {
    add_labels(
      project_id = project_id,
      lg = config$lang
    )

    add_board(
      project_id = project_id,
      name = config$gitlab_board_name,
      labels_order = config$gitlab_board_labels_order,
      lg = config$lang
    )
  }
  
  # GitHub project setup ----
  if (forge == "github") {
    # Create project/board from graphql api
    # fetch user/orga node id
    req_user_node_id <- glue(
      'query{
        $_owner_type_$(login: "$_organization_$"){
          id
        }
      }',
      .open = "$_",
      .close = "_$",
      owner_type = config$owner_type,
      organization = config$github_owner,
      )
    
    user_node_id <- gh::gh_gql(
      query = req_user_node_id,
      .token = Sys.getenv(config$gitlab_envt_token_name)
      ) %>%
      pluck("data", "user", "id")

    # create board
    req_project_create <- glue(
      'mutation{
        createProjectV2(
          input: {
            ownerId: "$_user_node_id_$",
            title: "$_project_name_$"
          }
        ){
          projectV2 {
            id
            number
          }
         }
      }',
      .open = "$_",
      .close = "_$")
    
    project_id <- gh::gh_gql(
      query = req_project_create,
      .token = Sys.getenv(config$gitlab_envt_token_name)
      )
    project_id <- project_id %>%
      pluck("data", "createProjectV2", "projectV2")

    # Notify user of the remaining manual steps
    proj_url <- paste0(project_url, "/projects")
    cli_alert_info(
      "The project board has been created, you can link it to the repo here :
                        {.url {proj_url}}
                        You can search for the project {.emph {project_name}} after clicking on {.emph Link a project}"
    )
    continue <- yesno("Manual step in progress : linking project to repo. Can we continue ?")
    if (isFALSE(continue)) {
      message("You stopped the process")
      return(NULL)
    }
    
    board_url <- paste0(proj_url, "/", project_id[["number"]], "/views/2")
    cli_alert_info("The board is here : {.url {board_url}}")
    cli_alert_info("The following columns of the project should be manually added :")
    cli_li(config$github_board_columns)
    continue <- yesno("Manual step in progress : adding columns to project. Can we continue ?")
    if (isFALSE(continue)) {
      message("You stopped the process")
      return(NULL)
    }
  }

  # Special issues and wiki GitHub ----
  if (forge == "github") {
    if (isTRUE(config$issue_client)) {
      add_issue_clients_github(
        owner = config$github_owner,
        repo = project_name
      )
    }
    
    if (isTRUE(config$issue_kickoff)) {
      add_issue_kickoff_github(
        owner = config$github_owner,
        repo = project_name
      )
    }
    
    if (isTRUE(config$issue_dev)) {
      add_issue_dev_github(
        owner = config$github_owner,
        repo = project_name
      )
    }
    
    # Link issues to project on GitHub
    if (forge == "github") {
      issue_url <- paste0(project_url, "/issues")
      cli_alert_info("You need to assign the new issues to the project board. :
                  {.url {issue_url}}")
      continue <- yesno("Manual step in progress : linking issue to project. Can we continue ?")
      if (isFALSE(continue)) {
        message("You stopped the process")
        return(NULL)
      }
    }
    
    if (isTRUE(config$wiki)) {
      add_wikis_github(
        owner = config$github_owner,
        repo = project_name,
        type = config$wiki_types
      )
    }
  }

  # Special issue and wiki GitLab
  if (forge == "gitlab") {
    if (isTRUE(config$issue_client)) {
      add_issue_clients(
        project_id = project_id,
        project_name = project_name,
        group_url = group_url
      )
    }
    
    if (isTRUE(config$issue_kickoff)) {
      add_issue_kickoff(
        project_id = project_id
      )
    }
    
    if (isTRUE(config$issue_dev)) {
      add_issue_dev(
        project_id = project_id,
        group_url = group_url,
        project_name = project_name
      )
    }
    
    if (isTRUE(config$wiki)) {
      add_wikis(
        project_id = project_id,
        project_name = project_name,
        group_url = group_url,
        group = basename(group_url),
        type = config$wiki_types
      )
    }
  }
  
  cat(
    cli::cli_text("Find your project on: {.url  {project_url}} ")
  )

  return(list(project_url = project_url,
              project_path = project_path))
}

