# WARNING - Generated by {fusen} from dev/flat_init_project_with_all.Rmd: do not edit by hand

#' Init a new project with everything in one command
#' 
#' @param project_name The name of the project to be created
#' @param project_gitlab_id GitLab ID of the project if it already exist on your Forge
#' @param config_path The path to the yaml configuration file to use with your options to modify the default one. See details.
#' @param project_path The path to the project if your want to keep it locally. Default to temporary directory.
#' @param ... Any parameter existing in the configuration file that you would like to use to override your config files
#' @details By default, the project is a R package created on <https://gitlab.com/about/> in your personal repository. Use your own configuration file to amend the default one. 
#' The configuration file is a yaml file with all possible options. You do not have to specify all options as it will be combined with our default ones. Open the default one to see what is in it: `file.edit(system.file("config_default_thinkr_gitlab.yml", package = "lozen"))`
#' 
#' @export
#' @examples
#' if (interactive()) {
#'   # Default on GitLab.com
#'   init_project_with_all(project_name = "newprojectpkg")
#'   # Change default options with your own config file
#'   init_project_with_all(project_name = "newprojectpkg", config_path = "<my-config-path>")
#'   # Add any extra option to override values of your config file once
#'   init_project_with_all(project_name = "newprojectpkg", config_path = "<my-config-path>", gitlab_namespace_id = "000")
#' }
init_project_with_all <- function(project_name, project_gitlab_id = NULL, config_path,
                                  project_path = tempfile('clone'), ...) {
  # Read ThinkR default in package
  config_default <- yaml::read_yaml(system.file("config_default_thinkr_gitlab.yml", package = "lozen"))
  if (!missing(config_path)) {
    config_user <- yaml::read_yaml(config_path)
    # Combine with user config file so that they do not have to define everything
    config <- purrr::list_modify(config_default, !!!config_user)
  } else {
    config <- config_default
  }
  # Override with ...
  config_local_dots <- list(...)
  config <- purrr::list_modify(config, !!!config_local_dots)
  
  forge <- tolower(config$forge)
  if (is.null(config$gitlab_namespace_id) || config$gitlab_namespace_id == "") {
    namespace_type = "user"
  } else {
    namespace_type = paste("group with id:", config$gitlab_namespace_id)
  }
  
  cat(
    cli::cli_text("You are about to create a new project with these configuration:"),
    cli::cli_li(c(
      paste("Forge:", forge),
      ifelse(forge == "gitlab", paste("Forge URL: ", config$gitlab_forge_url),
                   paste("GitHub: ", config$github_url)),
      ifelse(forge == "gitlab", paste("namespace: ", namespace_type),
                   paste("GitHub Owner: ", config$github_owner)),
      paste("project_name: ", project_name),
      paste("project_type: ", config$project_type)
    ))
  )
  answer <- readline("Are you ok with that? (y/n)")
  if (answer %in% c("n", "no")) {message("You stopped the process"); return(NULL)}
  
  # Connect to GitLab ----
  if (forge == "gitlab") {
    # Init GitLab
    gitlab_url <- Sys.getenv("GITLAB_URL", unset = config$gitlab_forge_url)
    
    # GitLab con
    my_gitlab <- gl_connection(
      gitlab_url = gitlab_url,
      private_token = Sys.getenv(config$gitlab_envt_token_name)
    )
    
    # Set the connection for the session
    set_gitlab_connection(my_gitlab)
    
    
    # Create / Connect project on GitLab ----
    if (is.null(project_gitlab_id)) {
      # If project does not exist
      project_id <- create_group_project(
        project_name = project_name,
        namespace_id = config$gitlab_namespace_id,
        default_branch = config$default_branch
      )
    } 
    the_project <- gl_get_project(
      project = project_id
    )
    
    project_name <- the_project[["name"]]
    group_url <- gsub(the_project[["name"]], "", the_project[["web_url"]])
    project_url <- the_project$web_url
  }
  
  # Retrieve project locally - GitLab ok, but GitHub ?
  project_path <- clone_locally(
    project_name = project_name,
    project_path = file.path(tempfile('clone'), project_name),
    group_url = group_url,
    open = FALSE
  )
  
  # Create the project
  create_r_project(
    project_path,
    type = config$project_type,
    name_licence = config$name_licence,
    type_licence = eval(parse(text = config$type_licence))
  )
  
  # Add extra dev_history
  use_dev_history(path = project_path, type = config$dev_history)
  
  # Set up CI ----
  if (forge == "gitlab") {
    lozen::use_gitlab_ci(
      project_path = project_path,
      type = config$gitlab_ci_type,
      bookdown_output_format = config$bookdown_output_format
    )
  }
  
  # What to deploy on Connect ----
  if (forge == "gitlab") {
    if (isTRUE(config$deploy_connect)) {
      message("Note that you will need to specify some required environment variables in your GitLab project")
      # Deploy book if book
      if (config$project_type == "book") {
        withr::with_dir(project_path, {
          lozen::use_gitlab_ci_deploy_connect_bookdown()
        })
      }
      # Deploy pkgdown if package
      if (config$project_type == "package") {
        withr::with_dir(project_path, {
          lozen::use_gitlab_ci_deploy_connect_pkgdown()
        })
      }
      # Deploy app if golem
      if (config$project_type == "golem") {
        withr::with_dir(project_path, {
          golem::add_rstudioconnect_file(pkg = project_path)
          use_gitlab_ci_deploy_connect_shiny()
        })
      }
    }
  }
  
  # Commit and MR templates ---- 
  if (!is.null(config$git_templates) || config$git_templates != "") {
    add_git_templates(
      project_path = project_path,
      type = config$git_templates
    )
  }
  
  # Push to server ----
  push_main(
    project_path = project_path
  )
  
  if (isTRUE(config$git_production_branch)) {
    create_production(
      project_path = project_path
    )
  }
  
  # Git configuration ----
  if (forge == "gitlab") {
    # Protect branches ----
    if (isTRUE(config$gitlab_protect_branches)) {
      protect_branches(
        project_id = project_id
      )
    }
    
    # Autoclose and coverage ----
    if (isTRUE(config$gitlab_protect_branches)) {
      modify_autoclose_and_coverage(
        project_id = project_id,
        autoclose = config$gitlab_autoclose_issue,
        build_coverage_regex = config$gitlab_coverage_regex
      )
    }
  }
  
  if (forge == "gitlab") {
    if (!is.null(config$template_issue_type) || config$template_issue_type != "") {
      gl_add_template_issue(
        project_path = project_path,
        language = config$lang, # "fr" # you can use "en" instead
        type = config$template_issue_type
      )
    }
  }
  
  # GitLab project setup ----
  if (forge == "gitlab") {
    add_labels(
      project_id = project_id,
      lg = config$lang
    )
    
    add_board(
      project_id = project_id,
      name = config$gitlab_board_name,
      labels_order = config$gitlab_board_labels_order,
      lg = config$lang
    )
    
    if (isTRUE(config$issue_client)) {
      add_issue_clients(
        project_id = project_id,
        project_name = project_name,
        group_url = group_url
      )
    }
    
    if (isTRUE(config$issue_kickoff)) {
      add_issue_kickoff(
        project_id = project_id
      )
    }
    
    if (isTRUE(config$issue_dev)) {
      add_issue_dev(
        project_id = project_id,
        group_url = group_url,
        project_name = project_name
      )
    }
    
    if (isTRUE(config$wiki)) {
      add_wikis(
        project_id = project_id,
        project_name = project_name,
        group_url = group_url,
        group = basename(group_url),
        type = config$wiki_types
      )
    }
  }
  # GitHub project setup ----
  if (forge == "github") {
    # add_labels(
    #   project_id = project_id,
    #   lg = config$lang
    # )
    
    add_board_github(
      owner = config$github_owner,
      repo = project_name,
      columns = config$github_board_columns
    )
    
    if (isTRUE(config$issue_client)) {
      add_issue_clients_github(
        owner = config$github_owner,
        repo = project_name
      )
    }
    
    if (isTRUE(config$issue_kickoff)) {
      add_issue_kickoff_github(
        owner = config$github_owner,
        repo = project_name
      )
    }
    
    if (isTRUE(config$issue_dev)) {
      add_issue_dev_github(
        owner = config$github_owner,
        repo = project_name
      )
    }
    
    if (isTRUE(config$wikis)) {
      add_wikis_github(
        owner = config$github_owner,
        repo = project_name,
        type = config$wiki_types
      )
    }
  }
  
  cat(
    cli::cli_text("Find your project on: {.url  {project_url}} ")
  )
  
  return(list(project_url = project_url,
              project_path = project_path))
}

