# WARNING - Generated by {fusen} from dev/flat_create_r_project_skeleton.Rmd: do not edit by hand

#' Une a dev histroy file
#'
#' @param path Path to project to add dev_history in
#' @param type Type of dev_history. Multiple types possible among "package", "book", "renv".
#'
#' @export
#' @examples
#' withr::with_tempdir({
#'   use_dev_history(path = ".", type = c("package", "book", "renv"))
#' })
use_dev_history <- function(path = ".", type = c("package", "renv")) {
  type <- match.arg(type, choices = c("package", "book", "renv"), several.ok = TRUE)

  old <- setwd(path)
  on.exit(setwd(old))

  if (!dir.exists(file.path(path, "dev"))) {
    dir.create(file.path(path, "dev"))
  }

  if (any(grepl("connect", type))) {
    add_git_ignore("rsconnect/", directory = path)
  }

  for (i in type) {
    file <- system.file("package", paste0("dev_history_", i, ".R"), package = "lozen")
    if (file == "") {
      file <- system.file("package", paste0("dev_history_", i, ".Rmd"), package = "lozen")
    }
    if (file == "") {
      file <- system.file("package", paste0("flat_", i, ".Rmd"), package = "lozen")
    }
    if (file == "") {
      stop("template ", i, " not found")
    }
    file.copy(file, file.path(path, "dev"))
  }

  add_build_ignore("dev")
}
