# WARNING - Generated by {fusen} from dev/flat_manage_gitlab_projects.Rmd: do not edit by hand

#' modify_autoclose_and_coverage on GitLab
#'
#' @param project_id project_id
#' @param autoclose Logical. Whether to autoclose issues when merged to main
#' @param build_coverage_regex Character. regex used to retrieve code coverage in Ci logs.
#'
#' @return Side Effect on GitLab
#' @importFrom gitlabr gitlab
#' @export
#'
#' @examples
#' \dontrun{
#' modify_autoclose_and_coverage(
#'   project_id = project_id
#' )
#' }
modify_autoclose_and_coverage <- function(project_id, autoclose = FALSE,
                                          build_coverage_regex = "Coverage: \\d+\\.\\d+") {
  protect_prod <- gitlab(
    req = paste0("projects/", project_id),
    verb = httr::PUT,
    autoclose_referenced_issues = autoclose,
    build_coverage_regex = build_coverage_regex
  )
  message("Issues are set to", ifelse(autoclose, " ", " not "), "auto-close when merged in \'main\'")
  message("build_coverage_regex is set to: ", build_coverage_regex)
}
