# WARNING - Generated by {fusen} from /dev/flat_book_utils.Rmd: do not edit by hand

#' Render pagedown html_paged
#'
#' @return A pagedown template
#' @inheritParams pagedown::html_paged
#' @importFrom pagedown html_paged
#' @export
#'
#' @examples
#' \dontrun{
#' rmarkdown::render("my_file.Rmd", output_format = lozen::paged_template)
#' #'}
paged_template <- function(    
    ...
) {    
  html_paged(    
    ...
  )
}
