# WARNING - Generated by {fusen} from dev/flat_book_utils.Rmd: do not edit by hand

#' Render pagedown html_paged
#'
#' @return A pagedown template
#' @inheritParams pagedown::html_paged
#' @export
#'
paged_template <- pagedown::html_paged
