# WARNING - Generated by {fusen} from /dev/flat_manage_gitlab_projects.Rmd: do not edit by hand

#' Define project status for a user
#'
#' @param project_id project_id
#' @param level The notification levels among disabled, participating,
#' watch, global, mention, custom
#' @return Side Effect on GitLab, allow reception of notifications.
#' @export
#' @examples
#' \dontrun{
#' project_options(
#'   project_id,
#'   level = "watch"
#' )
#' }
project_options <- function(project_id, level = "watch") {
  level <- match.arg(
    level,
    c(
      "disabled",
      "participating",
      "watch",
      "global",
      "mention",
      "custom"
    )
  )

  protect_notif <- gitlab(
    req = c("projects", project_id, "notification_settings"),
    verb = httr::PUT,
    level = level
  )

  message("Notification setting set for you only: ", protect_notif$level)
}
