# WARNING - Generated by {fusen} from dev/flat_manage_git.Rmd: do not edit by hand

#' Push everything on a branch
#'
#' @param project_path project_path
#' @param message commit message
#' @param branch branch name. main by default
#' @param main_branch main branch name. main by default
#' @export
#'
#' @return Side effect: commit output
#' @examples
#' \dontrun{
#' push_all_to_branch(
#'   project_path = project_path
#' )
#' }
push_all_to_branch <- function(project_path, branch = "main", main_branch = "main", message = "Init repo") {
  # If already a git repo
  if (branch != main_branch) {
    if (gert::git_branch_exists(branch = branch, repo = project_path)) {
      gert::git_branch_checkout(branch = branch, repo = project_path)
    } else {
      message(paste("branch", branch, "does not exist. It will be created."))
      gert::git_branch_create(branch = branch, ref = main_branch, repo = project_path)
      gert::git_branch_checkout(branch = branch, repo = project_path)
    }
  }

  # Commit the change
  all_files <- list.files(project_path, recursive = TRUE, all.files = TRUE)
  all_files <- all_files[!grepl("[.]git/", all_files)]
  added <- gert::git_add(files = all_files, repo = project_path)
  if (nrow(added) > 0) {
    gert::git_commit(message = message, repo = project_path)
  }

  # Push
  gert::git_push(repo = project_path)
  message(paste0("'", gert::git_branch(repo = project_path), "' pushed to remote server"))
}

#' Push main to server
#' @inheritParams  push_all_to_branch
#' @export
push_main <- function(project_path, branch = "main", main_branch = "main", message = "Init repo") {
  push_all_to_branch(branch = branch, main_branch = main_branch, project_path = project_path, message = message)
}


#' Push master to server
#' @inheritParams  push_all_to_branch
#' @export
push_master <- function(project_path, branch = "master", main_branch = "master", message = "Init repo") {
  push_all_to_branch(branch = branch, main_branch = main_branch, project_path = project_path, message = message)
}
