# WARNING - Generated by {fusen} from dev/flat_init_gitlab_ci.Rmd: do not edit by hand

#' read_ci
#'
#' Import yaml CI files as list
#'
#' @param path Path to the yaml file
#'
#' @importFrom yaml read_yaml
#'
#' @return list a list of all CI parameters
#' @export
#'
#' @examples
#' yaml_path <- system.file("yaml", ".gitlab-ci-shiny.yml", package = "lozen")
#' ci_list <- read_ci(path = yaml_path)
read_ci <- function(path = "./.gitlab-ci.yml") {
  ci_list <- read_yaml(file = path, handlers = list("seq" = as.list))
  return(ci_list)
}
