# WARNING - Generated by {fusen} from /dev/flat_use_gitlab_ci_deploy_connect.Rmd: do not edit by hand

#' Add a job to deploy a something on Connect
#'
#' This function creates a file .gitlab-ci.yml
#' that will deploy something on Connect using a `lozen::deploy_connect_*` functions.
#'
#' Before using it, please follow these steps :
#'
#' - Ask the Mission Lead Dev for their deployment token on Connect, this is the one you will need to use.
#'
#' - Add the environment variables in the private variable hidden in the GitLab repository:
#' Settings > CI/CD > Variables > Expand > Add variable /!\ if you check "Protected" when you create the variable, then it will be active only for protected branches
#'
#'   + Add `CONNECT_USER` with username.
#'   + Add `CONNECT_TOKEN` with the token.
#'
#' If you want to deploy an app
#' Be sure to have an app.R to deploy at the root of the folder, (if needed: use [golem::add_rstudioconnect_file()])
#'
#' NB: The environment variable `CONNECT_URL` is already defined generically on forge (only for group "thinkr").
#'
#' @return used for side effects

#' @param stage_name name of the CI stage (need to be unique in the .gitlab-ci.yml file)
#' @param deploy_function string caracter name of the `deploy_connect_*` functions to use.
#' @param image  Docker image to use
#' @param dir Directory to deploy
#' @param append append the file .gitlab-ci.yml if it already exists
#' @param file_name Name of the yaml file
#' @param ... param to pass to  deploy_function
#'
#' @importFrom yaml write_yaml
#' @importFrom glue glue
#'
#' @export
#' @examples
#' #
use_gitlab_ci_deploy_connect <- function(
  deploy_function = c("deploy_connect_shiny", "deploy_connect_pkgdown", "deploy_connect_bookdown"),
  stage_name = "deploy_connect",
  image = "rocker/verse:latest",
  dir = ".",
  append = TRUE,
  file_name = ".gitlab-ci.yml",
  ...
    ) {
  deploy_function <- match.arg(deploy_function)

  path_to_yaml <- check_if_yaml_exists(
    dir = dir,
    file_name = file_name,
    append = append
  )


  connect_ci_list <- create_deploy_ci_stage(
    image = image,
    stage_name = stage_name,
    deploy_function = deploy_function,
    ...
  )



  amend_yaml(
    path_to_yaml = path_to_yaml,
    connect_ci_list = connect_ci_list
  )

  path_to_yaml
}

#' @rdname use_gitlab_ci_deploy_connect
#' @importFrom cli cli_alert_warning
#' 
#' @export
#' @examples
#' use_gitlab_ci_deploy_connect_bookdown()
use_gitlab_ci_deploy_connect_bookdown <- function(...){    
    if (!dir.exists("_book")) {
    cli_alert_warning(
      "There is no _book directory at the root of your package. You should probably compile your book with `lozen::render_book(\"index.Rmd\", output_format = \"lozen::bs4_book_template\")` or `lozen::render_book(\"index.Rmd\", output_format = \"lozen::paged_template\")` first."
    )
    cli_alert_warning(
      "Once this is done, please ensure your _book directory is not listed in your .gitignore file !"
    )
  }
  use_gitlab_ci_deploy_connect(
    stage_name = "deploy_connect_bookdown",
    deploy_function = "deploy_connect_bookdown",
    ...
  )    
}

#' @export
#' @rdname use_gitlab_ci_deploy_connect

#' @examples
#' # Exemple avec pkgdown
#' deployed_pkgdown <- tempfile(pattern = "pkgdown")
#' dir.create(deployed_pkgdown)
#' # rstudioapi::filesPaneNavigate(deployed_pkgdown)
#' withr::with_dir(deployed_pkgdown, {
#'   use_gitlab_ci(type = "check-coverage-pkgdown")
#'   use_gitlab_ci_deploy_connect_pkgdown()
#' })
use_gitlab_ci_deploy_connect_pkgdown <- function(...) {
  use_gitlab_ci_deploy_connect(
    stage_name = "deploy_connect_pkgdown",
    deploy_function = "deploy_connect_pkgdown",
    ...
  )
}

#' @importFrom cli cli_alert_warning
#' @export
#' @rdname use_gitlab_ci_deploy_connect

#' @examples
#' deployed_shiny <- tempfile(pattern = "shiny")
#' dir.create(deployed_shiny)
#' # rstudioapi::filesPaneNavigate(deployed_shiny)
#' # Exemple avec shiny
#' withr::with_dir(deployed_shiny, {
#'   use_gitlab_ci(type = "check-coverage-pkgdown")
#'   use_gitlab_ci_deploy_connect_shiny()
#' })
use_gitlab_ci_deploy_connect_shiny <- function(...) {
  if (!file.exists("app.R")) {
    cli_alert_warning(
      "There is no app.R at the root of your package. You should probably run `golem::add_rstudioconnect_file()` to create this file."
    )
  }

  use_gitlab_ci_deploy_connect(
    stage_name = "deploy_connect_shiny",
    deploy_function = "deploy_connect_shiny",
    ...
  )
}
