# WARNING - Generated by {fusen} from dev/flat_init_gitlab_ci.Rmd: do not edit by hand

# Gitlab-CI
#'
#' Set gitlab continuous integration
#'
#' @param image Docker image used as basis. See \url{https://github.com/rocker-org/rocker}
#' @param project_path Path of the project to add CI in.
#' @param bookdown_output_format If type="bookdown" it corresponds to the function used to output the bookdown
#' @inheritParams gitlabr::use_gitlab_ci
#' @importFrom cli cli_alert_info
#'
#' @details See \code{\link[gitlabr]{use_gitlab_ci}}
#'
#' @export
#' @examples
#' withr::with_tempdir({
#'   use_gitlab_ci(image = "r-base")
#' })
#'
#' withr::with_tempdir({
#'   use_gitlab_ci(
#'     image = "rocker/verse",
#'     repo_name = "https://packagemanager.rstudio.com/all/__linux__/focal/latest",
#'     type = "check-coverage-pkgdown"
#'   )
#' })
use_gitlab_ci <- function(
    image = "rocker/verse",
    repo_name = "https://packagemanager.rstudio.com/all/__linux__/focal/latest",
    project_path = ".",
    type = "check-coverage-pkgdown",
    bookdown_output_format = c("lozen::paged_template", "lozen::bs4_book_template"),
    overwrite = TRUE) {
  ci_file <- file.path(project_path, ".gitlab-ci.yml")

  if (
    !file.exists(ci_file)
  ) {
    cli_alert_info("There is no {ci_file} in your project, a new one will be created.")
  } else {
    if (isFALSE(overwrite)) {
      overwrite <- askYesNo(
        glue("The file {ci_file} already exists. Do you want to overwrite it ?"),
        default = FALSE
      )
    } else {
      cli_alert_info("Overwriting {ci_file}")
      overwrite <- TRUE
    }
  }


  # Stop if file exist and append not permitted
  if (
    file.exists(ci_file) &&
      !overwrite
  ) {
    stop(glue("The file {ci_file} already exists. Please remove it or use the argument overwrite = TRUE"))
  }

  gitlabr::use_gitlab_ci(
    image = image,
    repo_name = repo_name,
    path = ci_file,
    type = type
  )

  if (grepl("check", type)) {
    lines <- readLines(ci_file)

    install_local <- grep("remotes::install_local\\(upgrade = \"always\"\\)", lines)
    lines[install_local] <- gsub(
      'upgrade = \"always\")',
      'upgrade = \"always\", dependencies = TRUE)',
      lines[install_local]
    )

    script <- grep('"--as-cran"', lines)
    lines[script] <- gsub(',\\s*"--as-cran"', "", lines[script])
    lines[script] <- gsub('"--as-cran"', "", lines[script])

    writeLines(enc2utf8(lines), ci_file)
  }

  if (grepl("pkgdown", type)) {
    lines <- readLines(ci_file)

    stage <- grep("stage: pkgdown$", lines)
    script <- grep("script", lines)
    renv <- grep("renv::restore", lines)

    if (length(renv) == 0) {
      extra <- script[script > stage][1]
    } else {
      renv_extra <- renv[renv > stage][1]
      extra <- script[script > renv_extra][1]
    }
    lines[extra] <- paste0(
      lines[extra],
      "\n",
      # Add extra line
      '    - Rscript -e \'install.packages("thinkrtemplate", repos = c("thinkropen" = "https://thinkr-open.r-universe.dev"))\''
    )

    writeLines(enc2utf8(lines), ci_file)
  }

  if (grepl("bookdown", type)) {
    match.arg(bookdown_output_format, c("lozen::paged_template", "lozen::bs4_book_template"), several.ok = FALSE)
    lines <- readLines(ci_file)

    bookdown_lines <- which(grepl(pattern = "Rscript -e 'bookdown::render_book", x = lines))

    if (length(bookdown_lines) >= 0) {
      if (bookdown_output_format[1] == "lozen::paged_template") {
        line_to_add <- "        - Rscript -e 'install.packages(\"lozen\", repos = c(\"https://thinkr-open.r-universe.dev\", \"https://cran.rstudio.com\"));bookdown::render_book(\"index.Rmd\", output_format = \"lozen::paged_template\", clean = FALSE);file.copy(\"_main.html\", \"public/index.html\")'"
      } else {
        line_to_add <- "        - Rscript -e 'install.packages(\"lozen\", repos = c(\"https://thinkr-open.r-universe.dev\", \"https://cran.rstudio.com\"));bookdown::render_book(\"index.Rmd\", output_format = \"lozen::bs4_book_template\", output_dir = \"public\", clean = FALSE)'"
      }
    }


    lines <- c(
      lines[1:(min(bookdown_lines) - 1)],
      line_to_add,
      lines[(max(bookdown_lines) + 1):length(lines)]
    )

    writeLines(enc2utf8(lines), ci_file)
  }

  ci_file
}
