# WARNING - Generated by {fusen} from /dev/flat_create_weekly.Rmd: do not edit by hand

#' Visualise the nature of the developments (conventional commits)
#'
#' @param project_id Id of the GitLab project
#' @param gitlab_url URL of the GitLab Forge
#' @param private_token Your private GitLab instance token allowed to use the "api".
#' @param path Path of the project if already pulled locally
#' @param ref Branch name (or commit sha) from which to explore commits. By default NULL, it use the default branch
#' @param date_min Minimal date to search from. The oldest date.
#' @param date_max Maximal date to search to. The more recent date.
#' @param language Character. Language: 'fr' ou 'en'.
#' @param conv_tags Conventional commits tags
#' @param color blue color for a graph
#'
#' @importFrom gitlabr gl_connection set_gitlab_connection gl_get_project
#' @importFrom tidyr unnest replace_na
#' @importFrom stringr str_detect str_extract_all
#' @importFrom dplyr filter select mutate group_by count ungroup as_tibble n
#' @importFrom purrr map_dfr
#' @importFrom lubridate as_date as_datetime
#' @importFrom ggplot2 ggplot aes geom_col scale_x_discrete labs theme_bw
#' @importFrom forcats fct_expand fct_relevel
#'
#' @return A ggplot
#' @export
#' @examples
#' \dontrun{
#' 
#'   visualise_commits(
#'     project_id = "<get_your_id_project>",
#'     gitlab_url = Sys.getenv("GITLAB_URL", unset = "https://gitlab.com"),
#'     date_min = "2022-09-22",
#'     date_max = "2022-09-29",
#'     private_token = Sys.getenv("GITLAB_TOKEN")
#'   )
#' 
#'   # Or on project already cloned
#'   tempdir <-
#'     clone_locally(full_url = "https://gitlab.com/my_name/my_repo", open = FALSE)
#' 
#'   visualise_commits(
#'     path = tempdir,
#'     date_min = "2022-09-22",
#'     date_max = "2022-09-29"
#'   )
#' }
visualise_commits <- function(project_id,
                              gitlab_url = Sys.getenv("GITLAB_URL", unset = "https://gitlab.com"),
                              private_token = Sys.getenv("GITLAB_TOKEN"),
                              path,
                              ref = NULL,
                              date_min = Sys.Date() - 7,
                              date_max = Sys.Date(),
                              language = c("fr", "en"),
                              conv_tags = c("feat", "fix", "doc", "test", "ci", "refactor", "style", "chore"),
                              color = "#15b7d6") {
  if (missing(path)) {
    if (private_token == "") {
      stop(
        "Please specify your private_token. This may be an environment variable named GITLAB_TOKEN"
      )
    }

    # GitLab con
    my_gitlab <- gl_connection(
      gitlab_url = gitlab_url,
      private_token = private_token
    )

    # Set the connection for the session
    set_gitlab_connection(my_gitlab)

    the_project <- gl_get_project(project = project_id)
    group_url <- gsub(the_project[["name"]], "", the_project[["web_url"]])

    path <- clone_locally(
      project_name = the_project[["name"]],
      group_url = group_url,
      open = FALSE
    )
  }

  date_min <- as_date(date_min)
  date_max <- as_date(date_max)

  if (date_max < date_min) {
    stop("date_min should be lower or equal to date_max")
  }

  # Language
  language <- match.arg(language,
    several.ok = FALSE
  )
  conv_tags <- tolower(conv_tags)

  if (language == "fr") {
    title_plot <- "R\u00e9partition des d\u00e9veloppements r\u00e9alis\u00e9s"
    title_y <- "Nombre de commits concern\u00e9s"
    title_period <- "P\u00e9riode"
  } else if (language == "en") {
    title_plot <- "Distribution of realised developments"
    title_y <- "Number of commits involved"
    title_period <- "Period"
  }

  # Get commits
  all_commits <- git2r::commits(
    repo = path, ref = ref,
    topological = TRUE, time = TRUE, reverse = FALSE
  ) %>%
    map_dfr(as_tibble) %>%
    mutate(order = rev(1:n()))


  if (nrow(all_commits) == 0) {
    message("There are no commits in the repository")
    return(NULL)
  }

  # Filter commits in range date and delete Merge requests commits
  commits_date_range <- all_commits %>%
    filter(as_date(as_datetime(when)) >= date_min &
      as_date(as_datetime(when)) <= date_max) %>%
    filter(!str_detect(message, "^merge")) %>%
    mutate(message = tolower(message))

  # TODO: extract tags:

  if (nrow(commits_date_range) == 0) {
    message("There are no commits for this period in the repository")
    return(NULL)
  }

  # Filter commits that respect the conventional commit style
  commits_conv <- commits_date_range %>%
    mutate(conv_title = str_extract_all(message,
      pattern = paste(paste0("^", conv_tags), collapse = "|")
    )) %>%
    select(sha, conv_title) %>%
    unnest(conv_title, keep_empty = TRUE) %>%
    replace_na(list(conv_title = "undefined")) %>%
    mutate(
      conv_title = fct_expand(conv_title, conv_tags),
      conv_title = fct_relevel(conv_title, conv_tags)
    )

  # Count and plots
  plot_commits <- commits_conv %>%
    group_by(conv_title) %>%
    count() %>%
    ungroup() %>%
    ggplot() +
    aes(x = conv_title, y = n) +
    geom_col(fill = color) +
    scale_x_discrete(drop = FALSE) +
    labs(
      title = title_plot,
      x = "",
      y = title_y,
      caption = paste(title_period, " : ", date_min, " - ", date_max)
    ) +
    theme_bw()

  return(plot_commits)
}
